;;;;;;;;;; INES HEADER ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
.DB "NES"  
.DB $1A						; MS_DOS END OF FILE
.DB $10						; SIZE OF PRG ROM in # of 16k banks
.DB $10						; SIZE OF CHR ROM in # of 8k banks
.DB %01000010				; mapper number (bits 7-4 ) + battery backing (bit 1) + mirroring (bit 0)
.DB $00						; Unused header bytes
.DB $00
.DB $00
.DB $00
.DB $00
.DB $00
.DB $00
.DB $00
.DB $00

.BASE $8000

 										
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;			     BANK 1 and 2 PLAYER NAMES AND ABILITIES 						 ;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;																				 ;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

_F{TEAM_PLAYER_NAMES_TEAM_PTR_TABLE

STARTING_ADDR_FOR_TEAM_PLAYER_NAMES_PTR_TABLE:
	.WORD BUFFALO_LIST, INDIANAPOLIS_LIST, MIAMI_LIST, NEW_ENGLAND_LIST, NEW_YORK_JETS_LIST
	.WORD CINCINNATI_LIST, CLEVELAND_LIST, HOUSTON_LIST, PITTSBURGH_LIST
	.WORD DENVER_LIST, KANSAS_CITY_LIST, LOS_ANGELES_RAIDERS_LIST, SAN_DIEGO_LIST, SEATTLE_LIST
	.WORD WASHINGTON_LIST, NEW_YORK_GIANTS_LIST, PHILADELPHIA_LIST, PHOENIX_LIST, DALLAS_LIST
	.WORD CHICAGO_LIST, DETROIT_LIST, GREEN_BAY_LIST, MINNESOTA_LIST, TAMPA_BAY_LIST
	.WORD SAN_FRANCISCO_LIST, LOS_ANGELES_RAMS_LIST, NEW_ORLEANS_LIST, ATLANTA_LIST
	
_F}_PLAYER_NAMES_TEAM_PTR_TABLE	

_F{_PLAYER_NAME_POINTERS

BUFFALO_LIST:
	.WORD BUFFALO_QB1
	.WORD BUFFALO_QB2
	.WORD BUFFALO_RB1
	.WORD BUFFALO_RB2
	.WORD BUFFALO_RB3
	.WORD BUFFALO_RB4
	.WORD BUFFALO_WR1
	.WORD BUFFALO_WR2
	.WORD BUFFALO_WR3
	.WORD BUFFALO_WR4
	.WORD BUFFALO_TE1
	.WORD BUFFALO_TE2
	.WORD BUFFALO_C
	.WORD BUFFALO_LG
	.WORD BUFFALO_RG
	.WORD BUFFALO_LT
	.WORD BUFFALO_RT
	.WORD BUFFALO_RE
	.WORD BUFFALO_NT
	.WORD BUFFALO_LE
	.WORD BUFFALO_ROLB
	.WORD BUFFALO_RILB
	.WORD BUFFALO_LILB
	.WORD BUFFALO_LOLB
	.WORD BUFFALO_RCB
	.WORD BUFFALO_LCB
	.WORD BUFFALO_FS
	.WORD BUFFALO_SS
	.WORD BUFFALO_K
	.WORD BUFFALO_P
	
INDIANAPOLIS_LIST:
	.WORD INDIANAPOLIS_QB1
	.WORD INDIANAPOLIS_QB2
	.WORD INDIANAPOLIS_RB1
	.WORD INDIANAPOLIS_RB2
	.WORD INDIANAPOLIS_RB3
	.WORD INDIANAPOLIS_RB4
	.WORD INDIANAPOLIS_WR1
	.WORD INDIANAPOLIS_WR2
	.WORD INDIANAPOLIS_WR3
	.WORD INDIANAPOLIS_WR4
	.WORD INDIANAPOLIS_TE1
	.WORD INDIANAPOLIS_TE2
	.WORD INDIANAPOLIS_C
	.WORD INDIANAPOLIS_LG
	.WORD INDIANAPOLIS_RG
	.WORD INDIANAPOLIS_LT
	.WORD INDIANAPOLIS_RT
	.WORD INDIANAPOLIS_RE
	.WORD INDIANAPOLIS_NT
	.WORD INDIANAPOLIS_LE
	.WORD INDIANAPOLIS_ROLB
	.WORD INDIANAPOLIS_RILB
	.WORD INDIANAPOLIS_LILB
	.WORD INDIANAPOLIS_LOLB
	.WORD INDIANAPOLIS_RCB
	.WORD INDIANAPOLIS_LCB
	.WORD INDIANAPOLIS_FS
	.WORD INDIANAPOLIS_SS
	.WORD INDIANAPOLIS_K
	.WORD INDIANAPOLIS_P
	
MIAMI_LIST:
	.WORD MIAMI_QB1
	.WORD MIAMI_QB2
	.WORD MIAMI_RB1
	.WORD MIAMI_RB2
	.WORD MIAMI_RB3
	.WORD MIAMI_RB4
	.WORD MIAMI_WR1
	.WORD MIAMI_WR2
	.WORD MIAMI_WR3
	.WORD MIAMI_WR4
	.WORD MIAMI_TE1
	.WORD MIAMI_TE2
	.WORD MIAMI_C
	.WORD MIAMI_LG
	.WORD MIAMI_RG
	.WORD MIAMI_LT
	.WORD MIAMI_RT
	.WORD MIAMI_RE
	.WORD MIAMI_NT
	.WORD MIAMI_LE
	.WORD MIAMI_ROLB
	.WORD MIAMI_RILB
	.WORD MIAMI_LILB
	.WORD MIAMI_LOLB
	.WORD MIAMI_RCB
	.WORD MIAMI_LCB
	.WORD MIAMI_FS
	.WORD MIAMI_SS
	.WORD MIAMI_K
	.WORD MIAMI_P
	
NEW_ENGLAND_LIST:
	.WORD NEW_ENGLAND_QB1
	.WORD NEW_ENGLAND_QB2
	.WORD NEW_ENGLAND_RB1
	.WORD NEW_ENGLAND_RB2
	.WORD NEW_ENGLAND_RB3
	.WORD NEW_ENGLAND_RB4
	.WORD NEW_ENGLAND_WR1
	.WORD NEW_ENGLAND_WR2
	.WORD NEW_ENGLAND_WR3
	.WORD NEW_ENGLAND_WR4
	.WORD NEW_ENGLAND_TE1
	.WORD NEW_ENGLAND_TE2
	.WORD NEW_ENGLAND_C
	.WORD NEW_ENGLAND_LG
	.WORD NEW_ENGLAND_RG
	.WORD NEW_ENGLAND_LT
	.WORD NEW_ENGLAND_RT
	.WORD NEW_ENGLAND_RE
	.WORD NEW_ENGLAND_NT
	.WORD NEW_ENGLAND_LE
	.WORD NEW_ENGLAND_ROLB
	.WORD NEW_ENGLAND_RILB
	.WORD NEW_ENGLAND_LILB
	.WORD NEW_ENGLAND_LOLB
	.WORD NEW_ENGLAND_RCB
	.WORD NEW_ENGLAND_LCB
	.WORD NEW_ENGLAND_FS
	.WORD NEW_ENGLAND_SS
	.WORD NEW_ENGLAND_K
	.WORD NEW_ENGLAND_P
	
NEW_YORK_JETS_LIST:
	.WORD NEW_YORK_JETS_QB1
	.WORD NEW_YORK_JETS_QB2
	.WORD NEW_YORK_JETS_RB1
	.WORD NEW_YORK_JETS_RB2
	.WORD NEW_YORK_JETS_RB3
	.WORD NEW_YORK_JETS_RB4
	.WORD NEW_YORK_JETS_WR1
	.WORD NEW_YORK_JETS_WR2
	.WORD NEW_YORK_JETS_WR3
	.WORD NEW_YORK_JETS_WR4
	.WORD NEW_YORK_JETS_TE1
	.WORD NEW_YORK_JETS_TE2
	.WORD NEW_YORK_JETS_C
	.WORD NEW_YORK_JETS_LG
	.WORD NEW_YORK_JETS_RG
	.WORD NEW_YORK_JETS_LT
	.WORD NEW_YORK_JETS_RT
	.WORD NEW_YORK_JETS_RE
	.WORD NEW_YORK_JETS_NT
	.WORD NEW_YORK_JETS_LE
	.WORD NEW_YORK_JETS_ROLB
	.WORD NEW_YORK_JETS_RILB
	.WORD NEW_YORK_JETS_LILB
	.WORD NEW_YORK_JETS_LOLB
	.WORD NEW_YORK_JETS_RCB
	.WORD NEW_YORK_JETS_LCB
	.WORD NEW_YORK_JETS_FS
	.WORD NEW_YORK_JETS_SS
	.WORD NEW_YORK_JETS_K
	.WORD NEW_YORK_JETS_P
	
CINCINNATI_LIST:
	.WORD CINCINNATI_QB1
	.WORD CINCINNATI_QB2
	.WORD CINCINNATI_RB1
	.WORD CINCINNATI_RB2
	.WORD CINCINNATI_RB3
	.WORD CINCINNATI_RB4
	.WORD CINCINNATI_WR1
	.WORD CINCINNATI_WR2
	.WORD CINCINNATI_WR3
	.WORD CINCINNATI_WR4
	.WORD CINCINNATI_TE1
	.WORD CINCINNATI_TE2
	.WORD CINCINNATI_C
	.WORD CINCINNATI_LG
	.WORD CINCINNATI_RG
	.WORD CINCINNATI_LT
	.WORD CINCINNATI_RT
	.WORD CINCINNATI_RE
	.WORD CINCINNATI_NT
	.WORD CINCINNATI_LE
	.WORD CINCINNATI_ROLB
	.WORD CINCINNATI_RILB
	.WORD CINCINNATI_LILB
	.WORD CINCINNATI_LOLB
	.WORD CINCINNATI_RCB
	.WORD CINCINNATI_LCB
	.WORD CINCINNATI_FS
	.WORD CINCINNATI_SS
	.WORD CINCINNATI_K
	.WORD CINCINNATI_P
	
CLEVELAND_LIST:
	.WORD CLEVELAND_QB1
	.WORD CLEVELAND_QB2
	.WORD CLEVELAND_RB1
	.WORD CLEVELAND_RB2
	.WORD CLEVELAND_RB3
	.WORD CLEVELAND_RB4
	.WORD CLEVELAND_WR1
	.WORD CLEVELAND_WR2
	.WORD CLEVELAND_WR3
	.WORD CLEVELAND_WR4
	.WORD CLEVELAND_TE1
	.WORD CLEVELAND_TE2
	.WORD CLEVELAND_C
	.WORD CLEVELAND_LG
	.WORD CLEVELAND_RG
	.WORD CLEVELAND_LT
	.WORD CLEVELAND_RT
	.WORD CLEVELAND_RE
	.WORD CLEVELAND_NT
	.WORD CLEVELAND_LE
	.WORD CLEVELAND_ROLB
	.WORD CLEVELAND_RILB
	.WORD CLEVELAND_LILB
	.WORD CLEVELAND_LOLB
	.WORD CLEVELAND_RCB
	.WORD CLEVELAND_LCB
	.WORD CLEVELAND_FS
	.WORD CLEVELAND_SS
	.WORD CLEVELAND_K
	.WORD CLEVELAND_P
	
HOUSTON_LIST:
	.WORD HOUSTON_QB1
	.WORD HOUSTON_QB2
	.WORD HOUSTON_RB1
	.WORD HOUSTON_RB2
	.WORD HOUSTON_RB3
	.WORD HOUSTON_RB4
	.WORD HOUSTON_WR1
	.WORD HOUSTON_WR2
	.WORD HOUSTON_WR3
	.WORD HOUSTON_WR4
	.WORD HOUSTON_TE1
	.WORD HOUSTON_TE2
	.WORD HOUSTON_C
	.WORD HOUSTON_LG
	.WORD HOUSTON_RG
	.WORD HOUSTON_LT
	.WORD HOUSTON_RT
	.WORD HOUSTON_RE
	.WORD HOUSTON_NT
	.WORD HOUSTON_LE
	.WORD HOUSTON_ROLB
	.WORD HOUSTON_RILB
	.WORD HOUSTON_LILB
	.WORD HOUSTON_LOLB
	.WORD HOUSTON_RCB
	.WORD HOUSTON_LCB
	.WORD HOUSTON_FS
	.WORD HOUSTON_SS
	.WORD HOUSTON_K
	.WORD HOUSTON_P
	
PITTSBURGH_LIST:
	.WORD PITTSBURGH_QB1
	.WORD PITTSBURGH_QB2
	.WORD PITTSBURGH_RB1
	.WORD PITTSBURGH_RB2
	.WORD PITTSBURGH_RB3
	.WORD PITTSBURGH_RB4
	.WORD PITTSBURGH_WR1
	.WORD PITTSBURGH_WR2
	.WORD PITTSBURGH_WR3
	.WORD PITTSBURGH_WR4
	.WORD PITTSBURGH_TE1
	.WORD PITTSBURGH_TE2
	.WORD PITTSBURGH_C
	.WORD PITTSBURGH_LG
	.WORD PITTSBURGH_RG
	.WORD PITTSBURGH_LT
	.WORD PITTSBURGH_RT
	.WORD PITTSBURGH_RE
	.WORD PITTSBURGH_NT
	.WORD PITTSBURGH_LE
	.WORD PITTSBURGH_ROLB
	.WORD PITTSBURGH_RILB
	.WORD PITTSBURGH_LILB
	.WORD PITTSBURGH_LOLB
	.WORD PITTSBURGH_RCB
	.WORD PITTSBURGH_LCB
	.WORD PITTSBURGH_FS
	.WORD PITTSBURGH_SS
	.WORD PITTSBURGH_K
	.WORD PITTSBURGH_P
	
DENVER_LIST:
	.WORD DENVER_QB1
	.WORD DENVER_QB2
	.WORD DENVER_RB1
	.WORD DENVER_RB2
	.WORD DENVER_RB3
	.WORD DENVER_RB4
	.WORD DENVER_WR1
	.WORD DENVER_WR2
	.WORD DENVER_WR3
	.WORD DENVER_WR4
	.WORD DENVER_TE1
	.WORD DENVER_TE2
	.WORD DENVER_C
	.WORD DENVER_LG
	.WORD DENVER_RG
	.WORD DENVER_LT
	.WORD DENVER_RT
	.WORD DENVER_RE
	.WORD DENVER_NT
	.WORD DENVER_LE
	.WORD DENVER_ROLB
	.WORD DENVER_RILB
	.WORD DENVER_LILB
	.WORD DENVER_LOLB
	.WORD DENVER_RCB
	.WORD DENVER_LCB
	.WORD DENVER_FS
	.WORD DENVER_SS
	.WORD DENVER_K
	.WORD DENVER_P
	
KANSAS_CITY_LIST:
	.WORD KANSAS_CITY_QB1
	.WORD KANSAS_CITY_QB2
	.WORD KANSAS_CITY_RB1
	.WORD KANSAS_CITY_RB2
	.WORD KANSAS_CITY_RB3
	.WORD KANSAS_CITY_RB4
	.WORD KANSAS_CITY_WR1
	.WORD KANSAS_CITY_WR2
	.WORD KANSAS_CITY_WR3
	.WORD KANSAS_CITY_WR4
	.WORD KANSAS_CITY_TE1
	.WORD KANSAS_CITY_TE2
	.WORD KANSAS_CITY_C
	.WORD KANSAS_CITY_LG
	.WORD KANSAS_CITY_RG
	.WORD KANSAS_CITY_LT
	.WORD KANSAS_CITY_RT
	.WORD KANSAS_CITY_RE
	.WORD KANSAS_CITY_NT
	.WORD KANSAS_CITY_LE
	.WORD KANSAS_CITY_ROLB
	.WORD KANSAS_CITY_RILB
	.WORD KANSAS_CITY_LILB
	.WORD KANSAS_CITY_LOLB
	.WORD KANSAS_CITY_RCB
	.WORD KANSAS_CITY_LCB
	.WORD KANSAS_CITY_FS
	.WORD KANSAS_CITY_SS
	.WORD KANSAS_CITY_K
	.WORD KANSAS_CITY_P
	
LOS_ANGELES_RAIDERS_LIST:
	.WORD LOS_ANGELES_RAIDERS_QB1
	.WORD LOS_ANGELES_RAIDERS_QB2
	.WORD LOS_ANGELES_RAIDERS_RB1
	.WORD LOS_ANGELES_RAIDERS_RB2
	.WORD LOS_ANGELES_RAIDERS_RB3
	.WORD LOS_ANGELES_RAIDERS_RB4
	.WORD LOS_ANGELES_RAIDERS_WR1
	.WORD LOS_ANGELES_RAIDERS_WR2
	.WORD LOS_ANGELES_RAIDERS_WR3
	.WORD LOS_ANGELES_RAIDERS_WR4
	.WORD LOS_ANGELES_RAIDERS_TE1
	.WORD LOS_ANGELES_RAIDERS_TE2
	.WORD LOS_ANGELES_RAIDERS_C
	.WORD LOS_ANGELES_RAIDERS_LG
	.WORD LOS_ANGELES_RAIDERS_RG
	.WORD LOS_ANGELES_RAIDERS_LT
	.WORD LOS_ANGELES_RAIDERS_RT
	.WORD LOS_ANGELES_RAIDERS_RE
	.WORD LOS_ANGELES_RAIDERS_NT
	.WORD LOS_ANGELES_RAIDERS_LE
	.WORD LOS_ANGELES_RAIDERS_ROLB
	.WORD LOS_ANGELES_RAIDERS_RILB
	.WORD LOS_ANGELES_RAIDERS_LILB
	.WORD LOS_ANGELES_RAIDERS_LOLB
	.WORD LOS_ANGELES_RAIDERS_RCB
	.WORD LOS_ANGELES_RAIDERS_LCB
	.WORD LOS_ANGELES_RAIDERS_FS
	.WORD LOS_ANGELES_RAIDERS_SS
	.WORD LOS_ANGELES_RAIDERS_K
	.WORD LOS_ANGELES_RAIDERS_P
	
SAN_DIEGO_LIST:
	.WORD SAN_DIEGO_QB1
	.WORD SAN_DIEGO_QB2
	.WORD SAN_DIEGO_RB1
	.WORD SAN_DIEGO_RB2
	.WORD SAN_DIEGO_RB3
	.WORD SAN_DIEGO_RB4
	.WORD SAN_DIEGO_WR1
	.WORD SAN_DIEGO_WR2
	.WORD SAN_DIEGO_WR3
	.WORD SAN_DIEGO_WR4
	.WORD SAN_DIEGO_TE1
	.WORD SAN_DIEGO_TE2
	.WORD SAN_DIEGO_C
	.WORD SAN_DIEGO_LG
	.WORD SAN_DIEGO_RG
	.WORD SAN_DIEGO_LT
	.WORD SAN_DIEGO_RT
	.WORD SAN_DIEGO_RE
	.WORD SAN_DIEGO_NT
	.WORD SAN_DIEGO_LE
	.WORD SAN_DIEGO_ROLB
	.WORD SAN_DIEGO_RILB
	.WORD SAN_DIEGO_LILB
	.WORD SAN_DIEGO_LOLB
	.WORD SAN_DIEGO_RCB
	.WORD SAN_DIEGO_LCB
	.WORD SAN_DIEGO_FS
	.WORD SAN_DIEGO_SS
	.WORD SAN_DIEGO_K
	.WORD SAN_DIEGO_P
	
SEATTLE_LIST:
	.WORD SEATTLE_QB1
	.WORD SEATTLE_QB2
	.WORD SEATTLE_RB1
	.WORD SEATTLE_RB2
	.WORD SEATTLE_RB3
	.WORD SEATTLE_RB4
	.WORD SEATTLE_WR1
	.WORD SEATTLE_WR2
	.WORD SEATTLE_WR3
	.WORD SEATTLE_WR4
	.WORD SEATTLE_TE1
	.WORD SEATTLE_TE2
	.WORD SEATTLE_C
	.WORD SEATTLE_LG
	.WORD SEATTLE_RG
	.WORD SEATTLE_LT
	.WORD SEATTLE_RT
	.WORD SEATTLE_RE
	.WORD SEATTLE_NT
	.WORD SEATTLE_LE
	.WORD SEATTLE_ROLB
	.WORD SEATTLE_RILB
	.WORD SEATTLE_LILB
	.WORD SEATTLE_LOLB
	.WORD SEATTLE_RCB
	.WORD SEATTLE_LCB
	.WORD SEATTLE_FS
	.WORD SEATTLE_SS
	.WORD SEATTLE_K
	.WORD SEATTLE_P
	
WASHINGTON_LIST:
	.WORD WASHINGTON_QB1
	.WORD WASHINGTON_QB2
	.WORD WASHINGTON_RB1
	.WORD WASHINGTON_RB2
	.WORD WASHINGTON_RB3
	.WORD WASHINGTON_RB4
	.WORD WASHINGTON_WR1
	.WORD WASHINGTON_WR2
	.WORD WASHINGTON_WR3
	.WORD WASHINGTON_WR4
	.WORD WASHINGTON_TE1
	.WORD WASHINGTON_TE2
	.WORD WASHINGTON_C
	.WORD WASHINGTON_LG
	.WORD WASHINGTON_RG
	.WORD WASHINGTON_LT
	.WORD WASHINGTON_RT
	.WORD WASHINGTON_RE
	.WORD WASHINGTON_NT
	.WORD WASHINGTON_LE
	.WORD WASHINGTON_ROLB
	.WORD WASHINGTON_RILB
	.WORD WASHINGTON_LILB
	.WORD WASHINGTON_LOLB
	.WORD WASHINGTON_RCB
	.WORD WASHINGTON_LCB
	.WORD WASHINGTON_FS
	.WORD WASHINGTON_SS
	.WORD WASHINGTON_K
	.WORD WASHINGTON_P
	
NEW_YORK_GIANTS_LIST:
	.WORD NEW_YORK_GIANTS_QB1
	.WORD NEW_YORK_GIANTS_QB2
	.WORD NEW_YORK_GIANTS_RB1
	.WORD NEW_YORK_GIANTS_RB2
	.WORD NEW_YORK_GIANTS_RB3
	.WORD NEW_YORK_GIANTS_RB4
	.WORD NEW_YORK_GIANTS_WR1
	.WORD NEW_YORK_GIANTS_WR2
	.WORD NEW_YORK_GIANTS_WR3
	.WORD NEW_YORK_GIANTS_WR4
	.WORD NEW_YORK_GIANTS_TE1
	.WORD NEW_YORK_GIANTS_TE2
	.WORD NEW_YORK_GIANTS_C
	.WORD NEW_YORK_GIANTS_LG
	.WORD NEW_YORK_GIANTS_RG
	.WORD NEW_YORK_GIANTS_LT
	.WORD NEW_YORK_GIANTS_RT
	.WORD NEW_YORK_GIANTS_RE
	.WORD NEW_YORK_GIANTS_NT
	.WORD NEW_YORK_GIANTS_LE
	.WORD NEW_YORK_GIANTS_ROLB
	.WORD NEW_YORK_GIANTS_RILB
	.WORD NEW_YORK_GIANTS_LILB
	.WORD NEW_YORK_GIANTS_LOLB
	.WORD NEW_YORK_GIANTS_RCB
	.WORD NEW_YORK_GIANTS_LCB
	.WORD NEW_YORK_GIANTS_FS
	.WORD NEW_YORK_GIANTS_SS
	.WORD NEW_YORK_GIANTS_K
	.WORD NEW_YORK_GIANTS_P
	
PHILADELPHIA_LIST:
	.WORD PHILADELPHIA_QB1
	.WORD PHILADELPHIA_QB2
	.WORD PHILADELPHIA_RB1
	.WORD PHILADELPHIA_RB2
	.WORD PHILADELPHIA_RB3
	.WORD PHILADELPHIA_RB4
	.WORD PHILADELPHIA_WR1
	.WORD PHILADELPHIA_WR2
	.WORD PHILADELPHIA_WR3
	.WORD PHILADELPHIA_WR4
	.WORD PHILADELPHIA_TE1
	.WORD PHILADELPHIA_TE2
	.WORD PHILADELPHIA_C
	.WORD PHILADELPHIA_LG
	.WORD PHILADELPHIA_RG
	.WORD PHILADELPHIA_LT
	.WORD PHILADELPHIA_RT
	.WORD PHILADELPHIA_RE
	.WORD PHILADELPHIA_NT
	.WORD PHILADELPHIA_LE
	.WORD PHILADELPHIA_ROLB
	.WORD PHILADELPHIA_RILB
	.WORD PHILADELPHIA_LILB
	.WORD PHILADELPHIA_LOLB
	.WORD PHILADELPHIA_RCB
	.WORD PHILADELPHIA_LCB
	.WORD PHILADELPHIA_FS
	.WORD PHILADELPHIA_SS
	.WORD PHILADELPHIA_K
	.WORD PHILADELPHIA_P
	
PHOENIX_LIST:
	.WORD PHOENIX_QB1
	.WORD PHOENIX_QB2
	.WORD PHOENIX_RB1
	.WORD PHOENIX_RB2
	.WORD PHOENIX_RB3
	.WORD PHOENIX_RB4
	.WORD PHOENIX_WR1
	.WORD PHOENIX_WR2
	.WORD PHOENIX_WR3
	.WORD PHOENIX_WR4
	.WORD PHOENIX_TE1
	.WORD PHOENIX_TE2
	.WORD PHOENIX_C
	.WORD PHOENIX_LG
	.WORD PHOENIX_RG
	.WORD PHOENIX_LT
	.WORD PHOENIX_RT
	.WORD PHOENIX_RE
	.WORD PHOENIX_NT
	.WORD PHOENIX_LE
	.WORD PHOENIX_ROLB
	.WORD PHOENIX_RILB
	.WORD PHOENIX_LILB
	.WORD PHOENIX_LOLB
	.WORD PHOENIX_RCB
	.WORD PHOENIX_LCB
	.WORD PHOENIX_FS
	.WORD PHOENIX_SS
	.WORD PHOENIX_K
	.WORD PHOENIX_P
	
DALLAS_LIST:
	.WORD DALLAS_QB1
	.WORD DALLAS_QB2
	.WORD DALLAS_RB1
	.WORD DALLAS_RB2
	.WORD DALLAS_RB3
	.WORD DALLAS_RB4
	.WORD DALLAS_WR1
	.WORD DALLAS_WR2
	.WORD DALLAS_WR3
	.WORD DALLAS_WR4
	.WORD DALLAS_TE1
	.WORD DALLAS_TE2
	.WORD DALLAS_C
	.WORD DALLAS_LG
	.WORD DALLAS_RG
	.WORD DALLAS_LT
	.WORD DALLAS_RT
	.WORD DALLAS_RE
	.WORD DALLAS_NT
	.WORD DALLAS_LE
	.WORD DALLAS_ROLB
	.WORD DALLAS_RILB
	.WORD DALLAS_LILB
	.WORD DALLAS_LOLB
	.WORD DALLAS_RCB
	.WORD DALLAS_LCB
	.WORD DALLAS_FS
	.WORD DALLAS_SS
	.WORD DALLAS_K
	.WORD DALLAS_P
	
CHICAGO_LIST:
	.WORD CHICAGO_QB1
	.WORD CHICAGO_QB2
	.WORD CHICAGO_RB1
	.WORD CHICAGO_RB2
	.WORD CHICAGO_RB3
	.WORD CHICAGO_RB4
	.WORD CHICAGO_WR1
	.WORD CHICAGO_WR2
	.WORD CHICAGO_WR3
	.WORD CHICAGO_WR4
	.WORD CHICAGO_TE1
	.WORD CHICAGO_TE2
	.WORD CHICAGO_C
	.WORD CHICAGO_LG
	.WORD CHICAGO_RG
	.WORD CHICAGO_LT
	.WORD CHICAGO_RT
	.WORD CHICAGO_RE
	.WORD CHICAGO_NT
	.WORD CHICAGO_LE
	.WORD CHICAGO_ROLB
	.WORD CHICAGO_RILB
	.WORD CHICAGO_LILB
	.WORD CHICAGO_LOLB
	.WORD CHICAGO_RCB
	.WORD CHICAGO_LCB
	.WORD CHICAGO_FS
	.WORD CHICAGO_SS
	.WORD CHICAGO_K
	.WORD CHICAGO_P
	
DETROIT_LIST:
	.WORD DETROIT_QB1
	.WORD DETROIT_QB2
	.WORD DETROIT_RB1
	.WORD DETROIT_RB2
	.WORD DETROIT_RB3
	.WORD DETROIT_RB4
	.WORD DETROIT_WR1
	.WORD DETROIT_WR2
	.WORD DETROIT_WR3
	.WORD DETROIT_WR4
	.WORD DETROIT_TE1
	.WORD DETROIT_TE2
	.WORD DETROIT_C
	.WORD DETROIT_LG
	.WORD DETROIT_RG
	.WORD DETROIT_LT
	.WORD DETROIT_RT
	.WORD DETROIT_RE
	.WORD DETROIT_NT
	.WORD DETROIT_LE
	.WORD DETROIT_ROLB
	.WORD DETROIT_RILB
	.WORD DETROIT_LILB
	.WORD DETROIT_LOLB
	.WORD DETROIT_RCB
	.WORD DETROIT_LCB
	.WORD DETROIT_FS
	.WORD DETROIT_SS
	.WORD DETROIT_K
	.WORD DETROIT_P
	
GREEN_BAY_LIST:
	.WORD GREEN_BAY_QB1
	.WORD GREEN_BAY_QB2
	.WORD GREEN_BAY_RB1
	.WORD GREEN_BAY_RB2
	.WORD GREEN_BAY_RB3
	.WORD GREEN_BAY_RB4
	.WORD GREEN_BAY_WR1
	.WORD GREEN_BAY_WR2
	.WORD GREEN_BAY_WR3
	.WORD GREEN_BAY_WR4
	.WORD GREEN_BAY_TE1
	.WORD GREEN_BAY_TE2
	.WORD GREEN_BAY_C
	.WORD GREEN_BAY_LG
	.WORD GREEN_BAY_RG
	.WORD GREEN_BAY_LT
	.WORD GREEN_BAY_RT
	.WORD GREEN_BAY_RE
	.WORD GREEN_BAY_NT
	.WORD GREEN_BAY_LE
	.WORD GREEN_BAY_ROLB
	.WORD GREEN_BAY_RILB
	.WORD GREEN_BAY_LILB
	.WORD GREEN_BAY_LOLB
	.WORD GREEN_BAY_RCB
	.WORD GREEN_BAY_LCB
	.WORD GREEN_BAY_FS
	.WORD GREEN_BAY_SS
	.WORD GREEN_BAY_K
	.WORD GREEN_BAY_P
	
MINNESOTA_LIST:
	.WORD MINNESOTA_QB1
	.WORD MINNESOTA_QB2
	.WORD MINNESOTA_RB1
	.WORD MINNESOTA_RB2
	.WORD MINNESOTA_RB3
	.WORD MINNESOTA_RB4
	.WORD MINNESOTA_WR1
	.WORD MINNESOTA_WR2
	.WORD MINNESOTA_WR3
	.WORD MINNESOTA_WR4
	.WORD MINNESOTA_TE1
	.WORD MINNESOTA_TE2
	.WORD MINNESOTA_C
	.WORD MINNESOTA_LG
	.WORD MINNESOTA_RG
	.WORD MINNESOTA_LT
	.WORD MINNESOTA_RT
	.WORD MINNESOTA_RE
	.WORD MINNESOTA_NT
	.WORD MINNESOTA_LE
	.WORD MINNESOTA_ROLB
	.WORD MINNESOTA_RILB
	.WORD MINNESOTA_LILB
	.WORD MINNESOTA_LOLB
	.WORD MINNESOTA_RCB
	.WORD MINNESOTA_LCB
	.WORD MINNESOTA_FS
	.WORD MINNESOTA_SS
	.WORD MINNESOTA_K
	.WORD MINNESOTA_P
	
TAMPA_BAY_LIST:
	.WORD TAMPA_BAY_QB1
	.WORD TAMPA_BAY_QB2
	.WORD TAMPA_BAY_RB1
	.WORD TAMPA_BAY_RB2
	.WORD TAMPA_BAY_RB3
	.WORD TAMPA_BAY_RB4
	.WORD TAMPA_BAY_WR1
	.WORD TAMPA_BAY_WR2
	.WORD TAMPA_BAY_WR3
	.WORD TAMPA_BAY_WR4
	.WORD TAMPA_BAY_TE1
	.WORD TAMPA_BAY_TE2
	.WORD TAMPA_BAY_C
	.WORD TAMPA_BAY_LG
	.WORD TAMPA_BAY_RG
	.WORD TAMPA_BAY_LT
	.WORD TAMPA_BAY_RT
	.WORD TAMPA_BAY_RE
	.WORD TAMPA_BAY_NT
	.WORD TAMPA_BAY_LE
	.WORD TAMPA_BAY_ROLB
	.WORD TAMPA_BAY_RILB
	.WORD TAMPA_BAY_LILB
	.WORD TAMPA_BAY_LOLB
	.WORD TAMPA_BAY_RCB
	.WORD TAMPA_BAY_LCB
	.WORD TAMPA_BAY_FS
	.WORD TAMPA_BAY_SS
	.WORD TAMPA_BAY_K
	.WORD TAMPA_BAY_P
	
SAN_FRANCISCO_LIST:
	.WORD SAN_FRANCISCO_QB1
	.WORD SAN_FRANCISCO_QB2
	.WORD SAN_FRANCISCO_RB1
	.WORD SAN_FRANCISCO_RB2
	.WORD SAN_FRANCISCO_RB3
	.WORD SAN_FRANCISCO_RB4
	.WORD SAN_FRANCISCO_WR1
	.WORD SAN_FRANCISCO_WR2
	.WORD SAN_FRANCISCO_WR3
	.WORD SAN_FRANCISCO_WR4
	.WORD SAN_FRANCISCO_TE1
	.WORD SAN_FRANCISCO_TE2
	.WORD SAN_FRANCISCO_C
	.WORD SAN_FRANCISCO_LG
	.WORD SAN_FRANCISCO_RG
	.WORD SAN_FRANCISCO_LT
	.WORD SAN_FRANCISCO_RT
	.WORD SAN_FRANCISCO_RE
	.WORD SAN_FRANCISCO_NT
	.WORD SAN_FRANCISCO_LE
	.WORD SAN_FRANCISCO_ROLB
	.WORD SAN_FRANCISCO_RILB
	.WORD SAN_FRANCISCO_LILB
	.WORD SAN_FRANCISCO_LOLB
	.WORD SAN_FRANCISCO_RCB
	.WORD SAN_FRANCISCO_LCB
	.WORD SAN_FRANCISCO_FS
	.WORD SAN_FRANCISCO_SS
	.WORD SAN_FRANCISCO_K
	.WORD SAN_FRANCISCO_P
	
LOS_ANGELES_RAMS_LIST:
	.WORD LOS_ANGELES_RAMS_QB1
	.WORD LOS_ANGELES_RAMS_QB2
	.WORD LOS_ANGELES_RAMS_RB1
	.WORD LOS_ANGELES_RAMS_RB2
	.WORD LOS_ANGELES_RAMS_RB3
	.WORD LOS_ANGELES_RAMS_RB4
	.WORD LOS_ANGELES_RAMS_WR1
	.WORD LOS_ANGELES_RAMS_WR2
	.WORD LOS_ANGELES_RAMS_WR3
	.WORD LOS_ANGELES_RAMS_WR4
	.WORD LOS_ANGELES_RAMS_TE1
	.WORD LOS_ANGELES_RAMS_TE2
	.WORD LOS_ANGELES_RAMS_C
	.WORD LOS_ANGELES_RAMS_LG
	.WORD LOS_ANGELES_RAMS_RG
	.WORD LOS_ANGELES_RAMS_LT
	.WORD LOS_ANGELES_RAMS_RT
	.WORD LOS_ANGELES_RAMS_RE
	.WORD LOS_ANGELES_RAMS_NT
	.WORD LOS_ANGELES_RAMS_LE
	.WORD LOS_ANGELES_RAMS_ROLB
	.WORD LOS_ANGELES_RAMS_RILB
	.WORD LOS_ANGELES_RAMS_LILB
	.WORD LOS_ANGELES_RAMS_LOLB
	.WORD LOS_ANGELES_RAMS_RCB
	.WORD LOS_ANGELES_RAMS_LCB
	.WORD LOS_ANGELES_RAMS_FS
	.WORD LOS_ANGELES_RAMS_SS
	.WORD LOS_ANGELES_RAMS_K
	.WORD LOS_ANGELES_RAMS_P
	
NEW_ORLEANS_LIST:
	.WORD NEW_ORLEANS_QB1
	.WORD NEW_ORLEANS_QB2
	.WORD NEW_ORLEANS_RB1
	.WORD NEW_ORLEANS_RB2
	.WORD NEW_ORLEANS_RB3
	.WORD NEW_ORLEANS_RB4
	.WORD NEW_ORLEANS_WR1
	.WORD NEW_ORLEANS_WR2
	.WORD NEW_ORLEANS_WR3
	.WORD NEW_ORLEANS_WR4
	.WORD NEW_ORLEANS_TE1
	.WORD NEW_ORLEANS_TE2
	.WORD NEW_ORLEANS_C
	.WORD NEW_ORLEANS_LG
	.WORD NEW_ORLEANS_RG
	.WORD NEW_ORLEANS_LT
	.WORD NEW_ORLEANS_RT
	.WORD NEW_ORLEANS_RE
	.WORD NEW_ORLEANS_NT
	.WORD NEW_ORLEANS_LE
	.WORD NEW_ORLEANS_ROLB
	.WORD NEW_ORLEANS_RILB
	.WORD NEW_ORLEANS_LILB
	.WORD NEW_ORLEANS_LOLB
	.WORD NEW_ORLEANS_RCB
	.WORD NEW_ORLEANS_LCB
	.WORD NEW_ORLEANS_FS
	.WORD NEW_ORLEANS_SS
	.WORD NEW_ORLEANS_K
	.WORD NEW_ORLEANS_P
	
ATLANTA_LIST:
	.WORD ATLANTA_QB1
	.WORD ATLANTA_QB2
	.WORD ATLANTA_RB1
	.WORD ATLANTA_RB2
	.WORD ATLANTA_RB3
	.WORD ATLANTA_RB4
	.WORD ATLANTA_WR1
	.WORD ATLANTA_WR2
	.WORD ATLANTA_WR3
	.WORD ATLANTA_WR4
	.WORD ATLANTA_TE1
	.WORD ATLANTA_TE2
	.WORD ATLANTA_C
	.WORD ATLANTA_LG
	.WORD ATLANTA_RG
	.WORD ATLANTA_LT
	.WORD ATLANTA_RT
	.WORD ATLANTA_RE
	.WORD ATLANTA_NT
	.WORD ATLANTA_LE
	.WORD ATLANTA_ROLB
	.WORD ATLANTA_RILB
	.WORD ATLANTA_LILB
	.WORD ATLANTA_LOLB
	.WORD ATLANTA_RCB
	.WORD ATLANTA_LCB
	.WORD ATLANTA_FS
	.WORD ATLANTA_SS
	.WORD ATLANTA_K
	.WORD ATLANTA_P

	.WORD PLAYER_LIST_END

_F}_PLAYER_NAME_POINTERS	

_F{_PLAYER_NUMBERS_AND_NAMES

BUFFALO_QB1:	                  .DB $00, "qbBILLS"
BUFFALO_QB2:	                  .DB $14, "frankREICH"
BUFFALO_RB1:	                  .DB $34, "thurmanTHOMAS"
BUFFALO_RB2:	                  .DB $41, "jamieMUELLER"
BUFFALO_RB3:	                  .DB $23, "kennethDAVIS"
BUFFALO_RB4:	                  .DB $30, "donSMITH"
BUFFALO_WR1:	                  .DB $80, "jamesLOFTON"
BUFFALO_WR2:	                  .DB $83, "andreREED"
BUFFALO_WR3:	                  .DB $82, "donBEEBE"
BUFFALO_WR4:	                  .DB $85, "alEDWARDS"
BUFFALO_TE1:	                  .DB $84, "keithMCKELLER"
BUFFALO_TE2:	                  .DB $88, "peteMETZELAARS"
BUFFALO_C:	                      .DB $67, "kentHULL"
BUFFALO_LG:	                      .DB $51, "jimRITCHER"
BUFFALO_RG:	                      .DB $65, "johnDAVIS"
BUFFALO_LT:	                      .DB $69, "willWOLFORD"
BUFFALO_RT:	                      .DB $75, "howardBALLARD"
BUFFALO_RE:	                      .DB $78, "bruceSMITH"
BUFFALO_NT:	                      .DB $91, "jeffWRIGHT"
BUFFALO_LE:	                      .DB $96, "leonSEALS"
BUFFALO_ROLB:	                  .DB $56, "darrylTALLEY"
BUFFALO_RILB:	                  .DB $50, "rayBENTLEY"
BUFFALO_LILB:	                  .DB $58, "shaneCONLAN"
BUFFALO_LOLB:	                  .DB $97, "c.BENNETT"
BUFFALO_RCB:	                  .DB $37, "nateODOMES"
BUFFALO_LCB:	                  .DB $47, "kirbyJACKSON"
BUFFALO_FS:	                      .DB $38, "markKELSO"
BUFFALO_SS:	                      .DB $46, "leonardSMITH"
BUFFALO_K:	                      .DB $11, "scottNORWOOD"
BUFFALO_P:	                      .DB $10, "rickTUTEN"

INDIANAPOLIS_QB1:	              .DB $11, "jeffGEORGE"
INDIANAPOLIS_QB2:	              .DB $10, "jackTRUDEAU"
INDIANAPOLIS_RB1:	              .DB $45, "ivy joeHUNTER"
INDIANAPOLIS_RB2:	              .DB $20, "albertBENTLEY"
INDIANAPOLIS_RB3:	              .DB $23, "anthonyJOHNSON"
INDIANAPOLIS_RB4:	              .DB $32, "kenCLARK"
INDIANAPOLIS_WR1:	              .DB $80, "billBROOKS"
INDIANAPOLIS_WR2:	              .DB $84, "jessieHESTER"
INDIANAPOLIS_WR3:	              .DB $83, "clarenceVERDIN"
INDIANAPOLIS_WR4:	              .DB $88, "stanleyMORGAN"
INDIANAPOLIS_TE1:	              .DB $81, "patBEACH"
INDIANAPOLIS_TE2:	              .DB $89, "orsonMOBLEY"
INDIANAPOLIS_C:	                  .DB $53, "rayDONALDSON"
INDIANAPOLIS_LG:	              .DB $69, "randyDIXON"
INDIANAPOLIS_RG:	              .DB $62, "brianBALDINGER"
INDIANAPOLIS_LT:	              .DB $73, "zefrossMOSS"
INDIANAPOLIS_RT:	              .DB $71, "kevinCALL"
INDIANAPOLIS_RE:	              .DB $78, "jonHAND"
INDIANAPOLIS_NT:	              .DB $79, "harveyARMSTRONG"
INDIANAPOLIS_LE:	              .DB $76, "samCLANCY"
INDIANAPOLIS_ROLB:	              .DB $50, "duaneBICKETT"
INDIANAPOLIS_RILB:	              .DB $56, "freddYOUNG"
INDIANAPOLIS_LILB:	              .DB $54, "jeffHERROD"
INDIANAPOLIS_LOLB:	              .DB $51, "chipBANKS"
INDIANAPOLIS_RCB:	              .DB $38, "eugeneDANIEL"
INDIANAPOLIS_LCB:	              .DB $37, "chrisGOODE"
INDIANAPOLIS_FS:	              .DB $39, "mikePRIOR"
INDIANAPOLIS_SS:	              .DB $27, "keithTAYLOR"
INDIANAPOLIS_K:	                  .DB $04, "deanBIASUCCI"
INDIANAPOLIS_P:	                  .DB $03, "rohnSTARK"

MIAMI_QB1:	                      .DB $13, "danMARINO"
MIAMI_QB2:	                      .DB $19, "scottMITCHELL"
MIAMI_RB1:	                      .DB $33, "sammieSMITH"
MIAMI_RB2:	                      .DB $49, "tonyPAIGE"
MIAMI_RB3:	                      .DB $20, "marcLOGAN"
MIAMI_RB4:	                      .DB $23, "troySTRADFORD"
MIAMI_WR1:	                      .DB $83, "markCLAYTON"
MIAMI_WR2:	                      .DB $85, "markDUPER"
MIAMI_WR3:	                      .DB $86, "fredBANKS"
MIAMI_WR4:	                      .DB $89, "tonyMARTIN"
MIAMI_TE1:	                      .DB $80, "ferrellEDMUNDS"
MIAMI_TE2:	                      .DB $11, "jimJENSEN"
MIAMI_C:	                      .DB $63, "jeffUHLENHAKE"
MIAMI_LG:	                      .DB $69, "keithSIMS"
MIAMI_RG:	                      .DB $62, "harryGALBREATH"
MIAMI_LT:	                      .DB $78, "richmondWEBB"
MIAMI_RT:	                      .DB $74, "markDENNIS"
MIAMI_RE:	                      .DB $91, "jeffCROSS"
MIAMI_NT:	                      .DB $98, "shawnLEE"
MIAMI_LE:	                      .DB $77, "karlWILSON"
MIAMI_ROLB:	                      .DB $55, "hughGREEN"
MIAMI_RILB:	                      .DB $93, "cliffODOM"
MIAMI_LILB:	                      .DB $56, "johnOFFERDAHL"
MIAMI_LOLB:	                      .DB $92, "davidGRIGGS"
MIAMI_RCB:	                      .DB $37, "j.b.BROWN"
MIAMI_LCB:	                      .DB $22, "timMCKYER"
MIAMI_FS:	                      .DB $25, "louisOLIVER"
MIAMI_SS:	                      .DB $26, "jarvisWILLIAMS"
MIAMI_K:	                      .DB $10, "peteSTOYANOVICH"
MIAMI_P:	                      .DB $04, "reggieROBY"

NEW_ENGLAND_QB1:	              .DB $14, "steveGROGAN"
NEW_ENGLAND_QB2:	              .DB $15, "marcWILSON"
NEW_ENGLAND_RB1:	              .DB $39, "marvinALLEN"
NEW_ENGLAND_RB2:	              .DB $44, "johnSTEPHENS"
NEW_ENGLAND_RB3:	              .DB $33, "georgeADAMS"
NEW_ENGLAND_RB4:	              .DB $30, "mosiTATUPU"
NEW_ENGLAND_WR1:	              .DB $80, "irvingFRYAR"
NEW_ENGLAND_WR2:	              .DB $88, "hart leeDYKES"
NEW_ENGLAND_WR3:	              .DB $19, "gregMCMURTY"
NEW_ENGLAND_WR4:	              .DB $82, "sammyMARTIN"
NEW_ENGLAND_TE1:	              .DB $46, "marvCOOK"
NEW_ENGLAND_TE2:	              .DB $85, "ericSIEVERS"
NEW_ENGLAND_C:	                  .DB $66, "paulFAIRCHILD"
NEW_ENGLAND_LG:	                  .DB $74, "chrisGAMBOL"
NEW_ENGLAND_RG:	                  .DB $68, "damianJOHNSON"
NEW_ENGLAND_LT:	                  .DB $78, "bruceARMSTRONG"
NEW_ENGLAND_RT:	                  .DB $75, "dannyVILLA"
NEW_ENGLAND_RE:	                  .DB $60, "garinVERIS"
NEW_ENGLAND_NT:	                  .DB $72, "timGOAD"
NEW_ENGLAND_LE:	                  .DB $92, "rayAGNEW"
NEW_ENGLAND_ROLB:	              .DB $56, "andreTIPPETT"
NEW_ENGLAND_RILB:	              .DB $95, "edREYNOLDS"
NEW_ENGLAND_LILB:	              .DB $58, "richardHARVEY"
NEW_ENGLAND_LOLB:	              .DB $55, "chrisSINGLETON"
NEW_ENGLAND_RCB:	              .DB $37, "mauriceHURST"
NEW_ENGLAND_LCB:	              .DB $42, "ronnieLIPPETT"
NEW_ENGLAND_FS:	                  .DB $31, "fredMARION"
NEW_ENGLAND_SS:	                  .DB $23, "rodMCSWAIN"
NEW_ENGLAND_K:	                  .DB $04, "jasonSTAUROVSKY"
NEW_ENGLAND_P:	                  .DB $10, "brianHANSEN"

NEW_YORK_JETS_QB1:	              .DB $07, "kenO.BRIEN"
NEW_YORK_JETS_QB2:	              .DB $11, "tonyEASON"
NEW_YORK_JETS_RB1:	              .DB $32, "blairTHOMAS"
NEW_YORK_JETS_RB2:	              .DB $24, "freemanMCNEIL"
NEW_YORK_JETS_RB3:	              .DB $30, "bradBAXTER"
NEW_YORK_JETS_RB4:	              .DB $34, "johnnyHECTOR"
NEW_YORK_JETS_WR1:	              .DB $88, "alTOON"
NEW_YORK_JETS_WR2:	              .DB $85, "robMOORE"
NEW_YORK_JETS_WR3:	              .DB $81, "teranceMATHIS"
NEW_YORK_JETS_WR4:	              .DB $83, "jojoTOWNSELL"
NEW_YORK_JETS_TE1:	              .DB $80, "markBOYER"
NEW_YORK_JETS_TE2:	              .DB $86, "dougWELLSANDT"
NEW_YORK_JETS_C:	              .DB $53, "jimSWEENEY"
NEW_YORK_JETS_LG:	              .DB $79, "mikeHAIGHT"
NEW_YORK_JETS_RG:	              .DB $66, "daveCADIGAN"
NEW_YORK_JETS_LT:	              .DB $61, "jeffCRISWELL"
NEW_YORK_JETS_RT:	              .DB $72, "brettMILLER"
NEW_YORK_JETS_RE:	              .DB $56, "jeffLAGEMAN"
NEW_YORK_JETS_NT:	              .DB $94, "scottMERSEREAU"
NEW_YORK_JETS_LE:	              .DB $96, "ronSTALLWORTH"
NEW_YORK_JETS_ROLB:	              .DB $58, "joeKELLY"
NEW_YORK_JETS_RILB:	              .DB $90, "dennisBYRD"
NEW_YORK_JETS_LILB:	              .DB $59, "kyleCLIFTON"
NEW_YORK_JETS_LOLB:	              .DB $51, "joeMOTT"
NEW_YORK_JETS_RCB:	              .DB $40, "jamesHASTY"
NEW_YORK_JETS_LCB:	              .DB $45, "tonySTARGELL"
NEW_YORK_JETS_FS:	              .DB $22, "erikMCMILLAN"
NEW_YORK_JETS_SS:	              .DB $21, "brianWASHINGTON"
NEW_YORK_JETS_K:	              .DB $05, "patLEAHY"
NEW_YORK_JETS_P:	              .DB $06, "joePROKOP"

CINCINNATI_QB1:	                  .DB $07, "boomerESIASON"
CINCINNATI_QB2:	                  .DB $04, "erikWILHELM"
CINCINNATI_RB1:	                  .DB $21, "jamesBROOKS"
CINCINNATI_RB2:	                  .DB $30, "ickeyWOODS"
CINCINNATI_RB3:	                  .DB $28, "haroldGREEN"
CINCINNATI_RB4:	                  .DB $36, "s.JENNINGS"
CINCINNATI_WR1:	                  .DB $85, "timMCGEE"
CINCINNATI_WR2:	                  .DB $81, "eddieBROWN"
CINCINNATI_WR3:	                  .DB $83, "kendalSMITH"
CINCINNATI_WR4:	                  .DB $86, "mikeBARBER"
CINCINNATI_TE1:	                  .DB $82, "rodneyHOLMAN"
CINCINNATI_TE2:	                  .DB $84, "ericKATTUS"
CINCINNATI_C:	                  .DB $64, "bruceKOZERSKI"
CINCINNATI_LG:	                  .DB $75, "bruceREIMERS"
CINCINNATI_RG:	                  .DB $74, "brianBLADOS"
CINCINNATI_LT:	                  .DB $78, "anthonyMUNOZ"
CINCINNATI_RT:	                  .DB $63, "joeWALTER"
CINCINNATI_RE:	                  .DB $99, "jasonBUCK"
CINCINNATI_NT:	                  .DB $69, "timKRUMRIE"
CINCINNATI_LE:	                  .DB $72, "skipMCCLENDON"
CINCINNATI_ROLB:	              .DB $50, "jamesFRANCIS"
CINCINNATI_RILB:	              .DB $59, "kevinWALKER"
CINCINNATI_LILB:	              .DB $91, "carlZANDER"
CINCINNATI_LOLB:	              .DB $51, "leonWHITE"
CINCINNATI_RCB:	                  .DB $45, "carlCARTER"
CINCINNATI_LCB:	                  .DB $24, "lewisBILLUPS"
CINCINNATI_FS:	                  .DB $27, "barneyBUSSEY"
CINCINNATI_SS:	                  .DB $33, "davidFULCHER"
CINCINNATI_K:	                  .DB $03, "jimBREECH"
CINCINNATI_P:	                  .DB $11, "leeJOHNSON"

CLEVELAND_QB1:	                  .DB $00, "qbBROWNS"
CLEVELAND_QB2:	                  .DB $10, "mikePAGEL"
CLEVELAND_RB1:	                  .DB $34, "kevinMACK"
CLEVELAND_RB2:	                  .DB $21, "ericMETCALF"
CLEVELAND_RB3:	                  .DB $33, "leroyHOARD"
CLEVELAND_RB4:	                  .DB $29, "brentFULLWOOD"
CLEVELAND_WR1:	                  .DB $84, "w.SLAUGHTER"
CLEVELAND_WR2:	                  .DB $88, "reggieLANGHORNE"
CLEVELAND_WR3:	                  .DB $80, "vernonJOINES"
CLEVELAND_WR4:	                  .DB $86, "brianBRENNAN"
CLEVELAND_TE1:	                  .DB $82, "ozzieNEWSOME"
CLEVELAND_TE2:	                  .DB $87, "johnTALLEY"
CLEVELAND_C:	                  .DB $61, "mikeBAAB"
CLEVELAND_LG:	                  .DB $65, "ralphTAMM"
CLEVELAND_RG:	                  .DB $73, "greggRAKOCZY"
CLEVELAND_LT:	                  .DB $74, "paulFARREN"
CLEVELAND_RT:	                  .DB $66, "tonyJONES"
CLEVELAND_RE:	                  .DB $97, "robertBANKS"
CLEVELAND_NT:	                  .DB $75, "chrisPIKE"
CLEVELAND_LE:	                  .DB $60, "alBAKER"
CLEVELAND_ROLB:	                  .DB $24, "tonyBLAYLOCK"
CLEVELAND_RILB:	                  .DB $56, "davidGRAYSON"
CLEVELAND_LILB:	                  .DB $59, "mikeJOHNSON"
CLEVELAND_LOLB:	                  .DB $57, "clayMATTHEWS"
CLEVELAND_RCB:	                  .DB $26, "raymondCLAYBORN"
CLEVELAND_LCB:	                  .DB $31, "frankMINNIFIELD"
CLEVELAND_FS:	                  .DB $30, "thaneGASH"
CLEVELAND_SS:	                  .DB $22, "felixWRIGHT"
CLEVELAND_K:	                  .DB $02, "jerryKAURIC"
CLEVELAND_P:	                  .DB $15, "bryanWAGNER"

HOUSTON_QB1:	                  .DB $01, "warrenMOON"
HOUSTON_QB2:	                  .DB $14, "codyCARLSON"
HOUSTON_RB1:	                  .DB $44, "lorenzoWHITE"
HOUSTON_RB2:	                  .DB $81, "ernestGIVINS"
HOUSTON_RB3:	                  .DB $20, "allenPINKETT"
HOUSTON_RB4:	                  .DB $37, "victorJONES"
HOUSTON_WR1:	                  .DB $84, "haywoodJEFFRIES"
HOUSTON_WR2:	                  .DB $85, "drewHILL"
HOUSTON_WR3:	                  .DB $35, "dougLLOYD"
HOUSTON_WR4:	                  .DB $82, "tonyJONES"
HOUSTON_TE1:	                  .DB $80, "curtisDUNCAN"
HOUSTON_TE2:	                  .DB $89, "geraldMCNEIL"
HOUSTON_C:	                      .DB $52, "jayPENNISON"
HOUSTON_LG:	                      .DB $63, "mikeMUNCHAK"
HOUSTON_RG:	                      .DB $74, "bruceMATTHEWS"
HOUSTON_LT:	                      .DB $78, "donMAGGS"
HOUSTON_RT:	                      .DB $70, "deanSTEINKUHLER"
HOUSTON_RE:	                      .DB $96, "seanJONES"
HOUSTON_NT:	                      .DB $99, "dougSMITH"
HOUSTON_LE:	                      .DB $95, "williamFULLER"
HOUSTON_ROLB:	                  .DB $91, "johnnyMEADS"
HOUSTON_RILB:	                  .DB $54, "alSMITH"
HOUSTON_LILB:	                  .DB $59, "johnGRIMSLEY"
HOUSTON_LOLB:	                  .DB $79, "rayCHILDRESS"
HOUSTON_RCB:	                  .DB $23, "richardJOHNSON"
HOUSTON_LCB:	                  .DB $28, "crisDISHMAN"
HOUSTON_FS:	                      .DB $27, "terryKINARD"
HOUSTON_SS:	                      .DB $25, "bubbaMCDOWELL"
HOUSTON_K:	                      .DB $07, "tonyZENDEJAS"
HOUSTON_P:	                      .DB $09, "gregMONTGOMERY"

PITTSBURGH_QB1:	                  .DB $06, "bubbyBRISTER"
PITTSBURGH_QB2:	                  .DB $11, "rickSTROM"
PITTSBURGH_RB1:	                  .DB $33, "merrilHOGE"
PITTSBURGH_RB2:	                  .DB $42, "warrenWILLIAMS"
PITTSBURGH_RB3:	                  .DB $38, "timWORLEY"
PITTSBURGH_RB4:	                  .DB $21, "richardBELL"
PITTSBURGH_WR1:	                  .DB $83, "louisLIPPS"
PITTSBURGH_WR2:	                  .DB $82, "derekHILL"
PITTSBURGH_WR3:	                  .DB $88, "chrisCALLOWAY"
PITTSBURGH_WR4:	                  .DB $20, "dwightSTONE"
PITTSBURGH_TE1:	                  .DB $86, "ericGREEN"
PITTSBURGH_TE2:	                  .DB $84, "mikeMULARKEY"
PITTSBURGH_C:	                  .DB $63, "dermonttiDAWSON"
PITTSBURGH_LG:	                  .DB $60, "b.BLANKENSHIP"
PITTSBURGH_RG:	                  .DB $74, "terryLONG"
PITTSBURGH_LT:	                  .DB $65, "johnJACKSON"
PITTSBURGH_RT:	                  .DB $62, "tunchILKIN"
PITTSBURGH_RE:	                  .DB $66, "donaldEVANS"
PITTSBURGH_NT:	                  .DB $98, "geraldWILLIAMS"
PITTSBURGH_LE:	                  .DB $93, "keithWILLIS"
PITTSBURGH_ROLB:	              .DB $95, "gregLLOYD"
PITTSBURGH_RILB:	              .DB $50, "davidLITTLE"
PITTSBURGH_LILB:	              .DB $54, "hardyNICKERSON"
PITTSBURGH_LOLB:	              .DB $53, "bryanHINKLE"
PITTSBURGH_RCB:	                  .DB $26, "rodWOODSON"
PITTSBURGH_LCB:	                  .DB $49, "dwayneWOODRUFF"
PITTSBURGH_FS:	                  .DB $27, "thomasEVERETT"
PITTSBURGH_SS:	                  .DB $37, "carnellLAKE"
PITTSBURGH_K:	                  .DB $01, "garyANDERSON"
PITTSBURGH_P:	                  .DB $04, "danSTRYZINSKI"

DENVER_QB1:	                      .DB $07, "johnELWAY"
DENVER_QB2:	                      .DB $08, "garyKUBIAK"
DENVER_RB1:	                      .DB $26, "bobbyHUMPHREY"
DENVER_RB2:	                      .DB $30, "steveSEWELL"
DENVER_RB3:	                      .DB $23, "sammyWINDER"
DENVER_RB4:	                      .DB $32, "melvinBRATTON"
DENVER_WR1:	                      .DB $82, "vanceJOHNSON"
DENVER_WR2:	                      .DB $80, "markJACKSON"
DENVER_WR3:	                      .DB $84, "rickyNATTIEL"
DENVER_WR4:	                      .DB $83, "michaelYOUNG"
DENVER_TE1:	                      .DB $88, "clarenceKAY"
DENVER_TE2:	                      .DB $87, "paulGREEN"
DENVER_C:	                      .DB $72, "keithKARTZ"
DENVER_LG:	                      .DB $66, "jimJURIGA"
DENVER_RG:	                      .DB $67, "dougWIDELL"
DENVER_LT:	                      .DB $69, "darrellHAMILTON"
DENVER_RT:	                      .DB $76, "kenLANIER"
DENVER_RE:	                      .DB $90, "ronHOLMES"
DENVER_NT:	                      .DB $71, "gregKRAGEN"
DENVER_LE:	                      .DB $91, "warrenPOWERS"
DENVER_ROLB:	                  .DB $77, "karlMECKLENBURG"
DENVER_RILB:	                  .DB $56, "michaelBROOKS"
DENVER_LILB:	                  .DB $51, "marcMUNFORD"
DENVER_LOLB:	                  .DB $73, "simonFLETCHER"
DENVER_RCB:	                      .DB $24, "wymonHENDERSON"
DENVER_LCB:	                      .DB $34, "tyroneBRAXTON"
DENVER_FS:	                      .DB $27, "steveATWATER"
DENVER_SS:	                      .DB $49, "dennisSMITH"
DENVER_K:	                      .DB $09, "davidTREADWELL"
DENVER_P:	                      .DB $02, "mikeHORAN"

KANSAS_CITY_QB1:	              .DB $17, "steveDE BERG"
KANSAS_CITY_QB2:	              .DB $10, "mikeELKINS"
KANSAS_CITY_RB1:	              .DB $35, "christianOKOYE"
KANSAS_CITY_RB2:	              .DB $23, "barryWORD"
KANSAS_CITY_RB3:	              .DB $48, "toddMCNAIR"
KANSAS_CITY_RB4:	              .DB $43, "billJONES"
KANSAS_CITY_WR1:	              .DB $81, "robbTHOMAS"
KANSAS_CITY_WR2:	              .DB $83, "stephonePAIGE"
KANSAS_CITY_WR3:	              .DB $88, "j.j.BIRDEN"
KANSAS_CITY_WR4:	              .DB $86, "emileHARRY"
KANSAS_CITY_TE1:	              .DB $87, "alfredoROBERTS"
KANSAS_CITY_TE2:	              .DB $85, "jonathanHAYES"
KANSAS_CITY_C:	                  .DB $53, "mikeWEBSTER"
KANSAS_CITY_LG:	                  .DB $79, "davidSZOTT"
KANSAS_CITY_RG:	                  .DB $72, "davidLUTZ"
KANSAS_CITY_LT:	                  .DB $76, "johnALT"
KANSAS_CITY_RT:	                  .DB $77, "richBALDINGER"
KANSAS_CITY_RE:	                  .DB $63, "billMAAS"
KANSAS_CITY_NT:	                  .DB $97, "danSALEAUMUA"
KANSAS_CITY_LE:	                  .DB $90, "neilSMITH"
KANSAS_CITY_ROLB:	              .DB $58, "derrickTHOMAS"
KANSAS_CITY_RILB:	              .DB $56, "dinoHACKETT"
KANSAS_CITY_LILB:	              .DB $59, "percySNOW"
KANSAS_CITY_LOLB:	              .DB $57, "chrisMARTIN"
KANSAS_CITY_RCB:	              .DB $31, "kevinROSS"
KANSAS_CITY_LCB:	              .DB $29, "albertLEWIS"
KANSAS_CITY_FS:	                  .DB $20, "deronCHERRY"
KANSAS_CITY_SS:	                  .DB $27, "kevinPORTER"
KANSAS_CITY_K:	                  .DB $08, "nickLOWERY"
KANSAS_CITY_P:	                  .DB $04, "bryanBARKER"

LOS_ANGELES_RAIDERS_QB1:	      .DB $13, "jaySCHROEDER"
LOS_ANGELES_RAIDERS_QB2:	      .DB $07, "steveBEUERLEIN"
LOS_ANGELES_RAIDERS_RB1:	      .DB $34, "boJACKSON"
LOS_ANGELES_RAIDERS_RB2:	      .DB $32, "marcusALLEN"
LOS_ANGELES_RAIDERS_RB3:	      .DB $35, "steveSMITH"
LOS_ANGELES_RAIDERS_RB4:	      .DB $28, "gregBELL"
LOS_ANGELES_RAIDERS_WR1:	      .DB $86, "mervynFERNANDEZ"
LOS_ANGELES_RAIDERS_WR2:	      .DB $83, "willieGAULT"
LOS_ANGELES_RAIDERS_WR3:	      .DB $81, "timBROWN"
LOS_ANGELES_RAIDERS_WR4:	      .DB $85, "samGRADDY"
LOS_ANGELES_RAIDERS_TE1:	      .DB $88, "ethanHORTON"
LOS_ANGELES_RAIDERS_TE2:	      .DB $84, "mikeDYAL"
LOS_ANGELES_RAIDERS_C:	          .DB $72, "donMOSEBAR"
LOS_ANGELES_RAIDERS_LG:	          .DB $76, "steveWISNIEWSKI"
LOS_ANGELES_RAIDERS_RG:	          .DB $65, "maxMONTOYA"
LOS_ANGELES_RAIDERS_LT:	          .DB $68, "bruceWILKERSON"
LOS_ANGELES_RAIDERS_RT:	          .DB $60, "roryGRAVES"
LOS_ANGELES_RAIDERS_RE:	          .DB $93, "gregTOWNSEND"
LOS_ANGELES_RAIDERS_NT:	          .DB $79, "bobGOLIC"
LOS_ANGELES_RAIDERS_LE:	          .DB $75, "howieLONG"
LOS_ANGELES_RAIDERS_ROLB:	      .DB $51, "aaronWALLACE"
LOS_ANGELES_RAIDERS_RILB:	      .DB $70, "scottDAVIS"
LOS_ANGELES_RAIDERS_LILB:	      .DB $50, "rikiELLISON"
LOS_ANGELES_RAIDERS_LOLB:	      .DB $57, "jerryROBINSON"
LOS_ANGELES_RAIDERS_RCB:	      .DB $48, "l.WASHINGTON"
LOS_ANGELES_RAIDERS_LCB:	      .DB $36, "terryMCDANIEL"
LOS_ANGELES_RAIDERS_FS:	          .DB $33, "eddieANDERSON"
LOS_ANGELES_RAIDERS_SS:	          .DB $45, "mikeHARDEN"
LOS_ANGELES_RAIDERS_K:	          .DB $18, "jeffJAEGER"
LOS_ANGELES_RAIDERS_P:	          .DB $06, "jeffGOSSETT"

SAN_DIEGO_QB1:	                  .DB $11, "b.j.TOLLIVER"
SAN_DIEGO_QB2:	                  .DB $13, "markVLASIC"
SAN_DIEGO_RB1:	                  .DB $35, "marionBUTTS"
SAN_DIEGO_RB2:	                  .DB $82, "rodBERNSTINE"
SAN_DIEGO_RB3:	                  .DB $46, "joeCARAVELLO"
SAN_DIEGO_RB4:	                  .DB $33, "ronnieHARMON"
SAN_DIEGO_WR1:	                  .DB $87, "quinnEARLY"
SAN_DIEGO_WR2:	                  .DB $83, "anthonyMILLER"
SAN_DIEGO_WR3:	                  .DB $81, "nateLEWIS"
SAN_DIEGO_WR4:	                  .DB $80, "wayneWALKER"
SAN_DIEGO_TE1:	                  .DB $89, "derrickWALKER"
SAN_DIEGO_TE2:	                  .DB $88, "arthurCOX"
SAN_DIEGO_C:	                  .DB $63, "frankCORNISH"
SAN_DIEGO_LG:	                  .DB $53, "courtneyHALL"
SAN_DIEGO_RG:	                  .DB $65, "davidRICHARDS"
SAN_DIEGO_LT:	                  .DB $78, "joelPATTEN"
SAN_DIEGO_RT:	                  .DB $76, "b.THOMPSON"
SAN_DIEGO_RE:	                  .DB $92, "burtGROSSMAN"
SAN_DIEGO_NT:	                  .DB $69, "lesMILLER"
SAN_DIEGO_LE:	                  .DB $99, "leeWILLIAMS"
SAN_DIEGO_ROLB:	                  .DB $91, "leslieO.NEAL"
SAN_DIEGO_RILB:	                  .DB $55, "juniorSEAU"
SAN_DIEGO_LILB:	                  .DB $50, "garyPLUMMER"
SAN_DIEGO_LOLB:	                  .DB $57, "henryROLLING"
SAN_DIEGO_RCB:	                  .DB $30, "samSEALE"
SAN_DIEGO_LCB:	                  .DB $22, "gillBYRD"
SAN_DIEGO_FS:	                  .DB $25, "vencieGLENN"
SAN_DIEGO_SS:	                  .DB $44, "martinBAYLESS"
SAN_DIEGO_K:	                  .DB $3, "johnCARNEY"
SAN_DIEGO_P:	                  .DB $10, "johnKIDD"

SEATTLE_QB1:	                  .DB $17, "daveKRIEG"
SEATTLE_QB2:	                  .DB $11, "kellySTOUFFER"
SEATTLE_RB1:	                  .DB $32, "john l.WILLIAMS"
SEATTLE_RB2:	                  .DB $44, "derrickFENNER"
SEATTLE_RB3:	                  .DB $30, "jamesJONES"
SEATTLE_RB4:	                  .DB $42, "chrisWARREN"
SEATTLE_WR1:	                  .DB $89, "brianBLADES"
SEATTLE_WR2:	                  .DB $81, "tommyKANE"
SEATTLE_WR3:	                  .DB $82, "paulSKANSI"
SEATTLE_WR4:	                  .DB $88, "jeffCHADWICK"
SEATTLE_TE1:	                  .DB $85, "ronHELLER"
SEATTLE_TE2:	                  .DB $86, "travisMCNEAL"
SEATTLE_C:	                      .DB $54, "grantFEASEL"
SEATTLE_LG:	                      .DB $65, "edwinBAILEY"
SEATTLE_RG:	                      .DB $71, "bryanMILLARD"
SEATTLE_LT:	                      .DB $66, "andyHECK"
SEATTLE_RT:	                      .DB $70, "ronMATTES"
SEATTLE_RE:	                      .DB $57, "tonyWOODS"
SEATTLE_NT:	                      .DB $72, "joeNASH"
SEATTLE_LE:	                      .DB $79, "jacobGREEN"
SEATTLE_ROLB:	                  .DB $97, "rufusPORTER"
SEATTLE_RILB:	                  .DB $96, "cortezKENNEDY"
SEATTLE_LILB:	                  .DB $92, "davidWYMAN"
SEATTLE_LOLB:	                  .DB $51, "terryWOODEN"
SEATTLE_RCB:	                  .DB $27, "patrickHUNTER"
SEATTLE_LCB:	                  .DB $29, "dwayneHARPER"
SEATTLE_FS:	                      .DB $41, "eugeneROBINSON"
SEATTLE_SS:	                      .DB $22, "nesbyGLASGOW"
SEATTLE_K:	                      .DB $09, "normJOHNSON"
SEATTLE_P:	                      .DB $03, "rickDONNELLY"

WASHINGTON_QB1:	                  .DB $11, "markRYPIEN"
WASHINGTON_QB2:	                  .DB $16, "stanHUMPHRIES"
WASHINGTON_RB1:	                  .DB $21, "earnestBYNER"
WASHINGTON_RB2:	                  .DB $83, "rickySANDERS"
WASHINGTON_RB3:	                  .DB $37, "geraldRIGGS"
WASHINGTON_RB4:	                  .DB $24, "kelvinBRYANT"
WASHINGTON_WR1:	                  .DB $81, "artMONK"
WASHINGTON_WR2:	                  .DB $84, "garyCLARK"
WASHINGTON_WR3:	                  .DB $30, "brianMITCHELL"
WASHINGTON_WR4:	                  .DB $80, "joeHOWARD"
WASHINGTON_TE1:	                  .DB $85, "donWARREN"
WASHINGTON_TE2:	                  .DB $88, "jimmieJOHNSON"
WASHINGTON_C:	                  .DB $53, "jeffBOSTIC"
WASHINGTON_LG:	                  .DB $68, "russGRIMM"
WASHINGTON_RG:	                  .DB $63, "raleighMCKENZIE"
WASHINGTON_LT:	                  .DB $79, "jimLACHEY"
WASHINGTON_RT:	                  .DB $76, "edSIMMONS"
WASHINGTON_RE:	                  .DB $74, "markusKOCH"
WASHINGTON_NT:	                  .DB $77, "darrylGRANT"
WASHINGTON_LE:	                  .DB $71, "charlesMANN"
WASHINGTON_ROLB:	              .DB $58, "wilberMARSHALL"
WASHINGTON_RILB:	              .DB $91, "gregMANUSKY"
WASHINGTON_LILB:	              .DB $99, "tracyROCKER"
WASHINGTON_LOLB:	              .DB $55, "andreCOLLINS"
WASHINGTON_RCB:	                  .DB $28, "darrellGREEN"
WASHINGTON_LCB:	                  .DB $35, "martinMAYHEW"
WASHINGTON_FS:	                  .DB $23, "toddBOWLES"
WASHINGTON_SS:	                  .DB $40, "alvinWALTON"
WASHINGTON_K:	                  .DB $08, "chipLOHMILLER"
WASHINGTON_P:	                  .DB $02, "kellyGOODBURN"

NEW_YORK_GIANTS_QB1:	          .DB $11, "philSIMMS"
NEW_YORK_GIANTS_QB2:	          .DB $15, "jeffHOSTETLER"
NEW_YORK_GIANTS_RB1:	          .DB $24, "ottisANDERSON"
NEW_YORK_GIANTS_RB2:	          .DB $30, "davidMEGGETT"
NEW_YORK_GIANTS_RB3:	          .DB $44, "mauriceCARTHON"
NEW_YORK_GIANTS_RB4:	          .DB $27, "rodneyHAMPTON"
NEW_YORK_GIANTS_WR1:	          .DB $82, "markINGRAM"
NEW_YORK_GIANTS_WR2:	          .DB $85, "stephenBAKER"
NEW_YORK_GIANTS_WR3:	          .DB $81, "staceyROBINSON"
NEW_YORK_GIANTS_WR4:	          .DB $83, "odessaTURNER"
NEW_YORK_GIANTS_TE1:	          .DB $89, "markBAVARO"
NEW_YORK_GIANTS_TE2:	          .DB $87, "howardCROSS"
NEW_YORK_GIANTS_C:	              .DB $65, "bartOATES"
NEW_YORK_GIANTS_LG:	              .DB $66, "williamROBERTS"
NEW_YORK_GIANTS_RG:	              .DB $60, "ericMOORE"
NEW_YORK_GIANTS_LT:	              .DB $76, "johnELLIOTT"
NEW_YORK_GIANTS_RT:	              .DB $72, "dougRIESENBERG"
NEW_YORK_GIANTS_RE:	              .DB $70, "leonardMARSHALL"
NEW_YORK_GIANTS_NT:	              .DB $74, "erikHOWARD"
NEW_YORK_GIANTS_LE:	              .DB $77, "ericDORSEY"
NEW_YORK_GIANTS_ROLB:	          .DB $56, "lawrenceTAYLOR"
NEW_YORK_GIANTS_RILB:	          .DB $52, "pepperJOHNSON"
NEW_YORK_GIANTS_LILB:	          .DB $55, "garyREASONS"
NEW_YORK_GIANTS_LOLB:	          .DB $58, "carlBANKS"
NEW_YORK_GIANTS_RCB:	          .DB $28, "eversonWALLS"
NEW_YORK_GIANTS_LCB:	          .DB $25, "markCOLLINS"
NEW_YORK_GIANTS_FS:	              .DB $29, "myronGUYTON"
NEW_YORK_GIANTS_SS:	              .DB $47, "gregJACKSON"
NEW_YORK_GIANTS_K:	              .DB $09, "mattBAHR"
NEW_YORK_GIANTS_P:	              .DB $05, "seanLANDETA"

PHILADELPHIA_QB1:	              .DB $00, "qbEAGLES"
PHILADELPHIA_QB2:	              .DB $09, "jimMCMAHON"
PHILADELPHIA_RB1:	              .DB $41, "keithBYARS"
PHILADELPHIA_RB2:	              .DB $23, "heathSHERMAN"
PHILADELPHIA_RB3:	              .DB $25, "anthonyTONEY"
PHILADELPHIA_RB4:	              .DB $36, "robertDRUMMOND"
PHILADELPHIA_WR1:	              .DB $86, "fredBARNETT"
PHILADELPHIA_WR2:	              .DB $89, "calvinWILLIAMS"
PHILADELPHIA_WR3:	              .DB $82, "mikeQUICK"
PHILADELPHIA_WR4:	              .DB $85, "kennyJACKSON"
PHILADELPHIA_TE1:	              .DB $88, "keithJACKSON"
PHILADELPHIA_TE2:	              .DB $87, "harperLE BEL"
PHILADELPHIA_C:	                  .DB $72, "davidALEXANDER"
PHILADELPHIA_LG:	              .DB $79, "mikeSCHAD"
PHILADELPHIA_RG:	              .DB $66, "ronSOLT"
PHILADELPHIA_LT:	              .DB $73, "ronHELLER"
PHILADELPHIA_RT:	              .DB $68, "r.SINGLETARY"
PHILADELPHIA_RE:	              .DB $96, "clydeSIMMONS"
PHILADELPHIA_NT:	              .DB $90, "mikeGOLIC"
PHILADELPHIA_LE:	              .DB $92, "reggieWHITE"
PHILADELPHIA_ROLB:	              .DB $52, "jessieSMALL"
PHILADELPHIA_RILB:	              .DB $99, "jeromeBROWN"
PHILADELPHIA_LILB:	              .DB $56, "byronEVANS"
PHILADELPHIA_LOLB:	              .DB $59, "sethJOYNER"
PHILADELPHIA_RCB:	              .DB $21, "ericALLEN"
PHILADELPHIA_LCB:	              .DB $26, "benSMITH"
PHILADELPHIA_FS:	              .DB $48, "wesHOPKINS"
PHILADELPHIA_SS:	              .DB $20, "andreWATERS"
PHILADELPHIA_K:	                  .DB $07, "rogerRUZEK"
PHILADELPHIA_P:	                  .DB $05, "jeffFEAGLES"

PHOENIX_QB1:	                  .DB $03, "timmROSENBACH"
PHOENIX_QB2:	                  .DB $19, "tomTUPA"
PHOENIX_RB1:	                  .DB $39, "johnnyJOHNSON"
PHOENIX_RB2:	                  .DB $81, "royGREEN"
PHOENIX_RB3:	                  .DB $24, "ronWOLFLEY"
PHOENIX_RB4:	                  .DB $36, "vaiSIKAHEMA"
PHOENIX_WR1:	                  .DB $87, "rickyPROEHL"
PHOENIX_WR2:	                  .DB $86, "ernieJONES"
PHOENIX_WR3:	                  .DB $34, "anthonyTHOMPSON"
PHOENIX_WR4:	                  .DB $84, "j.t.SMITH"
PHOENIX_TE1:	                  .DB $89, "walterREEVES"
PHOENIX_TE2:	                  .DB $85, "timJORDEN"
PHOENIX_C:	                      .DB $51, "billLEWIS"
PHOENIX_LG:	                      .DB $70, "derekKENNARD"
PHOENIX_RG:	                      .DB $61, "lanceSMITH"
PHOENIX_LT:	                      .DB $67, "luisSHARPE"
PHOENIX_RT:	                      .DB $63, "tootieROBBINS"
PHOENIX_RE:	                      .DB $72, "rodSADDLER"
PHOENIX_NT:	                      .DB $66, "jimWAHLER"
PHOENIX_LE:	                      .DB $78, "freddie joeNUNN"
PHOENIX_ROLB:	                  .DB $56, "kenHARVEY"
PHOENIX_RILB:	                  .DB $53, "garthJAX"
PHOENIX_LILB:	                  .DB $58, "ericHILL"
PHOENIX_LOLB:	                  .DB $55, "anthonyBELL"
PHOENIX_RCB:	                  .DB $27, "jayTAYLOR"
PHOENIX_LCB:	                  .DB $47, "cedricMACK"
PHOENIX_FS:	                      .DB $43, "lonnieYOUNG"
PHOENIX_SS:	                      .DB $46, "timMCDONALD"
PHOENIX_K:	                      .DB $17, "alDEL GRECO"
PHOENIX_P:	                      .DB $16, "richCAMARILLO"

DALLAS_QB1:	                      .DB $08, "troyAIKMAN"
DALLAS_QB2:	                      .DB $15, "babeLAUFENBERG"
DALLAS_RB1:	                      .DB $22, "emmittSMITH"
DALLAS_RB2:	                      .DB $34, "tommieAGEE"
DALLAS_RB3:	                      .DB $32, "alonzoHIGHSMITH"
DALLAS_RB4:	                      .DB $39, "robertPERRYMAN"
DALLAS_WR1:	                      .DB $83, "kelvinMARTIN"
DALLAS_WR2:	                      .DB $88, "michaelIRVIN"
DALLAS_WR3:	                      .DB $81, "alexanderWRIGHT"
DALLAS_WR4:	                      .DB $86, "jamesDIXON"
DALLAS_TE1:	                      .DB $84, "jayNOVACEK"
DALLAS_TE2:	                      .DB $89, "robAWALT"
DALLAS_C:	                      .DB $53, "markSTEPNOSKI"
DALLAS_LG:	                      .DB $68, "crawfordKER"
DALLAS_RG:	                      .DB $67, "johnGESEK"
DALLAS_LT:	                      .DB $66, "kevinGOGAN"
DALLAS_RT:	                      .DB $61, "nateNEWTON"
DALLAS_RE:	                      .DB $92, "tonyTOLBERT"
DALLAS_NT:	                      .DB $73, "dannyNOONAN"
DALLAS_LE:	                      .DB $96, "danielSTUBBS"
DALLAS_ROLB:	                  .DB $51, "kenNORTON"
DALLAS_RILB:	                  .DB $56, "eugeneLOCKHART"
DALLAS_LILB:	                  .DB $97, "jimmieJONES"
DALLAS_LOLB:	                  .DB $55, "jackDEL RIO"
DALLAS_RCB:	                      .DB $45, "mannyHENDRIX"
DALLAS_LCB:	                      .DB $30, "issiacHOLT"
DALLAS_FS:	                      .DB $20, "rayHORTON"
DALLAS_SS:	                      .DB $37, "jamesWASHINGTON"
DALLAS_K:	                      .DB $01, "kenWILLIS"
DALLAS_P:	                      .DB $04, "mikeSAXON"

CHICAGO_QB1:	                  .DB $04, "jimHARBAUGH"
CHICAGO_QB2:	                  .DB $18, "mikeTOMCZAK"
CHICAGO_RB1:	                  .DB $25, "bradMUSTER"
CHICAGO_RB2:	                  .DB $35, "nealANDERSON"
CHICAGO_RB3:	                  .DB $31, "markGREEN"
CHICAGO_RB4:	                  .DB $22, "johnnyBAILEY"
CHICAGO_WR1:	                  .DB $84, "ronMORRIS"
CHICAGO_WR2:	                  .DB $82, "wendellDAVIS"
CHICAGO_WR3:	                  .DB $88, "glenKOZLOWSKI"
CHICAGO_WR4:	                  .DB $29, "dennisGENTRY"
CHICAGO_TE1:	                  .DB $80, "jamesTHORNTON"
CHICAGO_TE2:	                  .DB $86, "capBOSO"
CHICAGO_C:	                      .DB $63, "jayHILGENBERG"
CHICAGO_LG:	                      .DB $62, "markBORTZ"
CHICAGO_RG:	                      .DB $57, "tomTHAYER"
CHICAGO_LT:	                      .DB $74, "jimCOVERT"
CHICAGO_RT:	                      .DB $78, "keithVAN HORNE"
CHICAGO_RE:	                      .DB $95, "richardDENT"
CHICAGO_NT:	                      .DB $72, "williamPERRY"
CHICAGO_LE:	                      .DB $93, "traceARMSTRONG"
CHICAGO_ROLB:	                  .DB $51, "jimMORRISSEY"
CHICAGO_RILB:	                  .DB $99, "danHAMPTON"
CHICAGO_LILB:	                  .DB $50, "mikeSINGLETARY"
CHICAGO_LOLB:	                  .DB $59, "ronRIVERA"
CHICAGO_RCB:	                  .DB $32, "lemuelSTINSON"
CHICAGO_LCB:	                  .DB $21, "donnellWOOLFORD"
CHICAGO_FS:	                      .DB $20, "markCARRIER"
CHICAGO_SS:	                      .DB $23, "shaunGAYLE"
CHICAGO_K:	                      .DB $06, "kevinBUTLER"
CHICAGO_P:	                      .DB $08, "mauryBUFORD"

DETROIT_QB1:	                  .DB $09, "rodneyPEETE"
DETROIT_QB2:	                  .DB $11, "andreWARE"
DETROIT_RB1:	                  .DB $20, "barrySANDERS"
DETROIT_RB2:	                  .DB $83, "aubreyMATTHEWS"
DETROIT_RB3:	                  .DB $34, "jamesWILDER"
DETROIT_RB4:	                  .DB $23, "melGRAY"
DETROIT_WR1:	                  .DB $84, "richardJOHNSON"
DETROIT_WR2:	                  .DB $82, "robertCLARK"
DETROIT_WR3:	                  .DB $86, "willieGREEN"
DETROIT_WR4:	                  .DB $87, "jeffCAMPBELL"
DETROIT_TE1:	                  .DB $89, "terryGREER"
DETROIT_TE2:	                  .DB $81, "mikeFARR"
DETROIT_C:	                      .DB $53, "kevinGLOVER"
DETROIT_LG:	                      .DB $65, "ericANDOLSEK"
DETROIT_RG:	                      .DB $67, "kenDALLAFIOR"
DETROIT_LT:	                      .DB $75, "lomasBROWN"
DETROIT_RT:	                      .DB $73, "harveySALEM"
DETROIT_RE:	                      .DB $70, "danOWENS"
DETROIT_NT:	                      .DB $93, "jerryBALL"
DETROIT_LE:	                      .DB $77, "keithFERGUSON"
DETROIT_ROLB:	                  .DB $55, "michaelCOFER"
DETROIT_RILB:	                  .DB $98, "dennisGIBSON"
DETROIT_LILB:	                  .DB $54, "chrisSPIELMAN"
DETROIT_LOLB:	                  .DB $58, "georgeJAMISON"
DETROIT_RCB:	                  .DB $47, "leroyIRVIN"
DETROIT_LCB:	                  .DB $39, "rayCROCKETT"
DETROIT_FS:	                      .DB $36, "bennieBLADES"
DETROIT_SS:	                      .DB $35, "williamWHITE"
DETROIT_K:	                      .DB $03, "eddieMURRAY"
DETROIT_P:	                      .DB $06, "jimARNOLD"

GREEN_BAY_QB1:	                  .DB $07, "donMAJKOWSKI"
GREEN_BAY_QB2:	                  .DB $08, "anthonyDILWEG"
GREEN_BAY_RB1:	                  .DB $33, "keithWOODSIDE"
GREEN_BAY_RB2:	                  .DB $35, "michaelHADDIX"
GREEN_BAY_RB3:	                  .DB $39, "darrellTHOMPSON"
GREEN_BAY_RB4:	                  .DB $27, "hermanFONTENOT"
GREEN_BAY_WR1:	                  .DB $84, "sterlingSHARPE"
GREEN_BAY_WR2:	                  .DB $81, "perryKEMP"
GREEN_BAY_WR3:	                  .DB $88, "charlesWILSON"
GREEN_BAY_WR4:	                  .DB $85, "jeffQUERY"
GREEN_BAY_TE1:	                  .DB $86, "edWEST"
GREEN_BAY_TE2:	                  .DB $80, "jackieHARRIS"
GREEN_BAY_C:	                  .DB $63, "jamesCAMPEN"
GREEN_BAY_LG:	                  .DB $57, "richMORAN"
GREEN_BAY_RG:	                  .DB $65, "ronHALLSTROM"
GREEN_BAY_LT:	                  .DB $73, "alanVEINGRAD"
GREEN_BAY_RT:	                  .DB $77, "tonyMANDARICH"
GREEN_BAY_RE:	                  .DB $93, "robertBROWN"
GREEN_BAY_NT:	                  .DB $79, "bobNELSON"
GREEN_BAY_LE:	                  .DB $62, "mattBROCK"
GREEN_BAY_ROLB:	                  .DB $97, "timHARRIS"
GREEN_BAY_RILB:	                  .DB $50, "johnnyHOLLAND"
GREEN_BAY_LILB:	                  .DB $91, "brianNOBLE"
GREEN_BAY_LOLB:	                  .DB $54, "scottSTEPHEN"
GREEN_BAY_RCB:	                  .DB $44, "jerryHOLMES"
GREEN_BAY_LCB:	                  .DB $22, "markLEE"
GREEN_BAY_FS:	                  .DB $26, "chuckCECIL"
GREEN_BAY_SS:	                  .DB $37, "markMURPHY"
GREEN_BAY_K:	                  .DB $13, "chrisJACKE"
GREEN_BAY_P:	                  .DB $17, "donBRACKEN"

MINNESOTA_QB1:	                  .DB $11, "wadeWILSON"
MINNESOTA_QB2:	                  .DB $16, "richGANNON"
MINNESOTA_RB1:	                  .DB $34, "herschelWALKER"
MINNESOTA_RB2:	                  .DB $31, "rickFENNEY"
MINNESOTA_RB3:	                  .DB $33, "jessieCLARK"
MINNESOTA_RB4:	                  .DB $46, "alfredANDERSON"
MINNESOTA_WR1:	                  .DB $84, "hassanJONES"
MINNESOTA_WR2:	                  .DB $81, "anthonyCARTER"
MINNESOTA_WR3:	                  .DB $87, "leoLEWIS"
MINNESOTA_WR4:	                  .DB $80, "crisCARTER"
MINNESOTA_TE1:	                  .DB $83, "steveJORDAN"
MINNESOTA_TE2:	                  .DB $82, "mikeJONES"
MINNESOTA_C:	                  .DB $63, "kirkLOWDERMILK"
MINNESOTA_LG:	                  .DB $64, "randallMCDANIEL"
MINNESOTA_RG:	                  .DB $69, "toddKALIS"
MINNESOTA_LT:	                  .DB $65, "garyZIMMERMAN"
MINNESOTA_RT:	                  .DB $76, "timIRWIN"
MINNESOTA_RE:	                  .DB $56, "chrisDOLEMAN"
MINNESOTA_NT:	                  .DB $97, "henryTHOMAS"
MINNESOTA_LE:	                  .DB $99, "alNOGA"
MINNESOTA_ROLB:	                  .DB $57, "m.MERRIWEATHER"
MINNESOTA_RILB:	                  .DB $75, "keithMILLARD"
MINNESOTA_LILB:	                  .DB $55, "scottSTUDWELL"
MINNESOTA_LOLB:	                  .DB $50, "rayBERRY"
MINNESOTA_RCB:	                  .DB $48, "reggieRUTLAND"
MINNESOTA_LCB:	                  .DB $39, "carlLEE"
MINNESOTA_FS:	                  .DB $29, "d.FULLINGTON"
MINNESOTA_SS:	                  .DB $47, "joeyBROWNER"
MINNESOTA_K:	                  .DB $07, "fuadREVEIZ"
MINNESOTA_P:	                  .DB $18, "harryNEWSOME"

TAMPA_BAY_QB1:	                  .DB $14, "vinnyTESTAVERDE"
TAMPA_BAY_QB2:	                  .DB $07, "jeffCARLSON"
TAMPA_BAY_RB1:	                  .DB $40, "garyANDERSON"
TAMPA_BAY_RB2:	                  .DB $33, "reggieCOBB"
TAMPA_BAY_RB3:	                  .DB $32, "brucePERKINS"
TAMPA_BAY_RB4:	                  .DB $26, "johnHARVEY"
TAMPA_BAY_WR1:	                  .DB $88, "markCARRIER"
TAMPA_BAY_WR2:	                  .DB $84, "bruceHILL"
TAMPA_BAY_WR3:	                  .DB $83, "dannyPEEBLES"
TAMPA_BAY_WR4:	                  .DB $87, "willieDREWREY"
TAMPA_BAY_TE1:	                  .DB $82, "ronHALL"
TAMPA_BAY_TE2:	                  .DB $89, "jesseANDERSON"
TAMPA_BAY_C:	                  .DB $60, "randyGRIMES"
TAMPA_BAY_LG:	                  .DB $75, "carlBAX"
TAMPA_BAY_RG:	                  .DB $62, "ianBECKLES"
TAMPA_BAY_LT:	                  .DB $74, "paulGRUBER"
TAMPA_BAY_RT:	                  .DB $72, "robTAYLOR"
TAMPA_BAY_RE:	                  .DB $71, "jimSKOW"
TAMPA_BAY_NT:	                  .DB $96, "timNEWTON"
TAMPA_BAY_LE:	                  .DB $79, "ruebenDAVIS"
TAMPA_BAY_ROLB:	                  .DB $59, "kevinMURPHY"
TAMPA_BAY_RILB:	                  .DB $58, "winstonMOSS"
TAMPA_BAY_LILB:	                  .DB $99, "eugeneMARVE"
TAMPA_BAY_LOLB:	                  .DB $51, "broderickTHOMAS"
TAMPA_BAY_RCB:	                  .DB $45, "wayneHADDIX"
TAMPA_BAY_LCB:	                  .DB $29, "rickyREYNOLDS"
TAMPA_BAY_FS:	                  .DB $39, "harryHAMILTON"
TAMPA_BAY_SS:	                  .DB $30, "markROBINSON"
TAMPA_BAY_K:	                  .DB $02, "steveCHRISTIE"
TAMPA_BAY_P:	                  .DB $03, "markROYALS"

SAN_FRANCISCO_QB1:	              .DB $16, "joeMONTANA"
SAN_FRANCISCO_QB2:	              .DB $08, "steveYOUNG"
SAN_FRANCISCO_RB1:	              .DB $33, "rogerCRAIG"
SAN_FRANCISCO_RB2:	              .DB $44, "tomRATHMAN"
SAN_FRANCISCO_RB3:	              .DB $35, "dexterCARTER"
SAN_FRANCISCO_RB4:	              .DB $24, "harrySYDNEY"
SAN_FRANCISCO_WR1:	              .DB $82, "johnTAYLOR"
SAN_FRANCISCO_WR2:	              .DB $80, "jerryRICE"
SAN_FRANCISCO_WR3:	              .DB $85, "mikeWILSON"
SAN_FRANCISCO_WR4:	              .DB $88, "mikeSHERRARD"
SAN_FRANCISCO_TE1:	              .DB $84, "brentJONES"
SAN_FRANCISCO_TE2:	              .DB $81, "jamieWILLIAMS"
SAN_FRANCISCO_C:	              .DB $61, "jesseSAPOLU"
SAN_FRANCISCO_LG:	              .DB $62, "guyMCINTYRE"
SAN_FRANCISCO_RG:	              .DB $79, "harrisBARTON"
SAN_FRANCISCO_LT:	              .DB $77, "bubbaPARIS"
SAN_FRANCISCO_RT:	              .DB $74, "steveWALLACE"
SAN_FRANCISCO_RE:	              .DB $75, "kevinFAGAN"
SAN_FRANCISCO_NT:	              .DB $95, "michaelCARTER"
SAN_FRANCISCO_LE:	              .DB $78, "pierceHOLT"
SAN_FRANCISCO_ROLB:	              .DB $53, "billROMANOWSKI"
SAN_FRANCISCO_RILB:	              .DB $59, "keithDELONG"
SAN_FRANCISCO_LILB:	              .DB $54, "mattMILLEN"
SAN_FRANCISCO_LOLB:	              .DB $94, "charlesHALEY"
SAN_FRANCISCO_RCB:	              .DB $29, "donGRIFFIN"
SAN_FRANCISCO_LCB:	              .DB $26, "darrylPOLLARD"
SAN_FRANCISCO_FS:	              .DB $42, "ronnieLOTT"
SAN_FRANCISCO_SS:	              .DB $43, "daveWAYMER"
SAN_FRANCISCO_K:	              .DB $06, "mikeCOFER"
SAN_FRANCISCO_P:	              .DB $09, "barryHELTON"

LOS_ANGELES_RAMS_QB1:	          .DB $11, "jimEVERETT"
LOS_ANGELES_RAMS_QB2:	          .DB $16, "chuckLONG"
LOS_ANGELES_RAMS_RB1:	          .DB $43, "clevelandGARY"
LOS_ANGELES_RAMS_RB2:	          .DB $21, "curtWARNER"
LOS_ANGELES_RAMS_RB3:	          .DB $44, "gastonGREEN"
LOS_ANGELES_RAMS_RB4:	          .DB $24, "bufordMCGEE"
LOS_ANGELES_RAMS_WR1:	          .DB $80, "henryELLARD"
LOS_ANGELES_RAMS_WR2:	          .DB $83, "willieANDERSON"
LOS_ANGELES_RAMS_WR3:	          .DB $89, "derrickFAISON"
LOS_ANGELES_RAMS_WR4:	          .DB $84, "aaronCOX"
LOS_ANGELES_RAMS_TE1:	          .DB $81, "peteHOLOHAN"
LOS_ANGELES_RAMS_TE2:	          .DB $86, "damoneJOHNSON"
LOS_ANGELES_RAMS_C:	              .DB $56, "dougSMITH"
LOS_ANGELES_RAMS_LG:	          .DB $66, "tomNEWBERRY"
LOS_ANGELES_RAMS_RG:	          .DB $61, "bernBROSTEK"
LOS_ANGELES_RAMS_LT:	          .DB $75, "irvPANKEY"
LOS_ANGELES_RAMS_RT:	          .DB $78, "jackieSLATER"
LOS_ANGELES_RAMS_RE:	          .DB $96, "brianSMITH"
LOS_ANGELES_RAMS_NT:	          .DB $99, "alvinWRIGHT"
LOS_ANGELES_RAMS_LE:	          .DB $93, "dougREED"
LOS_ANGELES_RAMS_ROLB:	          .DB $54, "mikeWILCHER"
LOS_ANGELES_RAMS_RILB:	          .DB $53, "fredSTRICKLAND"
LOS_ANGELES_RAMS_LILB:	          .DB $50, "frankSTAMS"
LOS_ANGELES_RAMS_LOLB:	          .DB $91, "kevinGREENE"
LOS_ANGELES_RAMS_RCB:	          .DB $48, "bobbyHUMPHERY"
LOS_ANGELES_RAMS_LCB:	          .DB $25, "jerryGRAY"
LOS_ANGELES_RAMS_FS:	          .DB $26, "anthonyNEWMAN"
LOS_ANGELES_RAMS_SS:	          .DB $22, "vinceNEWSOME"
LOS_ANGELES_RAMS_K:	              .DB $01, "mikeLANSFORD"
LOS_ANGELES_RAMS_P:	              .DB $08, "keithENGLISH"

NEW_ORLEANS_QB1:	              .DB $03, "steveWALSH"
NEW_ORLEANS_QB2:	              .DB $11, "johnFOURCADE"
NEW_ORLEANS_RB1:	              .DB $34, "craigHEYWARD"
NEW_ORLEANS_RB2:	              .DB $21, "daltonHILLIARD"
NEW_ORLEANS_RB3:	              .DB $36, "ruebenMAYES"
NEW_ORLEANS_RB4:	              .DB $22, "gilFENERTY"
NEW_ORLEANS_WR1:	              .DB $84, "ericMARTIN"
NEW_ORLEANS_WR2:	              .DB $80, "brentPERRIMAN"
NEW_ORLEANS_WR3:	              .DB $87, "lonzellHILL"
NEW_ORLEANS_WR4:	              .DB $88, "floydTURNER"
NEW_ORLEANS_TE1:	              .DB $85, "hobyBRENNER"
NEW_ORLEANS_TE2:	              .DB $82, "johnTICE"
NEW_ORLEANS_C:	                  .DB $61, "joelHILGENBERG"
NEW_ORLEANS_LG:	                  .DB $72, "jimDOMBROWSKI"
NEW_ORLEANS_RG:	                  .DB $65, "steveTRAPILO"
NEW_ORLEANS_LT:	                  .DB $74, "kevinHAVERDINK"
NEW_ORLEANS_RT:	                  .DB $67, "stanBROCK"
NEW_ORLEANS_RE:	                  .DB $97, "renaldoTURNBULL"
NEW_ORLEANS_NT:	                  .DB $94, "jimWILKS"
NEW_ORLEANS_LE:	                  .DB $93, "wayneMARTIN"
NEW_ORLEANS_ROLB:	              .DB $56, "patSWILLING"
NEW_ORLEANS_RILB:	              .DB $53, "vaughanJOHNSON"
NEW_ORLEANS_LILB:	              .DB $51, "samMILLS"
NEW_ORLEANS_LOLB:	              .DB $57, "rickeyJACKSON"
NEW_ORLEANS_RCB:	              .DB $41, "toiCOOK"
NEW_ORLEANS_LCB:	              .DB $40, "robertMASSEY"
NEW_ORLEANS_FS:	                  .DB $28, "geneATKINS"
NEW_ORLEANS_SS:	                  .DB $39, "brettMAXIE"
NEW_ORLEANS_K:	                  .DB $07, "mortenANDERSEN"
NEW_ORLEANS_P:	                  .DB $06, "tommyBARNHARDT"

ATLANTA_QB1:	                  .DB $12, "chrisMILLER"
ATLANTA_QB2:	                  .DB $07, "hughMILLEN"
ATLANTA_RB1:	                  .DB $30, "mikeROZIER"
ATLANTA_RB2:	                  .DB $81, "michaelHAYNES"
ATLANTA_RB3:	                  .DB $34, "steveBROUSSARD"
ATLANTA_RB4:	                  .DB $38, "keithJONES"
ATLANTA_WR1:	                  .DB $86, "floydDIXON"
ATLANTA_WR2:	                  .DB $80, "andreRISON"
ATLANTA_WR3:	                  .DB $43, "tracyJOHNSON"
ATLANTA_WR4:	                  .DB $89, "georgeTHOMAS"
ATLANTA_TE1:	                  .DB $85, "shawnCOLLINS"
ATLANTA_TE2:	                  .DB $87, "garyWILKINS"
ATLANTA_C:	                      .DB $64, "jamieDUKES"
ATLANTA_LG:	                      .DB $69, "houstonHOOVER"
ATLANTA_RG:	                      .DB $79, "billFRALIC"
ATLANTA_LT:	                      .DB $78, "mikeKENN"
ATLANTA_RT:	                      .DB $71, "chrisHINTON"
ATLANTA_RE:	                      .DB $99, "timGREEN"
ATLANTA_NT:	                      .DB $97, "toryEPPS"
ATLANTA_LE:	                      .DB $76, "mikeGANN"
ATLANTA_ROLB:	                  .DB $56, "darionCONNER"
ATLANTA_RILB:	                  .DB $59, "johnRADE"
ATLANTA_LILB:	                  .DB $58, "jessieTUGGLE"
ATLANTA_LOLB:	                  .DB $95, "michaelREID"
ATLANTA_RCB:	                  .DB $21, "deionSANDERS"
ATLANTA_LCB:	                  .DB $22, "charlesDIMRY"
ATLANTA_FS:	                      .DB $25, "scottCASE"
ATLANTA_SS:	                      .DB $40, "brianJORDAN"
ATLANTA_K:	                      .DB $05, "gregDAVIS"
ATLANTA_P:	                      .DB $17, "scottFULHAGE"

PLAYER_LIST_END:	              .DB $FF

_F}_PLAYER_NUMBERS_AND_NAMES

.PAD $B000, $FF

_F{_PLAYER_ABILITIES

.ENUM $00
QB_ONE_ABILITIES_OFFSET			.dsb 5
QB_TWO_ABILITIES_OFFSET			.dsb 5
RB_ONE_ABILITIES_OFFSET			.dsb 4
RB_TWO_ABILITIES_OFFSET			.dsb 4
RB_THREE_ABILITIES_OFFSET		.dsb 4
RB_FOUR_ABILITIES_OFFSET		.dsb 4
WR_ONE_ABILITIES_OFFSET			.dsb 4
WR_TWO_ABILITIES_OFFSET			.dsb 4
WR_THREE_ABILITIES_OFFSET		.dsb 4
WR_FOUR_ABILITIES_OFFSET		.dsb 4
TE_ONE_ABILITIES_OFFSET			.dsb 4
TE_TWO_ABILITIES_OFFSET			.dsb 4
CENTER_ABILITIES_OFFSET			.dsb 3
LEFT_GUARD_ABILITIES_OFFSET		.dsb 3
RIGHT_GUARD_ABILITIES_OFFSET	.dsb 3
LEFT_TACKLE_ABILITIES_OFFSET	.dsb 3
RIGHT_TACKLE_ABILITIES_OFFSET	.dsb 3
RE_ABILITIES_OFFSET				.dsb 4
NT_ABILITIES_OFFSET				.dsb 4
LE_ABILITIES_OFFSET				.dsb 4
ROLB_ABILITIES_OFFSET			.dsb 4
RILB_ABILITIES_OFFSET			.dsb 4
LILB_ABILITIES_OFFSET			.dsb 4
LOLB_ABILITIES_OFFSET			.dsb 4
RCB_ABILITIES_OFFSET			.dsb 4
LCB_ABILITIES_OFFSET			.dsb 4
FS_ABILITIES_OFFSET				.dsb 4
SS_ABILITIES_OFFSET				.dsb 4
K_ABILITIES_OFFSET				.dsb 4
P_ABILITIES_OFFSET				.dsb 4
.ENDE

BUFFALO_ABILITIES:
	.DB $A3,$11,$52,$8C,$CC
	.DB $A3,$11,$22,$46,$37
	.DB $A5,$93,$83,$B7
	.DB $A6,$3D,$51,$73
	.DB $A5,$32,$A5,$74
	.DB $A5,$32,$8B,$74
	.DB $A3,$51,$81,$78
	.DB $A3,$81,$B6,$8A
	.DB $A3,$61,$40,$76
	.DB $A3,$21,$9A,$76
	.DB $A3,$57,$B7,$77
	.DB $A3,$26,$50,$74
	.DB $A3,$5A,$1E
	.DB $A3,$58,$07
	.DB $A3,$39,$24
	.DB $A3,$37,$48
	.DB $A3,$29,$88
	.DB $86,$AB,$88,$3C
	.DB $43,$47,$0B,$22
	.DB $43,$56,$AC,$47
	.DB $64,$75,$AD,$69
	.DB $43,$55,$30,$48
	.DB $64,$78,$2F,$2A
	.DB $75,$99,$82,$2A
	.DB $65,$85,$C3,$58
	.DB $43,$65,$89,$77
	.DB $54,$75,$26,$66
	.DB $54,$76,$84,$67
	.DB $C8,$C4,$29,$66
	.DB $83,$64,$20,$29
	
INDIANAPOLIS_ABILITIES:
	.DB $A3,$01,$04,$74,$53
	.DB $A3,$11,$03,$45,$47
	.DB $A5,$47,$C0,$73
	.DB $A5,$64,$96,$79
	.DB $A5,$43,$92,$73
	.DB $A5,$53,$C6,$73
	.DB $A5,$51,$AB,$7A
	.DB $A6,$51,$A5,$79
	.DB $A5,$51,$9F,$76
	.DB $A3,$31,$BD,$76
	.DB $A3,$37,$0E,$75
	.DB $A3,$27,$AE,$74
	.DB $A3,$37,$AF
	.DB $A3,$37,$95
	.DB $A3,$55,$27
	.DB $A3,$29,$C1
	.DB $A3,$28,$07
	.DB $43,$48,$B8,$23
	.DB $43,$37,$8A,$22
	.DB $43,$57,$87,$29
	.DB $43,$57,$26,$35
	.DB $43,$44,$31,$34
	.DB $43,$46,$88,$37
	.DB $43,$46,$84,$35
	.DB $43,$55,$99,$44
	.DB $43,$55,$85,$44
	.DB $43,$56,$32,$66
	.DB $43,$65,$A1,$56
	.DB $C8,$C4,$10,$55
	.DB $83,$64,$40,$B8
	
MIAMI_ABILITIES:
	.DB $A3,$01,$06,$CA,$9A
	.DB $A3,$11,$40,$66,$37
	.DB $A6,$59,$8D,$73
	.DB $A6,$4D,$B4,$76
	.DB $A6,$56,$85,$73
	.DB $A5,$53,$8E,$75
	.DB $A4,$61,$D0,$7A
	.DB $A5,$71,$84,$79
	.DB $A3,$21,$B3,$76
	.DB $A3,$31,$A2,$77
	.DB $A3,$58,$C0,$77
	.DB $A3,$46,$05,$7A
	.DB $A3,$4A,$2A
	.DB $A3,$3A,$BF
	.DB $A3,$59,$93
	.DB $A3,$5B,$9C
	.DB $A3,$38,$1E
	.DB $75,$87,$82,$2A
	.DB $43,$48,$C2,$22
	.DB $43,$57,$C6,$27
	.DB $43,$56,$B2,$37
	.DB $43,$56,$B1,$36
	.DB $75,$86,$32,$47
	.DB $53,$66,$A3,$37
	.DB $43,$67,$A4,$67
	.DB $54,$76,$88,$77
	.DB $65,$88,$92,$88
	.DB $65,$88,$96,$88
	.DB $C8,$C4,$18,$AB
	.DB $83,$64,$B6,$B5
	
NEW_ENGLAND_ABILITIES:
	.DB $A3,$01,$07,$23,$46
	.DB $A3,$11,$33,$56,$35
	.DB $A6,$35,$92,$73
	.DB $A6,$47,$84,$74
	.DB $A5,$44,$C3,$73
	.DB $A5,$44,$47,$73
	.DB $A4,$41,$AA,$79
	.DB $A4,$41,$91,$77
	.DB $A3,$21,$8E,$77
	.DB $A3,$31,$36,$76
	.DB $A3,$68,$21,$79
	.DB $A3,$34,$42,$77
	.DB $A3,$55,$43
	.DB $A3,$27,$44
	.DB $A3,$36,$AF
	.DB $A3,$5A,$80
	.DB $A3,$27,$32
	.DB $43,$47,$A1,$27
	.DB $43,$37,$34,$22
	.DB $75,$88,$92,$48
	.DB $53,$68,$85,$46
	.DB $43,$55,$C2,$24
	.DB $43,$45,$A4,$24
	.DB $43,$45,$86,$25
	.DB $54,$76,$88,$75
	.DB $65,$87,$A3,$98
	.DB $43,$67,$99,$76
	.DB $43,$48,$8D,$44
	.DB $C8,$C4,$2E,$96
	.DB $83,$64,$15,$44
	
NEW_YORK_JETS_ABILITIES:
	.DB $A3,$11,$0C,$87,$65
	.DB $A3,$11,$09,$66,$34
	.DB $A5,$63,$AA,$74
	.DB $A5,$52,$AB,$73
	.DB $A6,$44,$90,$73
	.DB $A5,$62,$8B,$73
	.DB $A4,$61,$86,$7A
	.DB $A4,$41,$8D,$77
	.DB $A3,$21,$A1,$76
	.DB $A3,$21,$B0,$76
	.DB $A3,$38,$42,$77
	.DB $A3,$25,$43,$74
	.DB $A3,$56,$1D
	.DB $A3,$46,$41
	.DB $A3,$47,$3D
	.DB $A3,$37,$33
	.DB $A3,$37,$2A
	.DB $43,$46,$44,$24
	.DB $43,$46,$48,$24
	.DB $43,$57,$8F,$27
	.DB $43,$46,$9A,$24
	.DB $75,$8A,$21,$3A
	.DB $64,$77,$10,$76
	.DB $43,$46,$1F,$24
	.DB $43,$55,$92,$64
	.DB $43,$54,$C4,$64
	.DB $65,$88,$87,$9C
	.DB $43,$65,$8E,$75
	.DB $C8,$C4,$36,$BA
	.DB $83,$64,$2E,$AB
	
CINCINNATI_ABILITIES:
	.DB $A3,$21,$0A,$98,$AB
	.DB $A3,$11,$34,$66,$55
	.DB $A5,$84,$80,$75
	.DB $A6,$4C,$C5,$74
	.DB $A5,$54,$A3,$73
	.DB $A5,$53,$AB,$73
	.DB $A4,$41,$91,$78
	.DB $A4,$51,$C1,$78
	.DB $A3,$31,$B0,$76
	.DB $A3,$31,$12,$76
	.DB $A3,$5A,$C9,$78
	.DB $A3,$35,$18,$74
	.DB $A3,$48,$41
	.DB $A3,$49,$1E
	.DB $A3,$38,$48
	.DB $A3,$5B,$0B
	.DB $A3,$37,$4B
	.DB $43,$57,$19,$23
	.DB $43,$56,$43,$22
	.DB $43,$56,$86,$24
	.DB $64,$7A,$C0,$29
	.DB $43,$55,$96,$24
	.DB $43,$55,$24,$44
	.DB $43,$45,$8F,$45
	.DB $43,$34,$C6,$53
	.DB $43,$34,$AA,$63
	.DB $54,$77,$BD,$79
	.DB $86,$AB,$8A,$AB
	.DB $C8,$C4,$20,$94
	.DB $83,$64,$11,$6A
	
CLEVELAND_ABILITIES:
	.DB $A3,$31,$52,$6B,$76
	.DB $A3,$31,$46,$54,$55
	.DB $A6,$4D,$C0,$76
	.DB $A5,$53,$8D,$78
	.DB $A6,$34,$88,$73
	.DB $A6,$35,$C7,$73
	.DB $A4,$51,$A9,$79
	.DB $A3,$31,$B8,$77
	.DB $A3,$21,$C2,$76
	.DB $A3,$21,$22,$76
	.DB $A3,$47,$9F,$75
	.DB $A3,$25,$C6,$73
	.DB $A3,$56,$23
	.DB $A3,$47,$38
	.DB $A3,$37,$39
	.DB $A3,$46,$32
	.DB $A3,$37,$A7
	.DB $43,$57,$B1,$25
	.DB $43,$48,$A0,$22
	.DB $43,$57,$B7,$25
	.DB $53,$65,$9B,$55
	.DB $43,$55,$98,$45
	.DB $64,$7A,$80,$29
	.DB $53,$65,$4E,$25
	.DB $43,$55,$C4,$44
	.DB $54,$77,$A1,$67
	.DB $43,$56,$89,$44
	.DB $43,$55,$85,$76
	.DB $C8,$C4,$28,$54
	.DB $83,$64,$09,$32
	
HOUSTON_ABILITIES:
	.DB $A3,$21,$8B,$AB,$B9
	.DB $A3,$11,$09,$64,$56
	.DB $A5,$65,$BF,$26
	.DB $A6,$81,$89,$CB
	.DB $A5,$53,$9C,$C3
	.DB $A5,$53,$83,$C3
	.DB $A5,$71,$9B,$CB
	.DB $A6,$91,$C7,$CB
	.DB $A5,$53,$4F,$C3
	.DB $A3,$21,$9A,$C7
	.DB $A5,$71,$C4,$C9
	.DB $A3,$61,$C0,$C6
	.DB $A3,$47,$47
	.DB $A3,$49,$2C
	.DB $A3,$6A,$28
	.DB $A3,$37,$44
	.DB $A3,$37,$1E
	.DB $75,$88,$8F,$28
	.DB $43,$57,$AE,$26
	.DB $53,$78,$C8,$28
	.DB $43,$54,$A5,$45
	.DB $53,$65,$C6,$25
	.DB $43,$54,$35,$25
	.DB $75,$89,$0C,$2A
	.DB $75,$96,$96,$BB
	.DB $43,$64,$81,$87
	.DB $54,$76,$92,$86
	.DB $43,$66,$C1,$76
	.DB $C8,$C4,$2E,$54
	.DB $83,$64,$13,$A8
	
PITTSBURGH_ABILITIES:
	.DB $A3,$11,$1D,$B3,$85
	.DB $A3,$11,$42,$65,$35
	.DB $A5,$55,$13,$C6
	.DB $A5,$54,$C7,$C6
	.DB $A5,$54,$A3,$C3
	.DB $A5,$42,$C3,$C3
	.DB $A4,$41,$A5,$C8
	.DB $A3,$31,$CD,$C6
	.DB $A3,$21,$9F,$C6
	.DB $A4,$41,$8B,$C6
	.DB $A3,$49,$C0,$C6
	.DB $A3,$36,$36,$C6
	.DB $A3,$58,$A8
	.DB $A3,$56,$2A
	.DB $A3,$56,$C6
	.DB $A3,$37,$A6
	.DB $A3,$6A,$32
	.DB $53,$67,$BC,$28
	.DB $65,$78,$80,$2B
	.DB $53,$66,$93,$28
	.DB $75,$89,$96,$4A
	.DB $65,$87,$CA,$49
	.DB $53,$66,$CB,$28
	.DB $53,$66,$4B,$28
	.DB $86,$BA,$3B,$9B
	.DB $65,$88,$8F,$88
	.DB $54,$75,$B0,$86
	.DB $65,$87,$82,$79
	.DB $C8,$C4,$15,$97
	.DB $83,$64,$21,$57
	
DENVER_ABILITIES:
	.DB $A3,$31,$0E,$B4,$A7
	.DB $A3,$11,$17,$65,$45
	.DB $A5,$95,$8C,$75
	.DB $A5,$33,$83,$77
	.DB $A6,$34,$B2,$73
	.DB $A6,$36,$BC,$75
	.DB $A5,$71,$9E,$78
	.DB $A5,$61,$B0,$7A
	.DB $A3,$31,$8D,$76
	.DB $A3,$31,$21,$77
	.DB $A4,$47,$A1,$76
	.DB $A3,$26,$2F,$74
	.DB $A3,$56,$33
	.DB $A3,$56,$34
	.DB $4A,$66,$10
	.DB $A3,$38,$C0
	.DB $A3,$37,$AF
	.DB $43,$56,$88,$24
	.DB $43,$46,$43,$24
	.DB $43,$57,$9C,$24
	.DB $64,$78,$1B,$29
	.DB $53,$68,$98,$28
	.DB $43,$54,$41,$25
	.DB $75,$85,$A2,$2A
	.DB $43,$25,$80,$54
	.DB $43,$66,$8E,$74
	.DB $54,$7A,$C1,$49
	.DB $65,$87,$AB,$69
	.DB $C8,$C4,$2E,$A4
	.DB $83,$64,$0D,$CB
	
KANSAS_CITY_ABILITIES:
	.DB $A3,$01,$0F,$79,$88
	.DB $A3,$11,$40,$65,$45
	.DB $B9,$7E,$88,$72
	.DB $A7,$4B,$D2,$72
	.DB $A5,$53,$A4,$76
	.DB $A5,$35,$91,$75
	.DB $A3,$31,$33,$77
	.DB $A5,$71,$85,$7B
	.DB $A4,$51,$9E,$76
	.DB $A3,$31,$CB,$77
	.DB $A3,$27,$9C,$74
	.DB $A3,$27,$9B,$74
	.DB $A3,$5A,$36
	.DB $A3,$57,$2B
	.DB $A3,$38,$47
	.DB $A3,$2C,$1F
	.DB $A3,$3A,$27
	.DB $53,$66,$48,$26
	.DB $45,$38,$0B,$28
	.DB $64,$79,$B7,$28
	.DB $86,$9A,$8E,$2C
	.DB $64,$79,$43,$28
	.DB $75,$88,$A1,$47
	.DB $53,$67,$84,$26
	.DB $54,$76,$B2,$86
	.DB $54,$78,$86,$7A
	.DB $43,$65,$8F,$77
	.DB $43,$65,$B8,$55
	.DB $C8,$C4,$31,$CC
	.DB $83,$64,$09,$49
	
LOS_ANGELES_RAIDERS_ABILITIES:
	.DB $A3,$11,$11,$A4,$69
	.DB $A3,$11,$10,$65,$45
	.DB $A5,$B4,$9A,$C2
	.DB $A5,$83,$8B,$74
	.DB $A6,$37,$8D,$74
	.DB $A6,$45,$A6,$72
	.DB $A5,$71,$86,$99
	.DB $A6,$91,$84,$78
	.DB $A6,$81,$B0,$77
	.DB $A6,$91,$CB,$72
	.DB $A3,$67,$C0,$76
	.DB $A3,$25,$1E,$73
	.DB $A3,$47,$1F
	.DB $A3,$6A,$32
	.DB $A3,$48,$24
	.DB $A3,$77,$C9
	.DB $A3,$37,$99
	.DB $75,$89,$93,$4A
	.DB $43,$4A,$49,$38
	.DB $75,$8A,$4F,$4A
	.DB $53,$65,$96,$23
	.DB $53,$69,$27,$39
	.DB $43,$55,$26,$63
	.DB $43,$55,$8A,$63
	.DB $65,$86,$9B,$57
	.DB $65,$86,$CA,$57
	.DB $75,$9A,$AD,$79
	.DB $43,$67,$C6,$77
	.DB $C8,$C4,$17,$88
	.DB $83,$64,$1B,$45
	
SAN_DIEGO_ABILITIES:
	.DB $A3,$11,$13,$C4,$46
	.DB $A3,$11,$31,$65,$35
	.DB $A5,$95,$90,$73
	.DB $A6,$36,$82,$72
	.DB $A5,$36,$14,$73
	.DB $A5,$43,$BC,$77
	.DB $A4,$41,$AA,$76
	.DB $A5,$61,$97,$7A
	.DB $A3,$31,$B0,$76
	.DB $A4,$41,$89,$76
	.DB $A3,$47,$84,$75
	.DB $A3,$29,$A1,$74
	.DB $A3,$48,$8F
	.DB $A3,$57,$AD
	.DB $A3,$3A,$1D
	.DB $A3,$39,$30
	.DB $A3,$38,$C7
	.DB $64,$77,$1E,$29
	.DB $53,$68,$4F,$26
	.DB $64,$78,$B7,$28
	.DB $75,$89,$A2,$2A
	.DB $43,$56,$9E,$25
	.DB $53,$6A,$24,$26
	.DB $43,$55,$80,$47
	.DB $65,$85,$93,$76
	.DB $75,$97,$CB,$AB
	.DB $54,$76,$8E,$66
	.DB $43,$68,$C6,$66
	.DB $C8,$C4,$1E,$B7
	.DB $83,$64,$40,$A8
	
SEATTLE_ABILITIES:
	.DB $A3,$11,$17,$3A,$AA
	.DB $A3,$11,$12,$65,$55
	.DB $A6,$35,$91,$79
	.DB $A8,$3B,$92,$73
	.DB $A5,$54,$A2,$73
	.DB $A5,$54,$C1,$73
	.DB $A4,$41,$98,$77
	.DB $A4,$51,$9B,$78
	.DB $A3,$31,$03,$76
	.DB $A4,$51,$34,$76
	.DB $A3,$26,$21,$74
	.DB $A3,$36,$A7,$74
	.DB $A3,$48,$1B
	.DB $A3,$56,$95
	.DB $A3,$47,$4B
	.DB $A3,$67,$2B
	.DB $A3,$38,$32
	.DB $53,$67,$A5,$28
	.DB $43,$56,$51,$24
	.DB $75,$98,$89,$2A
	.DB $53,$66,$81,$28
	.DB $43,$58,$9C,$26
	.DB $43,$55,$13,$25
	.DB $43,$55,$C0,$23
	.DB $43,$55,$92,$56
	.DB $54,$74,$96,$77
	.DB $43,$55,$C9,$75
	.DB $54,$78,$8D,$38
	.DB $C8,$C4,$2A,$65
	.DB $83,$64,$36,$69
	
WASHINGTON_ABILITIES:
	.DB $A3,$01,$21,$56,$65
	.DB $A3,$11,$1F,$65,$45
	.DB $A5,$73,$A2,$C5
	.DB $A6,$81,$C5,$C8
	.DB $A6,$4C,$BF,$C2
	.DB $A5,$62,$AE,$C5
	.DB $A5,$65,$85,$C9
	.DB $A5,$71,$C4,$CB
	.DB $A5,$54,$C7,$C3
	.DB $A3,$31,$C1,$C6
	.DB $A3,$25,$39,$C4
	.DB $A3,$35,$83,$C4
	.DB $A3,$5A,$1C
	.DB $A3,$58,$38
	.DB $A3,$58,$2B
	.DB $A3,$4A,$34
	.DB $A3,$39,$B5
	.DB $53,$66,$43,$25
	.DB $43,$57,$96,$26
	.DB $64,$78,$97,$29
	.DB $43,$57,$B4,$47
	.DB $43,$56,$0C,$24
	.DB $43,$57,$8E,$26
	.DB $53,$65,$AD,$27
	.DB $86,$B6,$B1,$64
	.DB $75,$94,$86,$A5
	.DB $43,$66,$C3,$74
	.DB $43,$64,$B0,$64
	.DB $C8,$C4,$33,$7C
	.DB $83,$64,$20,$37
	
NEW_YORK_GIANTS_ABILITIES:
	.DB $A3,$11,$34,$79,$9C
	.DB $A3,$31,$19,$54,$52
	.DB $A8,$7D,$93,$B4
	.DB $A5,$82,$B0,$B7
	.DB $A6,$36,$96,$73
	.DB $A5,$45,$B2,$95
	.DB $A6,$81,$91,$97
	.DB $A6,$81,$A3,$A8
	.DB $A3,$31,$C9,$76
	.DB $A3,$31,$C3,$76
	.DB $A3,$4A,$1A,$A6
	.DB $A3,$28,$B0,$84
	.DB $A3,$57,$1F
	.DB $A3,$48,$AF
	.DB $A3,$49,$C0
	.DB $A3,$3B,$2B
	.DB $A3,$47,$33
	.DB $43,$58,$89,$28
	.DB $43,$57,$51,$27
	.DB $43,$57,$C1,$26
	.DB $86,$AB,$CF,$4C
	.DB $65,$8A,$9C,$4A
	.DB $53,$65,$26,$96
	.DB $65,$79,$95,$28
	.DB $65,$84,$C4,$96
	.DB $65,$87,$8A,$69
	.DB $54,$78,$A1,$68
	.DB $54,$78,$B8,$88
	.DB $C8,$C4,$20,$69
	.DB $83,$64,$1C,$CC
	
PHILADELPHIA_ABILITIES:
	.DB $A3,$81,$D4,$9A,$99
	.DB $A3,$01,$1B,$55,$55
	.DB $A5,$45,$8F,$7A
	.DB $A5,$55,$CD,$44
	.DB $A5,$45,$C5,$73
	.DB $A5,$54,$85,$73
	.DB $A4,$51,$86,$78
	.DB $A4,$41,$89,$77
	.DB $A4,$41,$9F,$76
	.DB $A3,$31,$9C,$76
	.DB $A3,$79,$CE,$79
	.DB $A3,$27,$21,$73
	.DB $A3,$45,$33
	.DB $A3,$27,$44
	.DB $A3,$25,$48
	.DB $A3,$37,$4B
	.DB $A3,$37,$8A
	.DB $64,$77,$9B,$2A
	.DB $43,$57,$2E,$46
	.DB $75,$8A,$99,$4B
	.DB $43,$56,$8C,$26
	.DB $75,$8A,$8D,$29
	.DB $43,$56,$C7,$46
	.DB $64,$79,$B1,$4B
	.DB $75,$67,$C4,$7A
	.DB $75,$54,$C6,$79
	.DB $43,$27,$96,$84
	.DB $43,$24,$8B,$32
	.DB $C8,$C4,$17,$73
	.DB $83,$64,$16,$74
	
PHOENIX_ABILITIES:
	.DB $A3,$21,$3A,$46,$54
	.DB $A3,$11,$21,$65,$45
	.DB $A5,$75,$3D,$75
	.DB $A5,$61,$C7,$78
	.DB $A5,$55,$4F,$73
	.DB $A6,$53,$8A,$74
	.DB $A3,$21,$4E,$7A
	.DB $A4,$51,$A2,$78
	.DB $A5,$55,$A8,$73
	.DB $A3,$31,$C9,$77
	.DB $A3,$26,$C0,$75
	.DB $A3,$25,$32,$73
	.DB $A3,$45,$09
	.DB $A3,$38,$B9
	.DB $A3,$45,$BC
	.DB $A3,$79,$97
	.DB $A3,$38,$95
	.DB $43,$57,$A7,$27
	.DB $43,$56,$1E,$26
	.DB $64,$78,$CD,$28
	.DB $64,$89,$CB,$29
	.DB $43,$54,$43,$46
	.DB $43,$45,$A1,$25
	.DB $43,$45,$8D,$46
	.DB $43,$52,$96,$74
	.DB $43,$45,$AA,$66
	.DB $4A,$66,$8F,$86
	.DB $65,$88,$CB,$8A
	.DB $C8,$C4,$2F,$28
	.DB $83,$64,$1B,$BC
	
DALLAS_ABILITIES:
	.DB $A3,$11,$16,$76,$77
	.DB $A3,$11,$05,$65,$45
	.DB $A5,$84,$C6,$75
	.DB $A5,$36,$C9,$76
	.DB $A5,$55,$9C,$76
	.DB $A5,$45,$A3,$73
	.DB $A4,$51,$96,$78
	.DB $A5,$61,$A1,$77
	.DB $A3,$31,$AA,$76
	.DB $A4,$41,$86,$76
	.DB $A3,$6A,$50,$7A
	.DB $A3,$28,$1E,$74
	.DB $A3,$55,$2C
	.DB $A3,$47,$4B
	.DB $A3,$46,$4C
	.DB $A3,$28,$2F
	.DB $A3,$3B,$CD
	.DB $43,$57,$C0,$28
	.DB $53,$67,$44,$27
	.DB $54,$78,$A0,$2A
	.DB $53,$65,$A0,$46
	.DB $64,$78,$A4,$28
	.DB $44,$78,$D1,$2A
	.DB $43,$55,$43,$26
	.DB $75,$97,$AD,$67
	.DB $65,$88,$91,$79
	.DB $54,$78,$A9,$65
	.DB $54,$77,$C1,$75
	.DB $C8,$C4,$42,$66
	.DB $83,$64,$20,$8B
	
CHICAGO_ABILITIES:
	.DB $A3,$11,$1D,$63,$83
	.DB $A3,$11,$1F,$64,$45
	.DB $A6,$3E,$40,$78
	.DB $A7,$97,$88,$77
	.DB $A5,$43,$A1,$73
	.DB $A5,$83,$99,$75
	.DB $A4,$41,$B7,$77
	.DB $A4,$41,$91,$77
	.DB $A3,$21,$4C,$76
	.DB $A3,$21,$9C,$77
	.DB $A3,$39,$21,$73
	.DB $A3,$26,$33,$74
	.DB $A3,$79,$48
	.DB $A3,$6A,$3F
	.DB $A3,$57,$36
	.DB $A3,$47,$51
	.DB $A3,$47,$13
	.DB $64,$79,$A5,$6B
	.DB $45,$2A,$CE,$28
	.DB $64,$79,$4F,$2A
	.DB $43,$56,$0C,$46
	.DB $43,$58,$2A,$29
	.DB $75,$8B,$A6,$2C
	.DB $43,$56,$1E,$46
	.DB $65,$87,$C4,$A8
	.DB $54,$76,$C1,$99
	.DB $65,$87,$C9,$CA
	.DB $43,$66,$A2,$86
	.DB $C8,$C4,$32,$57
	.DB $83,$64,$23,$43
	
DETROIT_ABILITIES:
	.DB $A3,$41,$AB,$56,$43
	.DB $A3,$31,$92,$65,$46
	.DB $A5,$A3,$9B,$A6
	.DB $A3,$21,$AD,$77
	.DB $A6,$43,$98,$73
	.DB $A5,$82,$86,$77
	.DB $A3,$21,$B8,$7B
	.DB $A5,$61,$A1,$7A
	.DB $A5,$51,$CD,$74
	.DB $A3,$31,$21,$76
	.DB $A4,$41,$A4,$76
	.DB $A3,$31,$D1,$76
	.DB $A3,$46,$AF
	.DB $A3,$47,$1B
	.DB $A3,$45,$24
	.DB $A3,$58,$8D
	.DB $A3,$37,$0C
	.DB $43,$58,$23,$28
	.DB $64,$6A,$A7,$2A
	.DB $43,$34,$C7,$24
	.DB $75,$87,$BF,$48
	.DB $43,$44,$44,$23
	.DB $64,$78,$30,$27
	.DB $43,$43,$96,$23
	.DB $43,$33,$BE,$57
	.DB $54,$77,$A2,$77
	.DB $43,$57,$B0,$65
	.DB $65,$88,$C0,$88
	.DB $C8,$C4,$2E,$47
	.DB $83,$64,$07,$78
	
GREEN_BAY_ABILITIES:
	.DB $A3,$31,$3F,$57,$77
	.DB $A3,$11,$08,$65,$45
	.DB $A5,$64,$86,$74
	.DB $A5,$3E,$98,$73
	.DB $A5,$54,$9D,$72
	.DB $A5,$53,$8B,$75
	.DB $A5,$71,$96,$7B
	.DB $A4,$41,$82,$77
	.DB $A3,$31,$A4,$77
	.DB $A4,$41,$39,$77
	.DB $A3,$47,$C2,$75
	.DB $A3,$36,$9A,$74
	.DB $A3,$55,$2F
	.DB $A3,$56,$30
	.DB $A3,$37,$0C
	.DB $A3,$46,$33
	.DB $A3,$29,$3A
	.DB $43,$55,$A8,$26
	.DB $A3,$58,$31,$28
	.DB $43,$56,$09,$26
	.DB $75,$87,$99,$29
	.DB $43,$44,$C6,$43
	.DB $43,$44,$4F,$24
	.DB $43,$44,$87,$54
	.DB $43,$65,$83,$75
	.DB $43,$55,$C9,$44
	.DB $43,$56,$42,$54
	.DB $43,$66,$37,$75
	.DB $C8,$C4,$23,$85
	.DB $83,$64,$2C,$37
	
MINNESOTA_ABILITIES:
	.DB $A3,$11,$21,$66,$65
	.DB $A3,$11,$22,$35,$34
	.DB $A5,$69,$80,$76
	.DB $A5,$55,$2B,$73
	.DB $A5,$44,$8B,$73
	.DB $A5,$44,$8D,$73
	.DB $A4,$41,$C0,$79
	.DB $A6,$81,$9F,$7B
	.DB $A3,$21,$C6,$76
	.DB $A4,$41,$8F,$77
	.DB $A3,$69,$B7,$78
	.DB $A3,$27,$CD,$73
	.DB $A3,$59,$0B
	.DB $A3,$7A,$C2
	.DB $A3,$37,$2A
	.DB $A3,$4A,$41
	.DB $A3,$37,$2B
	.DB $64,$7A,$94,$4A
	.DB $53,$67,$B9,$29
	.DB $43,$57,$31,$48
	.DB $64,$78,$AB,$6A
	.DB $75,$8A,$1E,$2C
	.DB $43,$44,$29,$24
	.DB $43,$44,$2F,$24
	.DB $54,$75,$CB,$67
	.DB $75,$98,$88,$7A
	.DB $54,$76,$B0,$56
	.DB $75,$98,$AA,$AA
	.DB $C8,$C4,$13,$69
	.DB $83,$64,$20,$36
	
TAMPA_BAY_ABILITIES:
	.DB $A3,$41,$23,$48,$66
	.DB $A3,$11,$42,$65,$45
	.DB $A5,$73,$CC,$77
	.DB $A6,$3E,$C7,$76
	.DB $A5,$44,$80,$73
	.DB $A5,$53,$97,$73
	.DB $A5,$61,$B0,$79
	.DB $A3,$31,$9C,$77
	.DB $A3,$21,$85,$76
	.DB $A4,$41,$B8,$76
	.DB $A3,$56,$32,$76
	.DB $A3,$46,$C0,$74
	.DB $A3,$54,$48
	.DB $A3,$35,$0C
	.DB $A3,$36,$AF
	.DB $A3,$37,$1C
	.DB $A3,$35,$45
	.DB $43,$54,$43,$26
	.DB $43,$47,$C8,$26
	.DB $53,$47,$C1,$25
	.DB $43,$54,$8E,$23
	.DB $43,$44,$CD,$45
	.DB $43,$44,$C0,$23
	.DB $43,$55,$B4,$28
	.DB $86,$B6,$C9,$BA
	.DB $43,$54,$C4,$75
	.DB $43,$66,$89,$87
	.DB $54,$77,$AA,$86
	.DB $C8,$C4,$11,$AB
	.DB $83,$64,$4A,$5A
	
SAN_FRANCISCO_ABILITIES:
	.DB $A3,$21,$01,$8C,$CB
	.DB $A3,$31,$33,$86,$78
	.DB $A5,$73,$D0,$76
	.DB $A6,$3E,$32,$78
	.DB $A5,$62,$97,$75
	.DB $A5,$63,$A0,$74
	.DB $A5,$71,$C9,$9A
	.DB $A6,$A1,$A3,$CC
	.DB $A3,$31,$C0,$76
	.DB $A5,$61,$85,$77
	.DB $A3,$5A,$43,$7A
	.DB $A3,$25,$BE,$74
	.DB $A3,$59,$82
	.DB $A3,$47,$AC
	.DB $A3,$38,$1F
	.DB $A3,$2A,$AE
	.DB $A3,$49,$AF
	.DB $43,$57,$38,$26
	.DB $43,$5A,$9C,$28
	.DB $64,$7A,$2A,$27
	.DB $64,$77,$4F,$29
	.DB $43,$56,$0C,$26
	.DB $53,$79,$1C,$49
	.DB $75,$89,$B7,$2B
	.DB $54,$75,$8A,$77
	.DB $43,$66,$8E,$56
	.DB $86,$AA,$AB,$7B
	.DB $75,$97,$D1,$A9
	.DB $C8,$C4,$21,$88
	.DB $83,$64,$0C,$25
	
LOS_ANGELES_RAMS_ABILITIES:
	.DB $A3,$11,$25,$89,$76
	.DB $A3,$11,$15,$65,$45
	.DB $A5,$75,$94,$55
	.DB $A5,$54,$83,$73
	.DB $A5,$63,$81,$73
	.DB $A5,$64,$8D,$77
	.DB $A6,$81,$BD,$7C
	.DB $A6,$81,$8B,$7B
	.DB $A3,$31,$B8,$76
	.DB $A4,$41,$8E,$76
	.DB $A3,$28,$43,$78
	.DB $A3,$26,$B0,$74
	.DB $A3,$59,$0C
	.DB $A3,$47,$31
	.DB $A3,$38,$1F
	.DB $A3,$39,$A6
	.DB $A3,$49,$C1
	.DB $43,$55,$C0,$24
	.DB $43,$57,$8F,$24
	.DB $43,$56,$88,$26
	.DB $43,$55,$9C,$24
	.DB $43,$55,$B2,$23
	.DB $43,$54,$1E,$23
	.DB $75,$8A,$43,$2A
	.DB $54,$74,$C4,$84
	.DB $43,$54,$A1,$55
	.DB $43,$46,$9E,$64
	.DB $54,$74,$96,$86
	.DB $C8,$C4,$47,$23
	.DB $83,$64,$4C,$27
	
NEW_ORLEANS_ABILITIES:
	.DB $A3,$11,$26,$65,$77
	.DB $A3,$11,$28,$66,$45
	.DB $A6,$3E,$B8,$74
	.DB $A5,$73,$C3,$73
	.DB $A5,$63,$C1,$74
	.DB $A5,$63,$34,$74
	.DB $A4,$51,$CB,$7A
	.DB $A3,$31,$C7,$77
	.DB $A3,$21,$B7,$76
	.DB $A4,$41,$9A,$76
	.DB $A3,$26,$46,$75
	.DB $A3,$25,$13,$74
	.DB $A3,$67,$1C
	.DB $A3,$4A,$1F
	.DB $A3,$47,$2F
	.DB $A3,$38,$4E
	.DB $A3,$6A,$39
	.DB $64,$79,$96,$29
	.DB $64,$78,$AC,$2A
	.DB $43,$56,$99,$26
	.DB $64,$79,$AA,$29
	.DB $64,$79,$C8,$24
	.DB $53,$67,$83,$24
	.DB $43,$55,$CC,$28
	.DB $43,$55,$AB,$65
	.DB $54,$76,$95,$87
	.DB $43,$56,$8D,$67
	.DB $54,$76,$90,$65
	.DB $C8,$C4,$27,$8A
	.DB $83,$64,$44,$96
	
ATLANTA_ABILITIES:
	.DB $A3,$11,$33,$46,$74
	.DB $A3,$11,$28,$55,$45
	.DB $A5,$73,$C7,$74
	.DB $A3,$31,$92,$77
	.DB $A5,$53,$9F,$74
	.DB $A5,$54,$99,$73
	.DB $A3,$31,$8D,$77
	.DB $A6,$91,$D3,$7B
	.DB $A5,$47,$C6,$73
	.DB $A4,$41,$8F,$76
	.DB $A6,$71,$86,$77
	.DB $A3,$34,$98,$74
	.DB $A3,$27,$A7
	.DB $A3,$26,$B2
	.DB $A3,$67,$09
	.DB $A3,$45,$1E
	.DB $A3,$4A,$B2
	.DB $43,$57,$10,$28
	.DB $43,$58,$AC,$26
	.DB $64,$77,$43,$28
	.DB $43,$55,$C9,$24
	.DB $43,$55,$12,$24
	.DB $53,$65,$AA,$27
	.DB $43,$55,$9C,$24
	.DB $86,$B8,$9E,$87
	.DB $43,$44,$8A,$73
	.DB $43,$54,$46,$73
	.DB $43,$36,$8B,$72
	.DB $C8,$C4,$21,$37
	.DB $83,$64,$0C,$9A
	
_F}_PLAYER_ABILITIES
	
.PAD $C000, $FF	
