
.BASE $A000

_F{_DEFENSE_PLAY_POINTERS

DEFENSE_PLAY_POINTERS:

.INCBIN "TSB.nes", $6010, $15EA

_F}_DEFENSE_PLAY_POINTERS

.PAD $B600,$FF

_F{_DEFENSE_SPECIAL_PLAY_POINTERS

DEFENSE_SPECIAL_PLAY_POINTERS:

DEFENSIVE_PLAYERS_CRY_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7610, $18

DEFENSE_INTERCEPTION_RETURN_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7628, $18

DEFENSE_RECOVER_ONSIDE_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7640, $18

DEFENSE_RECOVER_FUMBLE_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7658, $18

DEFENSE_PUNT_RETURN_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7670, $18

DEFENSE_ONSIDE_KICK_RETURN_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7688, $18
	
UNUSED_1_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $76A0, $18	

DEFENSE_FUMBLE_RETURN_PLAY_POINTERS:

	.INCBIN "TSB.nes", $76B8, $18

DEFENSE_RECOVERED_FUMBLE_PLAY_POINTERS:	

	.INCBIN "TSB.nes", $76D0, $18

UNUSED_2_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $76E8, $18

UNUSED_3_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7700, $18
	
DEFENSIVE_PLAYERS_CHEER_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7718, $18
	
UNUSED_4_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7730, $18
	
UNUSED_5_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7748, $18

DEFENSE_CHASE_BALL_CARRIER_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7760, $18

UNUSED_6_DEFENSE_SPECIAL_PLAY_POINTERS:

	.INCBIN "TSB.nes", $7778, $18

_F}_DEFENSE_SPECIAL_PLAY_POINTERS	
	
	.PAD $C000, $FF

	