;.ORG $0000 

_F{_BANK_IDS

.ENUM $00

PLAYER_NAMES_BANK 							.dsb 1
PLAYER_NAMES_ATTRIBS_BANK 					.dsb 1

FORMATION_OFF_PLAY_POINTERS_BANK 			.dsb 0
METATILE_BACKGROUNDS_BANK					.dsb 1

DEF_PLAY_POINTERS_BANK 						.dsb 0
DEF_SPECIAL_PLAY_POINTERS_BANK 				.dsb 1

OFF_PLAYER_SCRIPTS_BANK						.dsb 1
DEF_PLAYER_SCRIPTS_BANK						.dsb 1

CUTSCENE_DRAW_SCRIPT_BANK					.dsb 1
LEADERS_SCOREBOARD_SCHED_DRAW_SCRIPT_BANK	.dsb 1
SPRITE_SCRIPTS_1_BANK						.dsb 1
SPRITE_SCRIPTS_2_BANK						.dsb 1
METATILE_TILES_1_BANK						.dsb 1
METATILE_TILES_2_BANK						.dsb 0

SIM_LOGIC_STATS_1_BANK						.dsb 1
SIM_LOGIC_STATS_2_BANK						.dsb 1

PALLETE_DATA_BANK							.dsb 0
THROWN_PLAYER_ANI_SCRIPT_BANK				.dsb 1

PLAYER_FACES_DATA_BANK						.dsb 0
TEAM_DEFAULT_PLAYBOOKS_BANK					.dsb 0	
PLAY_NAME_AND_REACTIONS_BANK				.dsb 0
COM_BOOST_BANK								.dsb 1

DRAW_ROSTER_SCRIPT_BANK						.dsb 0 			
DRAW_SCHEDULE_SCRIPT_BANK					.dsb 0 
MENU_DRAW_SCRIPT_BANK						.dsb 0
TEAM_NAME_CITY_DATA_BANK					.dsb 0
MESSAGE_BAR_DRAW_SCRIPT_BANK				.dsb 1

MAIN_GAME_BANK_1							.dsb 1
MAIN_GAME_BANK_2							.dsb 1

HIGH_LEVEL_GAME_LOGIC_BANK_1				.dsb 1
HIGH_LEVEL_GAME_LOGIC_BANK_2				.dsb 0
PLAY_CALL_SCREEN_BANK						.dsb 1 

PLAYER_SCRIPT_COMMANDS_LOGIC_BANK_1			.dsb 1
PLAYER_SCRIPT_COMMANDS_LOGIC_BANK_2			.dsb 1

SET_TEAM_UNIFORM_COLORS_BANK				.dsb 0 
DRAW_METATILE_BANK							.dsb 0
DRAW_GAME_FIELD_BANK						.dsb 0
COLLISION_LOGIC_BANK						.dsb 0
SPRITE_FLICKERING_LOGIC_BANK				.dsb 0			
BANNER_ANIMATION_BANK						.dsb 0
BALL_ANIMATION_BANK							.dsb 1

DRAW_SCRIPT_PROCESSING_BANK					.dsb 1

NFL_LEADERS_BANK							.dsb 0
DRAW_PRO_BOWL_POSITION_BANK					.dsb 0
DRAW_PLAYER_ATTRIBUTES_BANK					.dsb 1

DRAW_SCHEDULE_BANK							.dsb 0
RESET_SCHEDULE_BANK							.dsb 0			
SET_DEFAULT_PLAYBOOK_STARTERS_BANK			.dsb 0
CLEAR_SEASON_STATS_BANK						.dsb 0
DRAW_TEAM_DATA_SCREEN_BANK					.dsb 0
DRAW_DEFENSIVE_STARTERS_BANK				.dsb 0 
DRAW_TEAM_CONTROL_SCREEN_BANK				.dsb 0
GET_TEAM_PASS_RUSH_YARDS_BANK				.dsb 0
GET_RECOVERY_TYPE_BANK						.dsb 0
ADJUST_FINAL_PLAYER_LOCATION_ON_PASS_BANK	.dsb 1

SOUND_MODE_SCREEN_BANK						.dsb 0
SET_CUTSCENE_UNI_COLORS_BANK				.dsb 0
SET_COM_JUICE_VALUES_BANK					.dsb 0
INITIALIZE_PLAYERS_BANK						.dsb 0
SET_PLAYER_SKILLS_IN_RAM_BANK				.dsb 0
CRASH_HANDLER_BANK							.dsb 1

SOUND_ENGINE_BANK							.dsb 1
SONG_EFFECTS_DATA_BANK_1					.dsb 1
SONG_EFFECTS_DATA_BANK_2					.dsb 1

FIXED_MAIN_FUNCTIONS_BANK					.dsb 1
DMC_SAMPLES_BANK							.dsb 1

.ENDE

_F}_BANK_IDS
