_F{_COIN_TOSS_BG_TEXT_PPU_LOCATIONS

P1_TEAM_CITY_COIN_TOSS_PPU_ADDR				= $2262
P2_TEAM_CITY_COIN_TOSS_PPU_ADDR				= P1_TEAM_CITY_COIN_TOSS_PPU_ADDR + $10 

P1_TEAM_MASCOT_COIN_TOSS_PPU_ADDR			= $2284
P2_TEAM_MASCOT_COIN_TOSS_PPU_ADDR			= P1_TEAM_MASCOT_COIN_TOSS_PPU_ADDR + $10

P1_CONTROL_TYPE_COIN_TOSS_PPU_ADDR			= $22C7
P2_CONTROL_TYPE_COIN_TOSS_PPU_ADDR			= P1_CONTROL_TYPE_COIN_TOSS_PPU_ADDR + $10

_F}_COIN_TOSS_BG_TEXT_PPU_LOCATIONS