_F{_CUTSCENE_SEQUENCE_IDS

.ENUM $01
	
	PUNT_CUT_SEQ_INDEX                             .dsb 1; 0X01 PUNT
	MISSED_PUNT_BLOCK_CUT_SEQ_INDEX                .dsb 1; 0X02 MISSED PUNT BLOCK
	PUNT_BLOCK_CUT_SEQ_INDEX                       .dsb 1; 0X03 PUNT BLOCKED
	UNUSED_CUT_SEQ_INDEX                           .dsb 1; 0X04 BLACK SCREEN, RETURN
	
	QB_SACK_CUT_SEQ_INDEX                          .dsb 1; 0X05 QB SACK
	QB_SACK_SIDE_CHANGE_CUT_SEQ_INDEX              .dsb 1; 0X06 QB SACK WITH SIDE CHANGE
	QB_SAFETY_CUT_SEQ_INDEX                        .dsb 1; 0X07 QB SACK WITH SAFETY
	MISSED_PASS_BLOCK_CUT_SEQ_INDEX                .dsb 1; 0X08 PASS WITH MISSED PASS BLOCK
	MISSED_PASS_BLOCK_DUPE_CUT_SEQ_INDEX           .dsb 1; 0X09 PASS WITH MISSED PASS BLOCK
	PASS_BLOCKED_CUT_SEQ_INDEX                     .dsb 1; 0X0A PASS WITH PASS BLOCKED
	
	P2_FG_MISS_BLOCK_DOWN_MIDDLE_CUT_SEQ_INDEX     .dsb 1; 0X0B P2 FG, MISSED BLOCK, THRU UPRIGHTS
	P2_FG_MISS_BLOCK_DOWN_MIDDLE_DUPE_CUT_SEQ_INDEX     .dsb 1; 0X0C P2 FG, THRU UPRIGHTS
	P2_FG_DOWN_MIDDLE_CUT_SEQ_INDEX                .dsb 1; 0X0D P2 FG, THRU UPRIGHTS 
	P2_XP_MISSED_BLOCK_DOWN_MIDDLE_CUT_SEQ_INDEX   .dsb 1; 0X0E P2 XP, MISSED BLOCK, GOOD 
	P2_XP_DOWN_MIDDLE_CUT_SEQ_INDEX                .dsb 1; 0X0F P2 XP, GOOD
	FG_BLOCKED_CUT_SEQ_INDEX                       .dsb 1; 0X10 FG BLOCKED
	
	P1_FG_MISS_BLOCK_DOWN_MIDDLE_CUT_SEQ_INDEX     .dsb 1; 0X11 P1 FG, MISSED BLOCK, THRU UPRIGHTS
	P1_FG_MISS_BLOCK_LEFT_UR_GOOD_CUT_SEQ_INDEX    .dsb 1; 0X12 P1 FG, MISSED BLOCK, HIT LEFT UPRIGHT, GOOD
	P1_FG_MISS_BLOCK_RIGHT_UR_GOOD_CUT_SEQ_INDEX   .dsb 1; 0X13 P1 FG, MISSED BLOCK, HIT RIGHT UPRIGHT, GOOD
	P2_FG_MISS_BLOCK_RIGHT_UR_GOOD_CUT_SEQ_INDEX   .dsb 1; 0X14 P2 FG, MISSED BLOCK, HIT RIGHT UPRIGHT, GOOD
	P2_FG_MISS_BLOCK_LEFT_UR_GOOD_CUT_SEQ_INDEX    .dsb 1; 0X15 P2 FG, MISSED BLOCK, HIT LEFT UPRIGHT, GOOD
	P1_FG_MISS_BLOCK_LEFT_UR_MISS_CUT_SEQ_INDEX    .dsb 1; 0X16 P1 FG, MISSED BLOCK, HIT LEFT UPRIGHT, MISS
	P1_FG_MISS_BLOCK_RIGHT_UR_MISS_CUT_SEQ_INDEX   .dsb 1; 0X17 P1 FG, MISSED BLOCK, HIT RIGHT UPRIGHT, MISS
	P1_FG_MISS_BLOCK_WIDE_LEFT_CUT_SEQ_INDEX       .dsb 1; 0X18 P1 FG, MISSED BLOCK, WIDE LEFT MISS
	P1_FG_MISS_BLOCK_WIDE_RIGHT_CUT_SEQ_INDEX      .dsb 1; 0X19 P1 FG, MISSED BLOCK, WIDE RIGHT MISS
	P1_FG_MISS_BLOCK_SHORT_CUT_SEQ_INDEX           .dsb 1; 0X1A P1 FG, MISSED BLOCK, SHORT
	P2_FG_MISS_BLOCK_RIGHT_UR_MISS_CUT_SEQ_INDEX   .dsb 1; 0X1B P2 FG, MISSED BLOCK, HIT RIGHT UPRIGHT, MISS
	P2_FG_MISS_BLOCK_LEFT_UR_MISS_CUT_SEQ_INDEX    .dsb 1; 0X1C P2 FG, MISSED BLOCK, HIT LEFT UPRIGHT, MISS
	P2_FG_MISS_BLOCK_WIDE_RIGHT_CUT_SEQ_INDEX      .dsb 1; 0X1D P2 FG, MISSED BLOCK, WIDE RIGHT MISS
	P2_FG_MISS_BLOCK_WIDE_LEFT_CUT_SEQ_INDEX       .dsb 1; 0X1E P2 FG, MISSED BLOCK, WIDE LEFT MISS
	P2_FG_MISS_BLOCK_SHORT_CUT_SEQ_INDEX           .dsb 1; 0X1F P2 FG, MISSED BLOCK, SHORT
	
	P1_FG_DOWN_MIDDLE_CUT_SEQ_INDEX                .dsb 1; 0X20 P1 FG, THRU UPRIGHTS
	P1_FG_LEFT_UR_GOOD_CUT_SEQ_INDEX               .dsb 1; 0X21 P1 FG, HIT LEFT UPRIGHT, GOOD
	P1_FG_RIGHT_UR_GOOD_CUT_SEQ_INDEX              .dsb 1; 0X22 P1 FG, HIT RIGHT UPRIGHT, GOOD
	P2_FG_RIGHT_UR_GOOD_CUT_SEQ_INDEX              .dsb 1; 0X23 P2 FG, HIT RIGHT UPRIGHT, GOOD
	P2_FG_LEFT_UR_GOOD_CUT_SEQ_INDEX               .dsb 1; 0X24 P2 FG, HIT LEFT UPRIGHT, GOOD
	P1_FG_LEFT_UR_MISS_CUT_SEQ_INDEX               .dsb 1; 0X25 P1 FG, HIT LEFT UPRIGHT, MISS
	P1_FG_RIGHT_UR_MISS_CUT_SEQ_INDEX              .dsb 1; 0X26 P1 FG, HIT RIGHT UPRIGHT, MISS
	P1_FG_WIDE_LEFT_CUT_SEQ_INDEX                  .dsb 1; 0X27 P1 FG, WIDE LEFT MISS     
	P1_FG_WIDE_RIGHT_CUT_SEQ_INDEX                 .dsb 1; 0X28 P1 FG, WIDE RIGHT MISS
	P1_FG_SHORT_CUT_SEQ_INDEX                      .dsb 1; 0X29 P1 FG, SHORT
	P2_FG_RIGHT_UR_MISS_CUT_SEQ_INDEX              .dsb 1; 0X2A P2 FG, HIT RIGHT UPRIGHT, MISS
	P2_FG_LEFT_UR_MISS_CUT_SEQ_INDEX               .dsb 1; 0X2B P2 FG, HIT LEFT UPRIGHT, MISS
	P2_FG_WIDE_RIGHT_CUT_SEQ_INDEX                 .dsb 1; 0X2C P2 FG, WIDE RIGHT MISS
	P2_FG_WIDE_LEFT_CUT_SEQ_INDEX                  .dsb 1; 0X2D P2 FG, WIDE LEFT MISS
	P2_FG_SHORT_CUT_SEQ_INDEX                      .dsb 1; 0X2E P2 FG, SHORT
	XP_FG_FG_BLOCK_CUT_SEQ_INDEX                   .dsb 1; 0X2F XP/FG ATT, BLOCK
	XP_FG_FG_BLOCK_DUPE_CUT_SEQ_INDEX               .dsb 1; 0X30 XP/FG ATT, BLOCK

	P1_XP_MISS_BLOCK_GOOD_CUT_SEQ_INDEX            .dsb 1; 0X31 P1 XP ATT, MISSED BLOCK, THRU UPRIGHTS, XP GOOD
	P1_XP_MISS_BLOCK_LEFT_UR_GOOD_CUT_SEQ_INDEX    .dsb 1; 0X32 P1 XP ATT, MISSED BLOCK, HIT LEFT UPRIGHT, XP GOOD
	P1_XP_MISS_BLOCK_RIGHT_UR_GOOD_CUT_SEQ_INDEX   .dsb 1; 0X33 P1 XP ATT, MISSED BLOCK, HIT RIGHT UPRIGHT, XP GOOD
	P2_XP_MISS_BLOCK_RIGHT_UR_GOOD_CUT_SEQ_INDEX   .dsb 1; 0X34 P2 XP ATT, MISSED BLOCK, HIT RIGHT UPRIGHT, XP GOOD
	P2_XP_MISS_BLOCK_LEFT_UR_GOOD_CUT_SEQ_INDEX    .dsb 1; 0X35 P2 XP ATT, MISSED BLOCK, HIT LEFT UPRIGHT, XP GOOD
	P1_XP_MISS_BLOCK_LEFT_UR_MISS_CUT_SEQ_INDEX    .dsb 1; 0X36 P1 XP ATT, MISSED BLOCK, HIT LEFT UPRIGHT, XP MISS
	P1_XP_MISS_BLOCK_RIGHT_UR_MISS_CUT_SEQ_INDEX   .dsb 1; 0X37 P1 XP ATT, MISSED BLOCK, HIT RIGHT UPRIGHT, XP MISS
	P1_XP_MISS_BLOCK_WIDE_LEFT_CUT_SEQ_INDEX       .dsb 1; 0X38 P1 XP ATT, MISSED BLOCK, WIDE LEFT XP MISS
	P1_XP_MISS_BLOCK_WIDE_RIGHT_CUT_SEQ_INDEX      .dsb 1; 0X39 P1 XP ATT, MISSED BLOCK, WIDE RIGHT XP MISS
	P1_XP_MISS_BLOCK_SHORT_CUT_SEQ_INDEX           .dsb 1; 0X3A P1 XP ATT, MISSED BLOCK, XP SHORT (IMPOSSIBLE)
	P2_XP_MISS_BLOCK_RIGHT_UR_MISS_CUT_SEQ_INDEX   .dsb 1; 0X3B P2 XP ATT, MISSED BLOCK, HIT RIGHT UPRIGHT, XP MISS
	P2_XP_MISS_BLOCK_LEFT_UR_MISS_CUT_SEQ_INDEX    .dsb 1; 0X3C P2 XP ATT, MISSED BLOCK, HIT LEFT UPRIGHT, XP MISS
	P2_XP_MISS_BLOCK_WIDE_RIGHT_CUT_SEQ_INDEX      .dsb 1; 0X3D P2 XP ATT, MISSED BLOCK, WIDE RIGHT XP MISS
	P2_XP_MISS_BLOCK_WIDE_LEFT_CUT_SEQ_INDEX       .dsb 1; 0X3E P2 XP ATT, MISSED BLOCK, WIDE LEFT XP MISS
	P2_XP_MISS_BLOCK_SHORT_CUT_SEQ_INDEX           .dsb 1; 0X3F P2 XP ATT, MISSED BLOCK, XP SHORT (IMPOSSIBLE)

	P1_XP_GOOD_CUT_SEQ_INDEX                       .dsb 1; 0X40 P1 XP ATT, THRU UPRIGHTS, XP GOOD
	P1_XP_LEFT_UR_GOOD_CUT_SEQ_INDEX               .dsb 1; 0X41 P1 XP ATT, HIT LEFT UPRIGHT, XP GOOD
	P1_XP_RIGHT_UR_GOOD_CUT_SEQ_INDEX              .dsb 1; 0X42 P1 XP ATT, HIT RIGHT UPRIGHT, XP GOOD
	P2_XP_RIGHT_UR_GOOD_CUT_SEQ_INDEX              .dsb 1; 0X43 P2 XP ATT, HIT RIGHT UPRIGHT, XP GOOD
	P2_XP_LEFT_UR_GOOD_CUT_SEQ_INDEX               .dsb 1; 0X44 P2 XP ATT, HIT LEFT UPRIGHT, XP GOOD
	P1_XP_LEFT_UR_MISS_CUT_SEQ_INDEX               .dsb 1; 0X45 P1 XP ATT, HIT LEFT UPRIGHT, XP MISS
	P1_XP_RIGHT_UR_MISS_CUT_SEQ_INDEX              .dsb 1; 0X46 P1 XP ATT, HIT RIGHT UPRIGHT, XP MISS
	P1_XP_WIDE_LEFT_CUT_SEQ_INDEX                  .dsb 1; 0X47 P1 XP ATT, WIDE LEFT,  XP MISS
	P1_XP_WIDE_RIGHT_CUT_SEQ_INDEX                 .dsb 1; 0X48 P1 XP ATT, WIDE RIGHT, XP MISS
	P1_XP_SHORT_CUT_SEQ_INDEX                      .dsb 1; 0X49 P1 XP ATT, XP SHORT(IMPOSSIBLE)
	P2_XP_RIGHT_UR_MISS_CUT_SEQ_INDEX              .dsb 1; 0X4A P2 XP ATT, HIT RIGHT UPRIGHT, XP MISS
	P2_XP_LEFT_UR_MISS_CUT_SEQ_INDEX               .dsb 1; 0X4B P2 XP ATT, HIT LEFT UPRIGHT, XP MISS
	P2_XP_WIDE_RIGHT_CUT_SEQ_INDEX                 .dsb 1; 0X4C P2 XP ATT, WIDE RIGHT, XP MISS
	P2_XP_WIDE_LEFT_CUT_SEQ_INDEX                  .dsb 1; 0X4D P2 XP ATT, WIDE LEFT, XP MISS
	P2_XP_SHORT_CUT_SEQ_INDEX                      .dsb 1; 0X4E P2 XP ATT, MISSED BLOCK, XP SHORT (IMPOSSIBLE)
	OFF_JUMP_CATCH_CUT_SEQ_INDEX                   .dsb 1; 0X4F OFF JUMP CATCH
	
	OFF_JUMP_CATCH_CUT_SEQ_INDEX_DUPE              .dsb 1; 0X50 OFF JUMP CATCH	
	OFF_JUMP_MISS_CUT_SEQ_INDEX                    .dsb 1; 0X51 OFF JUMP MISS
	OFF_JUMP_BOUNCE_HANDS_CUT_SEQ_INDEX            .dsb 1; 0X52 OFF JUMP BOUNCE OFF HANDS
	DEF_JUMP_MIS_CUT_SEQ_INDEX                     .dsb 1; 0X53 DEF JUMP MISS
	DEF_JUMP_BOUNCE_HANDS_CUT_SEQ_INDEX            .dsb 1; 0X54 DEF JUMP BOUNCE OFF HANDS
	DEF_JUMP_INT_CUT_SEQ_INDEX                     .dsb 1; 0X55 DEF JUMP INT
	DOUBLE_JUMP_OFF_CATCH_CUT_SEQ_INDEX            .dsb 1; 0X56 DOUBLE JUMP + OFF CATCH
	DOUBLE_JUMP_OFF_WHIFF_CUT_SEQ_INDEX            .dsb 1; 0X57 DOUBLE JUMP + OFF WHIFF
	DOUBLE_JUMP_BOUNCE_DEF_HANDS_CUT_SEQ_INDEX     .dsb 1; 0X58 DOUBLE JUMP + DEF BOUNCE OFF HANDS
	DOUBLE_JUMP_DEF_INT_CUT_SEQ_INDEX              .dsb 1; 0X59 DOUBLE JUMP + DEF INT

	OFF_REG_CATCH_CUT_SEQ_INDEX                     .dsb 1; 0X5A OFF REG SIDEWAYS CATCH
	OFF_REG_BOUNCE_HANDS_CUT_SEQ_INDEX              .dsb 1; 0X5B OFF REG SIDEWAYS BOUNCE OFF HANDS
	DEF_REG_BOUNCE_HANDS_CUT_SEQ_INDEX              .dsb 1; 0X5C DEF REG SIDEWAYS BOUNCE OFF HANDS
	DEF_REG_INT_CUT_SEQ_INDEX                       .dsb 1; 0X5D DEF REG SIDEWAYS INT
	DEF_DIVE_MISS_OFF_REG_CATCH_CUT_SEQ_INDEX       .dsb 1; 0X5E DEF DIVE MISS + OFF REG SIDEWAYS CATCH
	DEF_JUMP_MISS_OFF_REG_CATCH_CUT_SEQ_INDEX       .dsb 1; 0X5F DEF JUMP MISS + OFF REG SIDEWAYS CATCH
	
	OFF_DIVE_BOUNCE_OFF_HANDS_CUT_SEQ_INDEX         .dsb 1; 0X60 OFF DIVE + BOUNCE OFF HANDS
	DEF_DIVE_MISS_BOUNCE_OFF_WR_HANDS_CUT_SEQ_INDEX .dsb 1; 0X61 OFF JUMP + BOUNCE OFF HANDS
	DEF_JUMP_MISS_BOUNCE_OFF_WR_HANDS_CUT_SEQ_INDEX .dsb 1; 0X62 DEF JUMP + BOUNCE OFF HANDS
	DEF_JUMP_TIP_BALL_CUT_SEQ_INDEX                 .dsb 1; 0X63 DEF JUMP + BOUNCE OFF HANDS
	DOUBLE_JUMP_BOUNCE_DEF_HANDS_CUT_SEQ_INDEX_DUPE .dsb 1; 0X64 DOUBLE JUMP + DEF BOUNCE OFF HANDS (DUPLICATE OF 0X58 ABOVE)
	DEF_REG_INT_CUT_SEQ_INDEX_DUPE                  .dsb 1; 0X65 DEF REG SIDEWAYS INT (DUPLICATE OF 0X5D ABOVE)
	BALL_HIT_GROUND_REF_INC_CUT_SEQ_INDEX           .dsb 1; 0X66 BALL HITS GROUND + REF INCOMPLETE
	OFF_DIVE_CATCH_CUT_SEQ_INDEX                    .dsb 1; 0X67 OFF DIVE CATCH
	OFF_DIVE_MISS_CUT_SEQ_INDEX                     .dsb 1; 0X68 OFF DIVE MISS
	DEF_DIVE_INT_CUT_SEQ_INDEX                      .dsb 1; 0X69 DEF DIVE INT
	DEF_DIVE_MISS_CUT_SEQ_INDEX                     .dsb 1; 0X6A DEF DIVE MISS

	DEFAULT_IRQ_SPLIT_TABLE_CUT_SEQ_INDEX           .dsb 1; 0X6B INTRO
.ENDE 

_F}_CUTSCENE_SEQUENCE_IDS	
