
_F{_DEFENSIVE_STARTER_SCREEN_SPRITE_X_Y_LOCATIONS

LE_DEF_STARTER_TRIANGLE_SPR_Y	= $20	 
LE_DEF_STARTER_TRIANGLE_SPR_X	= $90

NT_DEF_STARTER_TRIANGLE_SPR_Y	= $20	 
NT_DEF_STARTER_TRIANGLE_SPR_X	= $78

RE_DEF_STARTER_TRIANGLE_SPR_Y	= $20	 
RE_DEF_STARTER_TRIANGLE_SPR_X	= $60

LOLB_DEF_STARTER_TRIANGLE_SPR_Y	= $28	 
LOLB_DEF_STARTER_TRIANGLE_SPR_X	= $A8

LILB_DEF_STARTER_TRIANGLE_SPR_Y	= $30	 
LILB_DEF_STARTER_TRIANGLE_SPR_X	= $88

RILB_DEF_STARTER_TRIANGLE_SPR_Y	= $30	 
RILB_DEF_STARTER_TRIANGLE_SPR_X	= $68

ROLB_DEF_STARTER_TRIANGLE_SPR_Y	= $28	 
ROLB_DEF_STARTER_TRIANGLE_SPR_X	= $48

LCB_DEF_STARTER_TRIANGLE_SPR_Y	= $38	 
LCB_DEF_STARTER_TRIANGLE_SPR_X	= $D8

RCB_DEF_STARTER_TRIANGLE_SPR_Y	= $38	 
RCB_DEF_STARTER_TRIANGLE_SPR_X	= $18

FS_DEF_STARTER_TRIANGLE_SPR_Y	= $40	 
FS_DEF_STARTER_TRIANGLE_SPR_X	= $98

SS_DEF_STARTER_TRIANGLE_SPR_Y	= $40	 
SS_DEF_STARTER_TRIANGLE_SPR_X	= $60

_F}_DEFENSIVE_STARTER_SCREEN_SPRITE_X_Y_LOCATIONS

