
_F{_END_OF_GAME_STATS_PPU_LOCATIONS

;;; END OF GAME STATS LOCATIONS ;;;;;;;;;;;;;;;;;;;;;;;;;;;

P1_TEAM_NAME_EOG_STATS_PPU_ADDR 		            = $2086
P2_TEAM_NAME_EOG_STATS_PPU_ADDR 		            = $20C6

P1_TOTAL_SCORE_EOG_STATS_PPU_ADDR		            = $209A
P2_TOTAL_SCORE_EOG_STATS_PPU_ADDR		            = $20DA

;;; TOP BOX;;;
P1_RUSHES_EOG_STATS_PPU_ADDR			            = $21A8
P2_RUSHES_EOG_STATS_PPU_ADDR			            = P1_RUSHES_EOG_STATS_PPU_ADDR + LENGTH_OF_ONE_ROW

P1_RUSH_YARDS_EOG_STATS_PPU_ADDR		            = P1_RUSHES_EOG_STATS_PPU_ADDR + 2
P2_RUSH_YARDS_EOG_STATS_PPU_ADDR		            = P2_RUSHES_EOG_STATS_PPU_ADDR + 2

P1_PASS_YARDS_EOG_STATS_PPU_ADDR		            = P1_RUSHES_EOG_STATS_PPU_ADDR + 9
P2_PASS_YARDS_EOG_STATS_PPU_ADDR		            = P2_RUSHES_EOG_STATS_PPU_ADDR + 9

P1_FIRST_DOWNS_EOG_STATS_PPU_ADDR		            = P1_RUSHES_EOG_STATS_PPU_ADDR + 17
P2_FIRST_DOWNS_EOG_STATS_PPU_ADDR		            = P2_RUSHES_EOG_STATS_PPU_ADDR + 17

;;; RUN LEADERS ;;;
P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR	            = $2287
P1_RUSH_LEADER_ATT_EOG_STATS_PPU_ADDR	            = P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR 	+ 17 
P1_RUSH_LEADER_YDS_EOG_STATS_PPU_ADDR	            = P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR 	+ 19

P2_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR	            = P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR + LENGTH_OF_ONE_ROW
P2_RUSH_LEADER_ATT_EOG_STATS_PPU_ADDR	            = P2_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR	+ 17 
P2_RUSH_LEADER_YDS_EOG_STATS_PPU_ADDR	            = P2_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR 	+ 19

;;; PASS LEADERS ;;;
P1_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR			    = P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR + (3 * LENGTH_OF_ONE_ROW)
P1_PASS_LEADER_COMP_PCT_EOG_STATS_PPU_ADDR		    = P1_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 12
P1_PASS_LEADER_YARDS_EOG_STATS_PPU_ADDR			    = P1_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 16
P1_PASS_LEADER_INTS_EOG_STATS_PPU_ADDR			    = P1_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 21

P2_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR			    = P1_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + LENGTH_OF_ONE_ROW
P2_PASS_LEADER_COMP_PCT_EOG_STATS_PPU_ADDR		    = P2_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 12
P2_PASS_LEADER_YARDS_EOG_STATS_PPU_ADDR			    = P2_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 16
P2_PASS_LEADER_INTS_EOG_STATS_PPU_ADDR			    = P2_PASS_LEADER_NAME_EOG_STATS_PPU_ADDR + 21


;;; REC LEADERS ;;;
P1_REC_LEADER_NAME_EOG_STATS_PPU_ADDR				= P1_RUSH_LEADER_NAME_EOG_STATS_PPU_ADDR + (6 * LENGTH_OF_ONE_ROW)
P1_REC_LEADER_ATT_EOG_STATS_PPU_ADDR				= P1_REC_LEADER_NAME_EOG_STATS_PPU_ADDR  + 17 
P1_REC_LEADER_YDS_EOG_STATS_PPU_ADDR				= P1_REC_LEADER_NAME_EOG_STATS_PPU_ADDR  + 19

P2_REC_LEADER_NAME_EOG_STATS_PPU_ADDR				= P1_REC_LEADER_NAME_EOG_STATS_PPU_ADDR  + LENGTH_OF_ONE_ROW
P2_REC_LEADER_ATT_EOG_STATS_PPU_ADDR				= P2_REC_LEADER_NAME_EOG_STATS_PPU_ADDR 	+ 17  
P2_REC_LEADER_YDS_EOG_STATS_PPU_ADDR				= P2_REC_LEADER_NAME_EOG_STATS_PPU_ADDR 	+ 19

_F}_END_OF_GAME_STATS_PPU_LOCATIONS
