;; FORMATIONS

_F{_FORMATIONS_IDS

.ENUM $00

KICKOFF_OFF_FORMATION_ID			.dsb 1
PUNT_OFF_FORMATION_ID				.dsb 1
FG_OFF_FORMATION_ID					.dsb 1
XP_OFF_FORMATION_ID					.dsb 1
PRO_T_OFF_FORMATION_ID				.dsb 1
SLOT_OFF_FORMATION_ID				.dsb 1
ONESET_OFF_FORMATION_ID				.dsb 1
TWO_TE_OFF_FORMATION_ID				.dsb 1
MOTION_DOWN_OFF_FORMATION_ID		.dsb 1
SHIFT_ONE_OFF_FORMATION_ID			.dsb 1
ONEBACK_OFF_FORMATION_ID			.dsb 1
OFFSET_I_OFF_FORMATION_ID			.dsb 1
R_AND_S_OFF_FORMATION_ID			.dsb 1
THREE_WING_OFF_FORMATION_ID			.dsb 1
SHOT_A_OFF_FORMATION_ID				.dsb 1
SHOT_B_OFF_FORMATION_ID				.dsb 1
SHOT_THREE_WING_OFF_FORMATION_ID	.dsb 1
SHOT_C_OFF_FORMATION_ID				.dsb 1
REDGUN_OFF_FORMATION_ID				.dsb 1
NO_BACK_OFF_FORMATION_ID			.dsb 1
PRO_T_B_OFF_FORMATION_ID			.dsb 1
ONEBACK_B_OFF_FORMATION_ID			.dsb 1

.ENDE

.ENUM $00

KICKOFF_DEF_PLAY_ID					.dsb 1
PUNT_DEF_PLAY_ID					.dsb 1
FG_DEF_PLAY_ID						.dsb 1
XP_DEF_PLAY_ID						.dsb 1

.ENDE

_F}_FORMATIONS_IDS
