_F{_LEADER_SCREEN_PPU_LOCATIONS

INDIV_LEADER_SCREEN_STARTING_PPU_ADDR			            = $20A0
 
SINGLE_STAT_LEADER_SCREEN_TITLE_PPU_ADDR		            = $2080
SINGLE_STAT_LEADER_SCREEN_STARTING_PPU_ADDR		            = $20E0

SACK_LEADERS_STAT_LABEL_STARTING_PPU_ADDR		            = $20B6

SINGLE_STAT_LEADER_SCREEN_STARTING_ATTR_ADDR	            = $23C8 

;;; PASSING LEADERS OFFSETS	;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 


OFFSET_TO_PASSING_LEADER_COLUMN_NAMES_SCREEN_ONE			= $26
OFFSET_TO_PASSING_LEADER_PASSING_ATTEMPTS					= OFFSET_TO_PASSING_LEADER_COLUMN_NAMES_SCREEN_ONE 	+ $20
OFFSET_TO_PASSING_LEADER_PASSING_COMPLETIONS				= OFFSET_TO_PASSING_LEADER_PASSING_ATTEMPTS 		+ $04
OFFSET_TO_PASSING_LEADER_COMP_PCT_VALUE						= OFFSET_TO_PASSING_LEADER_PASSING_COMPLETIONS 		+ $04
OFFSET_TO_PASSING_LEADER_PERCENT_SIGN					   	= OFFSET_TO_PASSING_LEADER_COMP_PCT_VALUE 			+ $05
OFFSET_TO_PASSING_LEADER_PERCENT_YARDS						= OFFSET_TO_PASSING_LEADER_PERCENT_SIGN 			+ $02
OFFSET_TO_PASSING_LEADER_PERCENT_YARDS_PER_ATTEMPT			= OFFSET_TO_PASSING_LEADER_PERCENT_YARDS 			+ $05


OFFSET_TO_PASSING_LEADER_COLUMN_NAMES_SCREEN_TWO			= $20
OFFSET_TO_PASSING_LEADER_PASSING_TDS						= OFFSET_TO_PASSING_LEADER_COLUMN_NAMES_SCREEN_TWO + $20
OFFSET_TO_PASSING_LEADER_PASSING_INTS						= OFFSET_TO_PASSING_LEADER_PASSING_TDS			   + $03
OFFSET_TO_PASSING_LEADER_PASSING_RATING						= OFFSET_TO_PASSING_LEADER_PASSING_INTS			   + $03
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_SCORING_LEADER_COLUMN_NAMES						= $2C
OFFSET_TO_SCORING_LEADER_TOTAL_TDS							= OFFSET_TO_SCORING_LEADER_COLUMN_NAMES				+ $1E
OFFSET_TO_SCORING_LEADER_XPS						 		= OFFSET_TO_SCORING_LEADER_TOTAL_TDS				+ $05
OFFSET_TO_SCORING_LEADER_XP_SLASH							= OFFSET_TO_SCORING_LEADER_XPS						+ $02
OFFSET_TO_SCORING_LEADER_XP_ATT								= OFFSET_TO_SCORING_LEADER_XP_SLASH					+ $01 
OFFSET_TO_SCORING_LEADER_FGS								= OFFSET_TO_SCORING_LEADER_XP_ATT 					+ $03
OFFSET_TO_SCORING_LEADER_FG_SLASH							= OFFSET_TO_SCORING_LEADER_FGS						+ $02
OFFSET_TO_SCORING_LEADER_FG_ATT								= OFFSET_TO_SCORING_LEADER_FG_SLASH					+ $01
OFFSET_TO_SCORING_LEADER_TOTAL_PTS							= OFFSET_TO_SCORING_LEADER_FG_ATT					+ $02

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_INTERCEPTION_LEADER_COLUMN_NAMES					= $30
OFFSET_TO_INTERCEPTION_LEADER_INTS							= $4F
OFFSET_TO_INTERCEPTION_LEADER_INT_YARDS						= OFFSET_TO_INTERCEPTION_LEADER_INTS				+ $03
OFFSET_TO_INTERCEPTION_LEADER_INT_YARD_AVG					= OFFSET_TO_INTERCEPTION_LEADER_INT_YARDS			+ $04
OFFSET_TO_INTERCEPTION_LEADER_INT_TDS						= OFFSET_TO_INTERCEPTION_LEADER_INT_YARD_AVG		+ $05

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_PUNT_RETURN_LEADER_COLUMN_NAMES					= $2F
OFFSET_TO_PUNT_RETURN_LEADER_ATT							= OFFSET_TO_PUNT_RETURN_LEADER_COLUMN_NAMES			+ $1F
OFFSET_TO_PUNT_RETURN_LEADER_YARDS							= OFFSET_TO_PUNT_RETURN_LEADER_ATT					+ $04
OFFSET_TO_PUNT_RETURN_LEADER_YARD_AVG						= OFFSET_TO_PUNT_RETURN_LEADER_YARDS				+ $04
OFFSET_TO_PUNT_RETURN_LEADER_TDS							= OFFSET_TO_PUNT_RETURN_LEADER_YARD_AVG				+ $05

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_RECEIVING_LEADER_COLUMN_NAMES						= $2E
OFFSET_TO_RECEIVING_LEADER_REC								= $4D
OFFSET_TO_RECEIVING_LEADER_REC_YDS							= OFFSET_TO_RECEIVING_LEADER_REC					+ $04 
OFFSET_TO_RECEIVING_LEADER_REC_AVG							= OFFSET_TO_RECEIVING_LEADER_REC_YDS				+ $05
OFFSET_TO_RECEIVING_LEADER_REC_TDS							= OFFSET_TO_RECEIVING_LEADER_REC_AVG				+ $04

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_RUSHING_LEADER_COLUMN_NAMES						= $2D
OFFSET_TO_RUSHING_LEADER_RUSH_ATT							= $4D
OFFSET_TO_RUSHING_LEADER_RUSH_YDS							= OFFSET_TO_RUSHING_LEADER_RUSH_ATT					+ $04 
OFFSET_TO_RUSHING_LEADER_RUSH_AVG							= OFFSET_TO_RUSHING_LEADER_RUSH_YDS					+ $05
OFFSET_TO_RUSHING_LEADER_RUSH_TDS							= OFFSET_TO_RUSHING_LEADER_RUSH_AVG					+ $04

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_PUNTING_LEADER_COLUMN_NAMES						= $31
OFFSET_TO_PUNTING_LEADER_PUNTS								= $50
OFFSET_TO_PUNTING_LEADER_PUNT_YARDS							= OFFSET_TO_PUNTING_LEADER_PUNTS 					+ $04
OFFSET_TO_PUNTING_LEADER_PUNT_AVG							= OFFSET_TO_PUNTING_LEADER_PUNT_YARDS 				+ $05

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

OFFSET_TO_KICK_RETURN_LEADER_COLUMN_NAMES					= $2F
OFFSET_TO_KICK_RETURN_LEADER_ATT							= $4E
OFFSET_TO_KICK_RETURN_LEADER_YARDS							= OFFSET_TO_KICK_RETURN_LEADER_ATT					+ $04
OFFSET_TO_KICK_RETURN_LEADER_YARD_AVG						= OFFSET_TO_KICK_RETURN_LEADER_YARDS				+ $04
OFFSET_TO_KICK_RETURN_LEADER_TDS							= OFFSET_TO_KICK_RETURN_LEADER_YARD_AVG				+ $05

_F}_LEADER_SCREEN_PPU_LOCATIONS
