_F{_MENU_CHOICE_CONSTANTS

.ENUM $00

AUTOKSIP_CHOICE				.dsb 1
PLAYOFF_BRACKET_CHOICE		.dsb 1
RESET_SCHEDULE_CHOICE		.dsb 1

.ENDE 

.ENUM $00

RESET_NO_CHOICE				.dsb 1
RESET_YES_CHOICE			.dsb 1

.ENDE 

.ENUM $00

TEAM_CONTROL_CHOICE			.dsb 1
SCHEDULE_CHOICE				.dsb 1
SEASON_GAME_START_CHOICE	.dsb 1
NFL_STANDINGS_CHOICE		.dsb 1
TEAM_RANKINGS_CHOICE		.dsb 1
NFL_LEADERS_CHOICE			.dsb 1

.ENDE

_F}_MENU_CHOICE_CONSTANTS

