

_F{_BACKGROUND_PALLETE_INDEXES

;;; BACKGROUND PALLETE INDEXES	;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Each pallete entry is 16 bytes 
;;; These are the ids to them. Each index gets bit shiffted left 4 times to do an effective multiply
;;; by 16 to get the offset from the start of the BG pallete table

.ENUM $00
INTRO_SCREEN_BG_PAL_INDEX							.dsb 0
CHEERLEADER_PANTY_HALFTIME_BG_PAL_INDEX				.dsb 0
BOMJACK_HALFTIME_BG_PAL_INDEX						.dsb 0
ROSTER_CREDITS_BG_PAL_INDEX							.dsb 1

BALOONS_HALFTIME_BG_PAL_INDEX						.dsb 0
BLIMP_HALFTIME_BG_PAL_INDEX							.dsb 1

CHEERLEADER_WINK_HALFTIME_BG_PAL_INDEX				.dsb 1

BAND__HALFTIME_BG_PAL_INDEX							.dsb 1

CHEERLEADER_KISS_HALFTIME_BG_PAL_INDEX				.dsb 0
PUNT_SCENE_BG_PAL_INDEX								.dsb 1

PARACHUTE_HALFTIME_BG_PAL_INDEX						.dsb 0 
KICK_UPRIGHTS_BG_PAL_INDEX							.dsb 0
KICK_SHORT_BG_PAL_INDEX								.dsb 0
HAND_CATCHING_BALL_BG_PAL_INDEX						.dsb 1

ROSTER_CREDITS_TWO_BG_PAL_INDEX						.dsb 1  ; before qb and dl 
LT_OVER_PLAYER_INTRO_BG_PAL_INDEX					.dsb 1
LT_OVER_PLAYER_FLASH_INTRO_BG_PAL_INDEX				.dsb 1
LINEMAN_INTRO_BG_PAL_INDEX							.dsb 1

FOOTBALL_INTRO_BG_PAL_INDEX							.dsb 0
CHAIN_MEASURE_BG_PAL_INDEX							.dsb 1
DIVISION_CHAMP_BG_PAL_INDEX							.dsb 1
SKYLINE_INTRO_BG_PAL_INDEX							.dsb 1
LARGE_SCOREBOARD_BG_PAL_INDEX						.dsb 1
TEAM_NFLPA_INTRO_BG_PAL_INDEX						.dsb 1
PLAY_CALL_SCREEN_BG_PAL_INDEX						.dsb 1	; 0x0f

BARRY_INTRO_BG_PAL_INDEX							.dsb 1  ; 0x10

RETURN_INJURY_BG_PAL_INDEX							.dsb 0						
FILL_SCREEN_BG_PAL_INDEX							.dsb 1

CONF_CHAMP_BG_PAL_INDEX								.dsb 1

PRESEASON_MENU_BG_PAL_INDEX 						.dsb 0
SEASON_MENU_BG_PAL_INDEX 							.dsb 1
	
TEAM_RANKINGS_BG_PAL_INDEX							.dsb 0
PLAYOFF_BRACKET_BG_PAL_INDEX						.dsb 0
TEAM_CONTROL_BG_PAL_INDEX							.dsb 0
TEAM_DATA_HELMETS_BG_PAL_INDEX						.dsb 1

SCHEDULE_MENU_BG_PAL_INDEX							.dsb 1
RUSH_TD_SCENE_BG_PAL_INDEX							.dsb 1

KICK_NO_GOOD_BG_PAL_INDEX							.dsb 0
KICK_HIT_CROSSBAR_BG_PAL_INDEX						.dsb 1

SUPERBOWL_SCENE_BG_PAL_INDEX						.dsb 1
LT_OVER_PLAYER_FLASH_2_INTRO_BG_PAL_INDEX			.dsb 1

TECMO_PRESENTS_INTRO_BG_PAL_INDEX					.dsb 0
TECMO_SCROLL_IN_INTRO_BG_PAL_INDEX					.dsb 0
ROSTER_SCROLL_IN_CREDITS_BG_PAL_INDEX				.dsb 1

RAMS_HELMET_SHELL_BG_PAL_INDEX						.dsb 1
BENGALS_HELMET_SHELL_BG_PAL_INDEX					.dsb 1
STANDARD_HELMET_SHELL_BG_PAL_INDEX					.dsb 1
REFLECT_HELMET_SHELL_BG_PAL_INDEX					.dsb 1

TECMO_SCROLL_IN_2_INTRO_BG_PAL_INDEX				.dsb 0
ROSTER_SCROLL_IN_2_CREDITS_BG_PAL_INDEX				.dsb 1 ; 0x1f

TECMO_PRESENTS_CREDITS_BG_PAL_INDEX					.dsb 0 ; 0x20
TECMO_SCROLL_IN_3_INTRO_BG_PAL_INDEX				.dsb 0
ROSTER_SCROLL_IN_3_CREDITS_BG_PAL_INDEX				.dsb 1

FLASHING_CREDITS_BG_PAL_INDEX						.dsb 1
HAND_IN_AIR_CREDITS_BG_PAL_INDEX					.dsb 1	
LEADING_PASSERS_BG_PAL_INDEX						.dsb 1 
LEADING_RUSHERS_BG_PAL_INDEX						.dsb 1
LEADING_SCORERS_BG_PAL_INDEX						.dsb 1
LEADING_PUNTERS_BG_PAL_INDEX						.dsb 1
INTERCEPTION_LEADERS_BG_PAL_INDEX					.dsb 1
SACK_LEADERS_BG_PAL_INDEX							.dsb 1
KR_LEADERS_BG_PAL_INDEX								.dsb 1
PR_LEADERS_BG_PAL_INDEX								.dsb 1
SOUND_MODE_SCREEN_BG_PAL_INDEX						.dsb 1
LARGE_HELMET_BG_PAL_INDEX							.dsb 1  ; FOR MATCHUP SCREEN
PLAYER_DATA_BG_PAL_INDEX							.dsb 1
 
OFF_STARTERS_BG_PAL_INDEX							.dsb 0 
DEF_STARTERS_BG_PAL_INDEX							.dsb 1

SET_PLAYBOOK_BG_PAL_INDEX							.dsb 1  ; 0x2F

PRO_BOWL_TEAM_DATA_BG_PAL_INDEX						.dsb 1
GATORADE_CREDITS_BG_PAL_INDEX						.dsb 1

PARACHUTE_HALFTIME_2_BG_PAL_INDEX					.dsb 0 
KICKING_CHEERLEADER_BG_PAL_INDEX					.dsb 0
QB_DROP_BACK_INTRO_BG_PAL_INDEX						.dsb 0
LT_STAND_UP_INTRO_BG_PAL_INDEX						.dsb 0
LT_WAVE_CREDITS_BG_PAL_INDEX						.dsb 0
KICK_SCENE_BG_PAL_INDEX								.dsb 0
KICK_GOOD_BG_PAL_INDEX								.dsb 0									
PUNT_SCENE_2_BG_PAL_INDEX							.dsb 0
PASS_INCOMPLETE_BG_PAL_INDEX						.dsb 0
REF_NO_GOOD_BG_PAL_INDEX							.dsb 1

PODIUM_CREDITS_BG_PAL_INDEX							.dsb 1
FINAL_STATS_SCREEN_BG_PAL_INDEX						.dsb 1

FLASHING_CREDITS_2_BG_PAL_INDEX						.dsb 0
QB_THROWING_BG_PAL_INDEX							.dsb 0				
PLAYER_CATCHING_BG_PAL_INDEX						.dsb 1

PLAYER_PORTRAIT_TEAM_DATA_BG_PAL_INDEX				.dsb 1
LEADING_RECEIVERS_BG_PAL_INDEX						.dsb 1

UNUSED_1_BG_PAL_INDEX								.dsb 1
UNUSED_2_BG_PAL_INDEX								.dsb 1
UNUSED_3_BG_PAL_INDEX								.dsb 1
UNUSED_4_BG_PAL_INDEX								.dsb 1

.ENDE
_F}_BACKGROUND_PALLETE_INDEXES

_F{_SPRITE_PALLETE_INDEXES

;;; SPRITE PALLETE INDEXES	;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Each pallete entry is 16 bytes 
;;; These are the ids to them. Each index gets bit shiffted left 4 times to do an effective multiply
;;; by 16 to get the offset from the start of the BG pallete table

.ENUM $00
	UNUSED_ONE_SPR_PAL_INDEX				.dsb 1

	NFL_SHIELD_SPR_PAL_INDEX				.dsb 0
	KICK_UPRIGHTS_SPR_PAL_INDEX				.dsb 0
	KICK_SHORT_SPR_PAL_INDEX				.dsb 0
	PLAY_CALL_SCREEN_SPR_PAL_INDEX			.dsb 0 
	DEF_STARTERS_SPR_PAL_INDEX				.dsb 1

	IND_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	BUF_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	MIA_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	NE_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	NYJ_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	
	CIN_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	CLE_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	HOU_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	PIT_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	
	DEN_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	KC_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	RAI_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	SD_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	SEA_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	
	DAL_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1 				
	NYG_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	PHI_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	PHX_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	WAS_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1

	CHI_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	DET_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	GB_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	MIN_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	TB_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	
	ATL_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	RAM_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	NO_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	SF_LARGE_HELMET_SPR_PAL_INDEX			.dsb 1
	
	LINEMAN_INTRO_SPR_PAL_INDEX				.dsb 1
	QB_DROPBACK_INTRO_SPR_PAL_INDEX			.dsb 1 
	LT_SACK_INTRO_SPR_PAL_INDEX				.dsb 1	; 0X20
	LT_OVER_PLAYER_INTRO_SPR_PAL_INDEX		.dsb 1
	LT_STANDING_INTRO_SPR_PAL_INDEX			.dsb 1		

    TEAM_RANKINGS_SPR_PAL_INDEX			 	.dsb 0 
	PLAYOFF_BRACKET_SPR_PAL_INDEX			.dsb 0
	TEAM_CONTROL_SPR_PAL_INDEX				.dsb 0 
    TEAM_DATA_HELMETS_SPR_PAL_INDEX			.dsb 1
	
	PRESEASON_MENU_SPR_PAL_INDEX 			.dsb 0
	SEASON_MENU_SPR_PAL_INDEX 				.dsb 1
	SCHEDULE_MENU_SPR_PAL_INDEX				.dsb 1
	
	LEADING_PASSERS_SPR_PAL_INDEX			.dsb 1
	LEADING_RUSHERS_SPR_PAL_INDEX			.dsb 1
	LEADING_KICKERS_SPR_PAL_INDEX			.dsb 1
	LEADING_PUNTERS_SPR_PAL_INDEX			.dsb 1
	INTERCEPTION_LEADERS_SPR_PAL_INDEX		.dsb 1
	SACK_LEADERS_SPR_PAL_INDEX				.dsb 1
	KR_LEADERS_SPR_PAL_INDEX				.dsb 1
	PR_LEADERS_SPR_PAL_INDEX				.dsb 1
	
	LARGE_HELMET_SPR_PAL_INDEX				.dsb 1
	OFF_STARTERS_SPR_PAL_INDEX				.dsb 1  ; 0x2F
	
	SET_PLAYBOOK_SPR_PAL_INDEX				.dsb 0			
	PRO_BOWL_TEAM_DATA_SPR_PAL_INDEX		.dsb 1
	
	UNUSED_1_SPR_PAL_INDEX					.dsb 1
	FACES_DIVISION_CHAMP_SPR_PAL_INDEX		.dsb 1
	KICKING_CHEERLEADER_SPR_PAL_INDEX		.dsb 1
	PARACHUTE_HALFTIME_SPR_PAL_INDEX		.dsb 1
	
	NFL_SHIELD_INTRO_SPR_PAL_INDEX			.dsb 0
	KICK_HIT_CROSSBAR_SPR_PAL_INDEX			.dsb 0
	KICK_WIDE_SPR_PAL_INDEX					.dsb 1
	
	WAVE_HALFTIME_SPR_PAL_INDEX				.dsb 1
	BARRY_FAST_SCREEN_INTRO_1_SPR_PAL_INDEX	.dsb 1 ; 2 frames each
	BARRY_FAST_SCREEN_INTRO_2_SPR_PAL_INDEX	.dsb 1
	BARRY_FAST_SCREEN_INTRO_3_SPR_PAL_INDEX	.dsb 1
	BARRY_FAST_SCREEN_INTRO_4_SPR_PAL_INDEX	.dsb 1
	
	LARGE_BARRY_INTRO_SPR_PAL_INDEX			.dsb 0
	CHEERLEADER_WINK_HALFTIME_SPR_PAL_INDEX .dsb 0
	CHEERLEADER_KISS_HALFTIME_SPR_PAL_INDEX	.dsb 1
	
	STADIUM_INTRO_SPR_PAL_INDEX				.dsb 1
	BLIMP_HALFTIME_SPR_PAL_INDEX			.dsb 1
	LT_SACK_FLASH_INTRO_SPR_PAL_INDEX		.dsb 1
	
	START_SCREEN_SPR_PAL_INDEX				.dsb 0
	SOUND_MODE_SPR_PAL_INDEX				.dsb 1 ; 0X3F
	
	GATORADE_CREDITS_SPR_PAL_INDEX			.dsb 1
	HAND_IN_AIR_CREDITS_SPR_PAL_INDEX		.dsb 1
	REF_SIGNALS_SPR_PAL_INDEX				.dsb 1
	UNUSED_2_SPR_PAL_INDEX					.dsb 1
	CHEERLEADER_PANTY_SPR_PAL_INDEX			.dsb 1
	UNUSED_3_SPR_PAL_INDEX					.dsb 1
	QB_PODIUM_SPR_PAL_INDEX					.dsb 1
	
	KICK_HIT_CROSSBAR_2_SPR_PAL_INDEX		.dsb 0
	LARGE_SCOREBOARD_SPR_PAL_INDEX			.dsb 1
	
	LT_WAVE_SPR_PAL_INDEX					.dsb 1
	FINAL_STATS_SCREEN_SPR_PAL_INDEX		.dsb 1
	
	TECMO_BUNNY_SPR_PAL_INDEX				.dsb 0
	BOMJACKS_SPR_PAL_INDEX					.dsb 1

	RETURN_INJURY_SPR_PAL_INDEX				.dsb 1
	
	QB_THROWING_SPR_PAL_INDEX				.dsb 0
	PLAYER_CATCHING_SPR_PAL_INDEX			.dsb 0
	PLAYER_SPIKE_BALL_SPR_PAL_INDEX			.dsb 0
	PLAYER_SACK_SPR_PAL_INDEX				.dsb 1

	PLAYER_FACES_SPR_PAL_INDEX				.dsb 0 
	WHITE_FACES_SPR_PAL_INDEX				.dsb 1
	BLACK_FACES_SPR_PAL_INDEX				.dsb 1
	
	LEADING_RECEIVERS_SPR_PAL_INDEX			.dsb 1 ; 0X4F

	STARS_ONE_CREDITS_SPR_PAL_INDEX			.dsb 1
	STARS_TWO_CREDITS_SPR_PAL_INDEX			.dsb 1
	BARRY_FAST_SCREEN_INTRO_5_SPR_PAL_INDEX .dsb 1	
.ENDE

_F}_SPRITE_PALLETE_INDEXES
	
_F{_CHANGING_PALLETE_INDEXES

.ENUM $0D
	PLAYBOOK_CONTROLLERS_CYCLING_PAL_INDEX				.dsb 1
.ENDE

_F}_CHANGING_PALLETE_INDEXES

