
_F{_SCENE_SCRIPT_PPU_LOCATIONS

STARTING_BG_SCRIPT_PPU_ADDR			         = 	$2082

_F}_SCENE_SCRIPT_PPU_LOCATIONS

_F{_TEAM_DATA_PPU_LOCATIONS

;;;;;;;;;;;;;;;;;TEAM_DATA;;;;;;;;;;;;;;;;;;;;;;;;;;
TEAM_DATA_TEAM_NAME_PPU_ADDR		         = $2054
STARTERS_RESET_AREA_PPU_ADDR		         = $2142

TEAM_DATA_WINS_PPU_ADDR				         = 	$20BB                                 
TEAM_DATA_LOSSES_PPU_ADDR			         = 	$20DB
TEAM_DATA_TIES_PPU_ADDR				         = 	$20FB 

_F}_TEAM_DATA_PPU_LOCATIONS

_F{_BANNER_PPU_LOCATIONS

; BANNER PPU LOCATIONS			

P1_KICK_BAR_PPU_ADDR			             =  $2050
P2_KICK_BAR_PPU_ADDR			             = $2044

P1_BANNER_NAME_PPU_ADDR				         = $2041
P2_BANNER_NAME_PPU_ADDR				         = $2054

ONSCREEN_BANNER_PPU_ADDR			         = $2040
OFFSCREEN_BANNER_PPU_ADDR			         = $2440
LOWER_BYTE_OF_BANNER_PPU_ADDR		         = $40 
OFFSCREEN_BANNER_LRG_SCORE_PPU_ADDR          = $244B

BANNER_LARGE_SCORE_PPU_ADDR			         = $204B
CLOCK_PPU_ADDR						         = $204D

P1_BANNER_SCORE_PPU_ADDR         	         = $206D
P2_BANNER_SCORE_PPU_ADDR         	         = $2070

DOWN_DISTANCE_BAN_PPU_ADDR			         = $246A

MAIN_MENU_TEXT_START_PPU_ADDR                = $2545

_F}_BANNER_PPU_LOCATIONS

_F{_RANKING_AND_STANDINGS_PPU_LOCATIONS

;;;;;;;;;;;;;;;;; TEAM _YARDAGE;;;;;;;;;;;;;;;;;;;;;;;;;;
TEAM_YARDAGE_RANK_NO_STARTING_PPU_ADDR	     = $20C1

SEASON_STANDINGS_PPU_ADDR        	         = $2400
SEASON_STANDING_PPU_ATTR_ADDR    	         = $27C2

TEAM_RANKINGS_PPU_ADDR           	         = $224D 
TEAM_RANKINGS_PPU_ATTR_ADDR      	         = $23EB

_F}_RANKING_AND_STANDINGS_PPU_LOCATIONS

_F{_PRO_BOWL_MENU_PPU_LOCATIONS

PRO_BOWL_MENU_OPTIONS_PPU_ADDR		         = $2040
PRO_BOWL_PLAYER_POS_PPU_ADDR		         = $2058	
PRO_BOWL_MENU_PPU_ADDR			 	         = $25C5
RESET_PRO_BOWL_STARTERS_PPU_ADDR	         = $20E7

_F}_PRO_BOWL_MENU_PPU_LOCATIONS

_F{_LARGE_SCOREBOARD_PPU_LOCATIONS

SCOREBOARD_P1_Q1_PPU_ADDR		             = $218A
SCOREBOARD_P1_TOTAL_PPU_ADDR	             = $2199		
SCOREBOARD_P2_TOTAL_PPU_ADDR	             = $21D9

_F}_LARGE_SCOREBOARD_PPU_LOCATIONS

_F{_RETURN_FROM_INJURY_PPU_LOCATIONS


;;;;;;;;;; RETURN FROM INJURY ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
RETURN_FROM_INJURY_TEAM_NAME_PPU_ADDR		 = $2160
RETURN_FROM_INJURY_PLAYER_NAME_PPU_ADDR		 = $213B

_F}_RETURN_FROM_INJURY_PPU_LOCATIONS

_F{_SOUND_MODE_PPU_LOCATIONS
;;;;;;;;SOUND MODE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SOUND_MODE_SONG_NUMBER_PPU_ADDR		         = $22B1

_F}_SOUND_MODE_PPU_LOCATIONS

_F{_DEFENSIVE_STARTER_PPU_LOCATIONS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;       DEFENSIVE STARTER SCREEN LOCATIONS	   ;

TEAM_NAME_DEF_STARTER_PPU_ADDR				 = $2054
DL_DASH_DEF_STARTER_PPU_ADDR				 = $21B4	
LB_DASH_DEF_STARTER_PPU_ADDR				 = $222A
DB_DASH_DEF_STARTER_PPU_ADDR				 = $2310



RE_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR		 = $21B2
NT_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR		 = $21D2
LE_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR		 = $21F2

ROLB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $2228
RILB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $2248
LILB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $2268
LOLB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $2288

RCB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $230E
LCB_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR	 = $232E
FS_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR		 = $234E
SS_NUMBER_BOT_SCRN_DEF_STARTER_PPU_ADDR		 = $236E
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; PRO BOWL TEAM DATA LOCATIONS	;;;;;;;;;;;;;;;;;

PLAYER_ALREADY_SELECTED_X_PPU_ADDR			 = $2081
PRO_BOWL_OFF_NAMES_START_PPU_ADDR			 = $2164
PRO_BOWL_DEF_NAMES_START_PPU_ADDR			 = $21B4
PRO_BOWL_KICKER_NAME_PPU_ADDR				 = $2334
PRO_BOWL_PUNTER_NAME_PPU_ADDR				 = $2374

_F}_DEFENSIVE_STARTER_PPU_LOCATIONS

_F{_MATCHUP_SCREEN_PPU_LOCATIONS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;       GAME MATCHUP LOCATIONS	   


GAME_MATCHUP_P1_TEAM_CITY_PPU_ADDR           = $2140
GAME_MATCHUP_P1_TEAM_MASCOT_PPU_ADDR         = $2186

GAME_MATCHUP_P2_TEAM_CITY_PPU_ADDR           = $2300
GAME_MATCHUP_P2_TEAM_MASCOT_PPU_ADDR         = $2346

AFC_TEAM_SELECT_TEXT_PPU_ADDR				 = $2269
NFC_TEAM_SELECT_TEXT_PPU_ADDR				 = AFC_TEAM_SELECT_TEXT_PPU_ADDR + $0B

_F}_MATCHUP_SCREEN_PPU_LOCATIONS

_F{_SCHEDULE_SCREEN_PPU_LOCATIONS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;       SCHEDULE LOCATIONS 					   ;

SCHEDULE_DATE_WEEK_A_PPU_ADDR	             =	$2080
SCHEDULE_DATE_WEEK_B_PPU_ADDR	             =	$2140
SCHEDULE_DATE_WEEK_C_PPU_ADDR	             = 	$2200
SCHEDULE_DATE_WEEK_D_PPU_ADDR	             =	$22C0

WEEK_A_MATCH_1_PPU_ADDR 		             = $20A7                                 ; 
WEEK_A_MATCH_2_PPU_ADDR 		             = $20C7
WEEK_A_MATCH_3_PPU_ADDR 		             = $20E7
WEEK_A_MATCH_4_PPU_ADDR 		             = $2107
WEEK_A_MATCH_5_PPU_ADDR 		             = $2127
	
WEEK_A_MATCH_6_PPU_ADDR 		             = $20AF
WEEK_A_MATCH_7_PPU_ADDR 		             = $20CF
WEEK_A_MATCH_8_PPU_ADDR 		             = $20EF
WEEK_A_MATCH_9_PPU_ADDR 		             = $210F
WEEK_A_MATCH_10_PPU_ADDR 		             = $212F
	
WEEK_A_MATCH_11_PPU_ADDR 		             = $20B7
WEEK_A_MATCH_12_PPU_ADDR 		             = $20D7
WEEK_A_MATCH_13_PPU_ADDR 		             = $20F7
WEEK_A_MATCH_14_PPU_ADDR 		             = $2117

                                      ; SECOND WEEK ON PAGE
WEEK_B_MATCH_1_PPU_ADDR 		             = $2167  
WEEK_B_MATCH_2_PPU_ADDR 		             = $2187
WEEK_B_MATCH_3_PPU_ADDR 		             = $21A7
WEEK_B_MATCH_4_PPU_ADDR 		             = $21C7
WEEK_B_MATCH_5_PPU_ADDR 		             = $21E7

WEEK_B_MATCH_6_PPU_ADDR 		             = $216F
WEEK_B_MATCH_7_PPU_ADDR 		             = $218F
WEEK_B_MATCH_8_PPU_ADDR 		             = $21AF
WEEK_B_MATCH_9_PPU_ADDR 		             = $21CF
WEEK_B_MATCH_10_PPU_ADDR 		             = $21EF

WEEK_B_MATCH_11_PPU_ADDR 		             = $2177
WEEK_B_MATCH_12_PPU_ADDR 		             = $2197
WEEK_B_MATCH_13_PPU_ADDR 		             = $21B7
WEEK_B_MATCH_14_PPU_ADDR 		             = $21D7

									; THIRD WEEK ON PAGE
WEEK_C_MATCH_1_PPU_ADDR 		             = $2227      
WEEK_C_MATCH_2_PPU_ADDR 		             = $2247
WEEK_C_MATCH_3_PPU_ADDR 		             = $2267
WEEK_C_MATCH_4_PPU_ADDR 		             = $2287
WEEK_C_MATCH_5_PPU_ADDR 		             = $22A7

WEEK_C_MATCH_6_PPU_ADDR 		             = $222F
WEEK_C_MATCH_7_PPU_ADDR 		             = $224F
WEEK_C_MATCH_8_PPU_ADDR 		             = $226F
WEEK_C_MATCH_9_PPU_ADDR 		             = $228F
WEEK_C_MATCH_10_PPU_ADDR 		             = $22AF

WEEK_C_MATCH_11_PPU_ADDR 		             = $2237
WEEK_C_MATCH_12_PPU_ADDR 		             = $2257
WEEK_C_MATCH_13_PPU_ADDR 		             = $2277
WEEK_C_MATCH_14_PPU_ADDR 		             = $2297

													; FOURTH WEEK ON PAGE
WEEK_D_MATCH_1_PPU_ADDR 		             = $22E7       
WEEK_D_MATCH_2_PPU_ADDR 		             = $2307
WEEK_D_MATCH_3_PPU_ADDR 		             = $2327
WEEK_D_MATCH_4_PPU_ADDR 		             = $2347
WEEK_D_MATCH_5_PPU_ADDR 		             = $2367

WEEK_D_MATCH_6_PPU_ADDR 		             = $22EF
WEEK_D_MATCH_7_PPU_ADDR 		             = $230F
WEEK_D_MATCH_8_PPU_ADDR 		             = $232F
WEEK_D_MATCH_9_PPU_ADDR 		             = $234F
WEEK_D_MATCH_10_PPU_ADDR 		             = $236F

WEEK_D_MATCH_11_PPU_ADDR 		             = $22F7
WEEK_D_MATCH_12_PPU_ADDR 		             = $2317
WEEK_D_MATCH_13_PPU_ADDR 		             = $2337
WEEK_D_MATCH_14_PPU_ADDR 		             = $2357


SCHEDULE_MENU_PPU_ADDR           	         = $2082
AUTOSKIP_MENU_PPU_ADDR           	         = $20C3
AUTOSKIP_WEEK_PPU_ADDR           	         = $210D
RESET_SCHEDULE_PPU_ADDR         	         = $2143
FINAL_RESET_PPU_ADDR             	         = $224D
SECOND_WEEK_SCHEDULE_START		             =  $2140

_F}_SCHEDULE_SCREEN_PPU_LOCATIONS

_F{_TEAM_CONTROL_SCREEN_PPU_LOCATIONS

;;;;;;;;TEAM_CONTROL ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
BUF_TEAM_CONTROL_PPU_ADDR	 		         = $20E6     ; BUFFALO 
IND_TEAM_CONTROL_PPU_ADDR	 		         = $2126
MIA_TEAM_CONTROL_PPU_ADDR			         = $2166
NE_TEAM_CONTROL_PPU_ADDR	 		         = $21A6
NYJ_TEAM_CONTROL_PPU_ADDR	 		         = $21E6
												; AFC CENT
CIN_TEAM_CONTROL_PPU_ADDR	 		         = $20F0
CLE_TEAM_CONTROL_PPU_ADDR	 		         = $2130
HOU_TEAM_CONTROL_PPU_ADDR	 		         = $2170
PIT_TEAM_CONTROL_PPU_ADDR	 		         = $21B0
												; AFC WEST
DEN_TEAM_CONTROL_PPU_ADDR	 		         = $20FA
KC_TEAM_CONTROL_PPU_ADDR	 		         = $213A
LAR_TEAM_CONTROL_PPU_ADDR	 		         = $217A
SD_TEAM_CONTROL_PPU_ADDR	 		         = $21BA
SEA_TEAM_CONTROL_PPU_ADDR	 		         = $21FA
												; NFC EAST
WAS_TEAM_CONTROL_PPU_ADDR	 		         = $2266
NYG_TEAM_CONTROL_PPU_ADDR		 	         = $22A6
PHI_TEAM_CONTROL_PPU_ADDR	 		         = $22E6
PHX_TEAM_CONTROL_PPU_ADDR	 		         = $2326
DAL_TEAM_CONTROL_PPU_ADDR	 		         = $2366
												; NFC CENT
CHI_TEAM_CONTROL_PPU_ADDR 			         = $2270
DET_TEAM_CONTROL_PPU_ADDR 			         = $22B0
GB_TEAM_CONTROL_PPU_ADDR 			         = $22F0
MIN_TEAM_CONTROL_PPU_ADDR 			         = $2330
TB_TEAM_CONTROL_PPU_ADDR 			         = $2370
												; NFC WEST
SF_TEAM_CONTROL_PPU_ADDR			         = $227A
LAM_TEAM_CONTROL_PPU_ADDR	 		         = $22BA
NO_TEAM_CONTROL_PPU_ADDR	 		         = $22FA
ATL_TEAM_CONTROL_PPU_ADDR	 		         = $233A     ; FALCONS

_F}_TEAM_CONTROL_SCREEN_PPU_LOCATIONS

_F{_PLAY_CALL_SCREEN_PPU_LOCATIONS
;;;;;;;;PLAY CALL SCREEN  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;
P1_TEAM_NAME_SELECT_READY_PPU_ADDR	         = $2041
P2_TEAM_NAME_SELECT_READY_PPU_ADDR	         = $2055



P1_READY_SELECT_TEXT_PPU_ADDR		         = $2063
P2_READY_SELECT_TEXT_PPU_ADDR		         = $2076

P1_PLAY_CALL_MENU_PPU_ADDR			         = $20A3
P2_PLAY_CALL_MENU_PPU_ADDR			         = $20B1

P1_TIMEOUT_MENU_PPU_ADDR			         = $2124
P1_TIMEOUTS_PPU_ADDR				         = $212C

P2_TIMEOUT_MENU_PPU_ADDR			         = $2132
P2_TIMEOUTS_PPU_ADDR				         = $213A
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
TEAM_NAME_PLAYBOOK_CHANGE_PPU_ADDR	         = $2054
PLAY_NAME_LOCATION_PPU_ADDR			         = $2362

RUN_PLAY_SUB_WINDOW_START_PPU_ADDR	         = $2200
RUN_PLAY_SUB_NAME_PPU_ADDR			         = $2224
OFFSCREEN_RUN_PLAY_START_PPU_ADDR	         = $2600 

PASS_PLAY_SUB_WINDOW_START_PPU_ADDR	         = $2080
PASS_PLAY_SUB_NAME_PPU_ADDR			         = $2064
OFFSCREEN_PASS_PLAY_START_PPU_ADDR	         = $2480 

WIDTH_OF_PLAY_IMAGE 				         = $08
OFFSET_TO_NEXT_HORIZ_NAMETABLE		         = $400  

PLAY_IMAGE_ONE_PPU_ADDR 			         = $20E3 
PLAY_IMAGE_TWO_PPU_ADDR 			         = $20EA 
PLAY_IMAGE_THREE_PPU_ADDR			         = $20F1 
PLAY_IMAGE_FOUR_PPU_ADDR			         = $20F8 
PLAY_IMAGE_FIVE_PPU_ADDR			         = $2223 
PLAY_IMAGE_SIX_PPU_ADDR				         = $222A 
PLAY_IMAGE_SEVEN_PPU_ADDR			         = $2231 
PLAY_IMAGE_EIGHT_PPU_ADDR			         = $2238


RUN_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR		     = $2261
RUN_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR		     = RUN_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
RUN_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR	     = RUN_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
RUN_PLAY_CHANGE_IMAGE_FOUR_PPU_ADDR		     = RUN_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
RUN_PLAY_CHANGE_IMAGE_FIVE_PPU_ADDR		     = RUN_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
RUN_PLAY_CHANGE_IMAGE_SIX_PPU_ADDR		     = RUN_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
RUN_PLAY_CHANGE_IMAGE_SEVEN_PPU_ADDR	     = RUN_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
RUN_PLAY_CHANGE_IMAGE_EIGHT_PPU_ADDR	     = RUN_PLAY_CHANGE_IMAGE_FOUR_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE

PASS_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR		     = $20A1
PASS_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR		     = PASS_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
PASS_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR	     = PASS_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
PASS_PLAY_CHANGE_IMAGE_FOUR_PPU_ADDR	     = PASS_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR + WIDTH_OF_PLAY_IMAGE
PASS_PLAY_CHANGE_IMAGE_FIVE_PPU_ADDR	     = PASS_PLAY_CHANGE_IMAGE_ONE_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
PASS_PLAY_CHANGE_IMAGE_SIX_PPU_ADDR		     = PASS_PLAY_CHANGE_IMAGE_TWO_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
PASS_PLAY_CHANGE_IMAGE_SEVEN_PPU_ADDR	     = PASS_PLAY_CHANGE_IMAGE_THREE_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE
PASS_PLAY_CHANGE_IMAGE_EIGHT_PPU_ADDR	     = PASS_PLAY_CHANGE_IMAGE_FOUR_PPU_ADDR + OFFSET_TO_NEXT_HORIZ_NAMETABLE

_F}_PLAY_CALL_SCREEN_PPU_LOCATIONS




	