

P2_SIDE_BITFLAG		= $80


.ENUM $00 

QB1_ROSTER_ID   	.dsb 1
QB2_ROSTER_ID   	.dsb 1
RB1_ROSTER_ID   	.dsb 1
RB2_ROSTER_ID   	.dsb 1
RB3_ROSTER_ID   	.dsb 1
RB4_ROSTER_ID   	.dsb 1
WR1_ROSTER_ID   	.dsb 1
WR2_ROSTER_ID   	.dsb 1
WR3_ROSTER_ID   	.dsb 1
WR4_ROSTER_ID   	.dsb 1
TE1_ROSTER_ID   	.dsb 1
TE2_ROSTER_ID   	.dsb 1
C_ROSTER_ID     	.dsb 1
LG_ROSTER_ID    	.dsb 1
RG_ROSTER_ID    	.dsb 1
LT_ROSTER_ID    	.dsb 1
RT_ROSTER_ID    	.dsb 1
RE_ROSTER_ID    	.dsb 1
NT_ROSTER_ID    	.dsb 1 
LE_ROSTER_ID    	.dsb 1
ROLB_ROSTER_ID  	.dsb 1
RILB_ROSTER_ID  	.dsb 1
LILB_ROSTER_ID  	.dsb 1
LOLB_ROSTER_ID  	.dsb 1
RCB_ROSTER_ID   	.dsb 1
LCB_ROSTER_ID   	.dsb 1
FS_ROSTER_ID    	.dsb 1
SS_ROSTER_ID    	.dsb 1
KICKER_ROSTER_ID	.dsb 1
PUNTER_ROSTER_ID	.dsb 1
.ENDE

NUMBER_OF_PLAYERS_ON_ROSTER							= PUNTER_ROSTER_ID - QB1_ROSTER_ID +1
NUMBER_OF_OFFENSIVE_PLAYERS_ON_ROSTER				= RE_ROSTER_ID - QB1_ROSTER_ID 
NUMBER_OF_QBS_ON_ROSTER								= RB1_ROSTER_ID - QB1_ROSTER_ID 
NUMBER_OF_SKILL_PLAYERS_ON_ROSTER					= C_ROSTER_ID - RB1_ROSTER_ID
NUMBER_OF_DEFENSIVE_PLAYERS_ON_ROSTER	 			= KICKER_ROSTER_ID - RE_ROSTER_ID 

.ENUM $00 
QB_POSITION_ID		.dsb 1
RB1_POSITION_ID		.dsb 1
RB2_POSITION_ID		.dsb 1
WR1_POSITION_ID		.dsb 1
WR2_POSITION_ID		.dsb 1
TE_POSITION_ID		.dsb 1
C_POSITION_ID		.dsb 1
LG_POSITION_ID		.dsb 1
RG_POSITION_ID		.dsb 1
LT_POSITION_ID		.dsb 1
RT_POSITION_ID		.dsb 1
.ENDE


.ENUM $00 
RE_POSITION_ID		.dsb 1
NT_POSITION_ID		.dsb 1
LE_POSITION_ID		.dsb 1
ROLB_POSITION_ID	.dsb 1
RILB_POSITION_ID	.dsb 1
LILB_POSITION_ID	.dsb 1
LOLB_POSITION_ID	.dsb 1
RCB_POSITION_ID		.dsb 1
LCB_POSITION_ID		.dsb 1
FS_POSITION_ID		.dsb 1
SS_POSITION_ID		.dsb 1
.ENDE

INIT_ICON_BITFLAG		= $80
ICON_CHANGE_BITFLAG		= $40									; used for the overhead icon
.ENUM $00 
QB_STARTER_ID		.dsb 1
RB1_STARTER_ID		.dsb 1
RB2_STARTER_ID		.dsb 1
WR1_STARTER_ID		.dsb 1
WR2_STARTER_ID		.dsb 1
TE1_STARTER_ID		.dsb 1
C_STARTER_ID		.dsb 1
LG_STARTER_ID		.dsb 1
RG_STARTER_ID		.dsb 1
LT_STARTER_ID		.dsb 1
RT_STARTER_ID		.dsb 1
RE_STARTER_ID		.dsb 1
NT_STARTER_ID		.dsb 1
LE_STARTER_ID		.dsb 1
ROLB_STARTER_ID		.dsb 1
RILB_STARTER_ID		.dsb 1
LILB_STARTER_ID		.dsb 1
LOLB_STARTER_ID		.dsb 1
RCB_STARTER_ID		.dsb 1
LCB_STARTER_ID		.dsb 1
FS_STARTER_ID		.dsb 1
SS_STARTER_ID		.dsb 1
KICKER_STARTER_ID  	.dsb 1
PUNTER_STARTER_ID	.dsb 1
KR_STARTER_ID		.dsb 1
PR_STARTER_ID		.dsb 1
.ENDE

NUMBER_OF_NON_QB_SKILL_STARTERS		= $05 
OFFSET_TO_DEFENDER_STARTERS 		= RE_STARTER_ID










