;;; SRAM USED TO SAVE PART OF MENUS SO WHOLE SCREEN DOESNT NEED TO BE RE-DRAWN;;;;

_F{_PLAY_OUT_ALL_GAMES_SRAM_VARIABLE
 
.ENUM $6002
PLAY_OUT_ALL_GAMES_BOOL		.dsb 1 	; 80= true

_F}_PLAY_OUT_ALL_GAMES_SRAM_VARIABLE

_F{_SAVE_PART_OF_MENU_SCREENS_SRAM_VARIABLES				; SHARED

MENU_SCREEN_SAVE_SRAM			.dsb 0
MAIN_MENU_SRAM					.dsb 0 			; for saving partial screen images
SCHEDULE_MENU_SRAM				.dsb 0
PRO_BOWL_MENU_SRAM				.dsb 0
RESET_STARTERS_SRAM				.dsb 0
PLAY_IMAGE_INFO_SRAM			.dsb 0
P1_PLAY_CALL_MENU_SRAM 			.dsb 0 
MINI_HELMET_ATTR_ONE_SRAM		.dsb 0
LARGE_HELMET_TILES_SRAM			.dsb 0 
NUM_ROWS_PLAY_IMAGE_SRAM		.dsb 1
NUM_COLS_PLAY_IMAGE_SRAM    	.dsb 1
PLAY_IMAGE_TILES_SRAM			.dsb 42

.ENDE



.ENUM $6083 
MINI_HELMET_ATTR_TWO_SRAM		.dsb 0			; second  
.ENDE


.ENUM $60A3 
RESET_SCHEDULE_MENU_SRAM  
.ENDE

.ENUM $6103 
P1_TIMEOUT_MENU_SRAM			.dsb 0			; uses 91 bytes 13 tiles long x 7 high
AUTOSKIP_MENU_SRAM				.dsb 0			; uses 65 bytes 13 tiles long x 5 high
SEASON_STANDINGS_MENU_SRAM		.dsb 0			; uses 384 bytes 32 tiles long x 12 high = 6103 to 6283
TEAM_RANKINGS_MENU_SRAM			.dsb 0			; uses 170 bytes 17 tiles long x 10 high
.ENDE

.ENUM $6203
P2_PLAY_CALL_MENU_SRAM 			.dsb 0 			; 
FINAL_RESET_MENU_SRAM   		.dsb 0      
.ENDE

.ENUM $6303
P2_TIMEOUT_MENU_SRAM 			.dsb 0      	; uses 91 bytes 13 tiles long x 7 high
.ENDE

_F}_SAVE_PART_OF_MENU_SCREENS_SRAM_VARIABLES

_F{_SAVE_RAM_DURING_CUTSCENES_SRAM_VARIABLES 				; SHARED


.ENUM $6003
   DRAW_TASK_CUT_SRAM       .dsb 5
.ENDE

.ENUM $6013
  SPRITE_CUT_SRAM           .dsb 240
  COLL_CUT_SRAM             .dsb 115
.ENDE
												;;; OVERWRITES SOME OF SPRITE CUT SRAM ;;; 
.ENUM $6101
   X_SCROLL_CUT_SRAM       .dsb 2				;*** bad location needs to be two bytes farther   
.ENDE


.ENUM $6183
  IRQ_CUT_SRAM              .dsb 19
.ENDE

.ENUM $61A3
  SPR_CHR_BANK_CUT_SRAM     .dsb 4
.ENDE

.ENUM $6203
  SPR_DRAW_STACK_SRAM     .dsb 28
  
_F}_SAVE_RAM_DURING_CUTSCENES_SRAM_VARIABLES 

_F{_SAVED_RANDOM_NUMBERS_SRAM_VARIABLES 

.ENUM $6403
	SAVED_RANDOMS: 			.dsb 0
	SAVED_RANDOM_1: 		.dsb 1
	SAVED_RANDOM_2: 		.dsb 1
	SAVED_RANDOM_3: 		.dsb 1
.ENDE 

_F}_SAVED_RANDOM_NUMBERS_SRAM_VARIABLES 

_F{_IN_GAME_STATS_SRAM_VARIABLES 
	
INJURY_STATUS_OFFSET 			=  P1_INJURIES_START 		- P1_GAME_STATS_START
IN_GAME_PLAYBOOK_OFFSET			=  P1_GM_PLAYBOOK_START 	- P1_GAME_STATS_START
IN_GAME_STARTERS_OFFSET			=  P1_GM_STARTERS_START		- P1_GAME_STATS_START
SIZE_OF_IN_GAME_STATS			=  P1_GM_PLAYBOOK_START 	- P1_GAME_STATS_START
PB_STARTER_INJURY_COND_SIZE		=  P2_GAME_STATS_START		- P1_GM_PLAYBOOK_START

.ENUM $6406	
    P1_GAME_STATS_START    	.dsb 0
	
	P1_QB_0_GM_STATS_START 	.dsb 10
	P1_QB_1_GM_STATS_START 	.dsb 10
	
	P1_RB_1_GM_STATS_START 	.dsb 16
	P1_RB_2_GM_STATS_START 	.dsb 16
	P1_RB_3_GM_STATS_START 	.dsb 16
	P1_RB_4_GM_STATS_START 	.dsb 16
	
	P1_WR_1_GM_STATS_START 	.dsb 16
	P1_WR_2_GM_STATS_START 	.dsb 16
	P1_WR_3_GM_STATS_START 	.dsb 16
	P1_WR_4_GM_STATS_START 	.dsb 16
	
	P1_TE_1_GM_STATS_START 	.dsb 16
	P1_TE_2_GM_STATS_START 	.dsb 16

	P1_RE_GM_STATS_START 	.dsb 5
	P1_NT_GM_STATS_START 	.dsb 5
	P1_LE_GM_STATS_START 	.dsb 5
	
	P1_ROLB_GM_STATS_START 	.dsb 5
	P1_RILB_GM_STATS_START 	.dsb 5
	P1_LILB_GM_STATS_START 	.dsb 5
	P1_LOLB_GM_STATS_START 	.dsb 5
	
	P1_RCB_GM_STATS_START 	.dsb 5
	P1_LCB_GM_STATS_START 	.dsb 5
	P1_FS_GM_STATS_START 	.dsb 5
	P1_SS_GM_STATS_START 	.dsb 5
	
	P1_K_GM_STATS_START 	.dsb 4
	P1_P_GM_STATS_START 	.dsb 3
	
	P1_GM_PLAYBOOK_START 	.dsb 4
	P1_GM_STARTERS_START 	.dsb 4
	P1_INJURIES_START 		.dsb 3
	P1_CONDITIONS_START 	.dsb 8
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	
	P2_GAME_STATS_START    	.dsb 0
	
	P2_QB_0_GM_STATS_START 	.dsb 10
	P2_QB_1_GM_STATS_START 	.dsb 10
	
	P2_RB_1_GM_STATS_START 	.dsb 16
	P2_RB_2_GM_STATS_START 	.dsb 16
	P2_RB_3_GM_STATS_START 	.dsb 16
	P2_RB_4_GM_STATS_START 	.dsb 16
	
	P2_WR_1_GM_STATS_START 	.dsb 16
	P2_WR_2_GM_STATS_START 	.dsb 16
	P2_WR_3_GM_STATS_START 	.dsb 16
	P2_WR_4_GM_STATS_START 	.dsb 16
	
	P2_TE_1_GM_STATS_START 	.dsb 16
	P2_TE_2_GM_STATS_START 	.dsb 16

	P2_RE_GM_STATS_START 	.dsb 5
	P2_NT_GM_STATS_START 	.dsb 5
	P2_LE_GM_STATS_START 	.dsb 5
	
	P2_ROLB_GM_STATS_START 	.dsb 5
	P2_RILB_GM_STATS_START 	.dsb 5
	P2_LILB_GM_STATS_START 	.dsb 5
	P2_LOLB_GM_STATS_START 	.dsb 5
	
	P2_RCB_GM_STATS_START 	.dsb 5
	P2_LCB_GM_STATS_START 	.dsb 5
	P2_FS_GM_STATS_START 	.dsb 5
	P2_SS_GM_STATS_START 	.dsb 5
	
	P2_K_GM_STATS_START 	.dsb 4
	P2_P_GM_STATS_START 	.dsb 3
	
	P2_GM_PLAYBOOK_START 	.dsb 4
	P2_GM_STARTERS_START 	.dsb 4
	P2_INJURIES_START 		.dsb 3
	P2_CONDITIONS_START 	.dsb 8

_F}_IN_GAME_STATS_SRAM_VARIABLES 

_F{_IN_GAME_STARTERS_SRAM_VARIABLES  
 
	DEF_STARTER_PLAYERS		.dsb 0	   ;
    GAME_PLAYERS[]			.dsb 0		
	P1_GM_PLAYERS			.dsb 0	   ; $6610
	P1_OFF_STARTERS			.dsb 0
	P1_SKILL_STARTERS		.dsb 12
	OL_STARTERS[]			.dsb 0 	   
	P1_OL_STARTERS			.dsb 10 
	P1_DEF_STARTERS			.dsb 22
	P1_K_STARTER			.dsb 2
	P1_P_STARTER			.dsb 2
	KR_PR_STARTERS[]		.dsb 0 
	P1_KR_STARTER			.dsb 2
	P1_PR_STARTER			.dsb 2
	
	P2_GM_PLAYERS			.dsb 0    ; $6644
	P2_OFF_STARTERS			.dsb 0
	P2_SKILL_STARTERS		.dsb 12
	P2_OL_STARTERS			.dsb 10
	P2_DEF_STARTERS			.dsb 22
	P2_K_STARTER			.dsb 2
	P2_P_STARTER			.dsb 2 
	P2_KR_STARTER			.dsb 2
	P2_PR_STARTER			.dsb 2
.ENDE


	CURRENT_IN_GAME_TARGET_ID[]			= P1_SKILL_STARTERS +3 ; 
	CURRENT_IN_GAME_DEFENDER_ID[]		= P1_DEF_STARTERS +1 
	CURRENT_IN_GAME_KICKER_ID			= P1_K_STARTER + 1
	CURRENT_IN_GAME_PUNTER_ID			= P1_P_STARTER + 1
	CURRENT_IN_GAME_KR_ID				= P1_KR_STARTER + 1
	CURRENT_IN_GAME_PR_ID				= P1_PR_STARTER + 1
	CURRENT_IN_GAME_RUNNER_ID[]			=  GAME_PLAYERS[] +1
	
    NUMBER_OF_IN_GM_STARTERS			= (P2_GM_PLAYERS - P1_GM_PLAYERS)/2 
    IN_GAME_STARTERS_OFFSET				= P1_GM_STARTERS_START - P1_GAME_STATS_START
	P1_PLAYER_TEAM_ID 					= P1_GM_PLAYERS;
	P1_PLAYER_ROSTER_ID  				= P1_GM_PLAYERS+1;
	P1_PLAYER_CURRENT_QB_ROSTER_ID 		= P1_GM_PLAYERS+1;
	
	P2_PLAYER_TEAMID 					= P2_GM_PLAYERS;
	P2_PLAYER_ROSTER_ID  				= P2_GM_PLAYERS+1;
	P2_PLAYER_CURRENT_QB_ROSTER_ID 		= P2_GM_PLAYERS+1;	
	
	P2_GAME_PLAYERS_OFFSET				= P2_GM_PLAYERS - P1_GM_PLAYERS
	
_F}_IN_GAME_STARTERS_SRAM_VARIABLES	

_F{_CPU_BOOSTS_SAVE_RAM_VARIABLES 

.ENUM $6678	
	
	CPU_BOOSTS				.dsb 0
	CPU_DEF_MS_BOOST		.dsb 1 
	CPU_OFF_MS_BOOST		.dsb 1
	CPU_DEF_INT_BOOST		.dsb 1
    CPU_PASS_CONTROL_BOOST	.dsb 1
	CPU_RECEPTION_BOOST		.dsb 1
	CPU_BOOST_INDEX			.dsb 1


_F}_CPU_BOOSTS_SAVE_RAM_VARIABLES 

_F{_PLAYBOOK_SAVE_RAM_VARIABLES 

    SIZE_OF_EACH_PLAYBOOK	= $08	
    P1_P2_PLAYBOOKS[]		.dsb 0
	P1_PLAYBOOK_EDIT		.dsb 8
	P2_PLAYBOOK_EDIT		.dsb 8
	OFFSET_TO_P1_PLAYBOOK	= $0 
	OFFSET_TO_P2_PLAYBOOK 	= P2_PLAYBOOK_EDIT - P1_PLAYBOOK_EDIT
	
_F}_PLAYBOOK_SAVE_RAM_VARIABLES 

_F{_IN_GAME_TEAM_STATS_SAVE_RAM_VARIABLES 	

	IN_GAME_TEAM_STATS[]	.dsb 0 	
	P1_FIRST_DOWNS			.dsb 1
	P2_FIRST_DOWNS			.dsb 1
	
	P1_GM_RUSHES			.dsb 1
	P2_GM_RUSHES			.dsb 1
	
	P1_GM_RUSH_YARDS		.dsb 2
	P2_GM_RUSH_YARDS		.dsb 2
	
	P1_GM_PASS_YARDS		.dsb 2
	P2_GM_PASS_YARDS		.dsb 2
	END_OF_TEAM_STATS		.dsb 0 
	SIZE_OF_TEAM_STATS =  END_OF_TEAM_STATS -IN_GAME_TEAM_STATS[]


_F}_IN_GAME_TEAM_STATS_SAVE_RAM_VARIABLES 	

_F{_WEEK_TO_SKIP_TO_SAVE_RAM_VARIABLE
	
	WEEK_TO_SKIP_TO			.dsb 1						; *** could move with other schedule variables

_F}_WEEK_TO_SKIP_TO_SAVE_RAM_VARIABLE

_F{_TEAM_SEASON_CONTROL_TYPE_SAVE_RAM_VARIABLES
	
	TEAM_TYPE_SEASON		.dsb 28
	
_F}_TEAM_SEASON_CONTROL_TYPE_SAVE_RAM_VARIABLES	
	
_F{_CHECKSUM_AND_CHECK_VALUE_SAVE_RAM_VARIABLES 	

	SRAM_CHECK_VAL			.dsb 7
	SRAM_CHECKSUM			.dsb 2

_F}_CHECKSUM_AND_CHECK_VALUE_SAVE_RAM_VARIABLES 

_F{_PRO_BOWL_PLAYERS_PLAYBOOK_SAVE_RAM_VARIABLES 

	SEASON_INFO_START		 .dsb 0
    SRAM_PRO_BOWL_STARTERS[] .dsb 0 	
	SRAM_AFC_STARTERS		 .dsb 8		; $66C0 index to their team and roster id
	SRAM_NFC_STARTERS		 .dsb 8
	
	SIZE_OF_PRO_BOWL_STARTERS		= SRAM_NFC_STARTERS - SRAM_AFC_STARTERS
	
	PRO_BOWL_PLAYER_INFO	.dsb 0 		; $66D0 team followed by roster id 	
	AFC_PLAYER_INFO			.dsb 60
	NFC_PLAYER_INFO			.dsb 60
    SRAM_AFC_PLAYBOOK		.dsb 8
	SRAM_NFC_PLAYBOOK		.dsb 8
	
	SIZE_OF_PRO_BOWL_PLAYER_INFO		= NFC_PLAYER_INFO - AFC_PLAYER_INFO
	OFFSET_TO_NFC_PLAYERS   			= NFC_PLAYER_INFO - AFC_PLAYER_INFO

_F}_PRO_BOWL_PLAYERS_PLAYBOOK_SAVE_RAM_VARIABLES 
 
_F{_CURRENT_SEASON_WEEK_SAVE_RAM_VARIABLES 
  	
										; $6758
   CURRENT_WEEK_IN_SEASON			.dsb 1
   CURRENT_GAME_IN_WEEK				.dsb 1
   WEEKLY_MATCHUPS_START    		.dsb 28 
   
_F}_CURRENT_SEASON_WEEK_SAVE_RAM_VARIABLES  
   
_F{_PLAYOFF_RESULTS_SAVE_RAM_VARIABLES 

	SIZE_OF_EACH_PLAYOFF_RESULT	= 	$04 
   
   PLAYOFF_RESULTS_START[]    		.dsb 0     ; $
   
   AFC_WILD_CARD_TWO_HOME_TEAM_ID 	.dsb 1		; 
   AFC_WILD_CARD_TWO_AWAY_TEAM_ID	.dsb 1
   AFC_WILD_CARD_TWO_HOME_SCORE		.dsb 1
   AFC_WILD_CARD_TWO_AWAY_SCORE		.dsb 1
   
   NFC_WILD_CARD_TWO_HOME_TEAM_ID 	.dsb 1		; 
   NFC_WILD_CARD_TWO_AWAY_TEAM_ID	.dsb 1
   NFC_WILD_CARD_TWO_HOME_SCORE		.dsb 1
   NFC_WILD_CARD_TWO_AWAY_SCORE		.dsb 1
   
   AFC_WILD_CARD_ONE_HOME_TEAM_ID 	.dsb 1		; 
   AFC_WILD_CARD_ONE_AWAY_TEAM_ID	.dsb 1
   AFC_WILD_CARD_ONE_HOME_SCORE		.dsb 1
   AFC_WILD_CARD_ONE_AWAY_SCORE		.dsb 1
   
   NFC_WILD_CARD_ONE_HOME_TEAM_ID 	.dsb 1		; 
   NFC_WILD_CARD_ONE_AWAY_TEAM_ID	.dsb 1
   NFC_WILD_CARD_ONE_HOME_SCORE		.dsb 1
   NFC_WILD_CARD_ONE_AWAY_SCORE		.dsb 1
   
   AFC_DIVISIONAL_TWO_HOME_TEAM_ID 	.dsb 1
   AFC_DIVISIONAL_TWO_AWAY_TEAM_ID  .dsb 1
   AFC_DIVISIONAL_TWO_HOME_SCORE 	.dsb 1
   AFC_DIVISIONAL_TWO_AWAY_SCORE    .dsb 1
   
   NFC_DIVISIONAL_TWO_HOME_TEAM_ID 	.dsb 1
   NFC_DIVISIONAL_TWO_AWAY_TEAM_ID  .dsb 1
   NFC_DIVISIONAL_TWO_HOME_SCORE 	.dsb 1
   NFC_DIVISIONAL_TWO_AWAY_SCORE    .dsb 1
  
   AFC_DIVISIONAL_ONE_HOME_TEAM_ID 	.dsb 1
   AFC_DIVISIONAL_ONE_AWAY_TEAM_ID  .dsb 1
   AFC_DIVISIONAL_ONE_HOME_SCORE 	.dsb 1
   AFC_DIVISIONAL_ONE_AWAY_SCORE    .dsb 1
   
   NFC_DIVISIONAL_ONE_HOME_TEAM_ID 	.dsb 1
   NFC_DIVISIONAL_ONE_AWAY_TEAM_ID  .dsb 1
   NFC_DIVISIONAL_ONE_HOME_SCORE 	.dsb 1
   NFC_DIVISIONAL_ONE_AWAY_SCORE    .dsb 1
   

   
	AFC_CHAMP_HOME_TEAM_ID 			.dsb 1
	AFC_CHAMP_AWAY_TEAM_ID  			.dsb 1
	AFC_CHAMP_HOME_SCORE 			.dsb 1
	AFC_CHAMP_AWAY_SCORE    			.dsb 1
   
   NFC_CHAMP_HOME_TEAM_ID 			.dsb 1
   NFC_CHAMP_AWAY_TEAM_ID  			.dsb 1
   NFC_CHAMP_HOME_SCORE 			.dsb 1
   NFC_CHAMP_AWAY_SCORE    			.dsb 1
   
   SUPERBOWL_MATCHUP_INFO[]			.dsb 0
   SUPERBOWL_HOME_TEAM_ID 			.dsb 1
   SUPERBOWL_AWAY_TEAM_ID  			.dsb 1
   SUPERBOWL_HOME_SCORE 			.dsb 1
   SUPERBOWL_AWAY_SCORE    			.dsb 1
 
_F}_PLAYOFF_RESULTS_SAVE_RAM_VARIABLES  
   
_F{_PLAYOFF_TEAMS_SAVE_RAM_VARIABLES 
 
   PLAYOFF_TEAMS[]				.dsb 0		; 67A2
   DIVISION_WINNERS[]			.dsb 0
   AFCE_DIVISION_CHAMP			.dsb 1
   AFCC_DIVISION_CHAMP			.dsb 1
   AFCW_DIVISION_CHAMP			.dsb 1
   NFCE_DIVISION_CHAMP			.dsb 1
   NFCC_DIVISION_CHAMP			.dsb 1
   NFCW_DIVISION_CHAMP			.dsb 1
         
   WILDCARD_TEAMS				.dsb 0
   AFC_WILD_CARD_ONE_TEAM_ID	.dsb 1
   AFC_WILD_CARD_TWO_TEAM_ID	.dsb 1
   AFC_WILD_CARD_THREE_TEAM_ID  .dsb 1
   NFC_WILD_CARD_ONE_TEAM_ID	.dsb 1
   NFC_WILD_CARD_TWO_TEAM_ID	.dsb 1
   NFC_WILD_CARD_THREE_TEAM_ID  .dsb 1
   
_F}_PLAYOFF_TEAMS_SAVE_RAM_VARIABLES   
 
_F{_SEASON_STATS_SAVE_RAM_VARIABLES	



 
   TEAM_SEASON_INFO_START 		.dsb 0
   TEAM_1_SEASON_INFO			.dsb 208
   TEAM_2_SEASON_INFO			.dsb 208
   TEAM_3_SEASON_INFO			.dsb 208
   TEAM_4_SEASON_INFO			.dsb 208
   TEAM_5_SEASON_INFO			.dsb 208
   TEAM_6_SEASON_INFO			.dsb 208
   TEAM_7_SEASON_INFO			.dsb 208
   TEAM_8_SEASON_INFO			.dsb 208 
   TEAM_9_SEASON_INFO			.dsb 208
   EMPTY_SEASON_INFO			.dsb 260
   TEAM_10_SEASON_INFO			.dsb 208
   TEAM_11_SEASON_INFO			.dsb 208
   TEAM_12_SEASON_INFO			.dsb 208
   TEAM_13_SEASON_INFO			.dsb 208
   TEAM_14_SEASON_INFO			.dsb 208
   TEAM_15_SEASON_INFO			.dsb 208
   TEAM_16_SEASON_INFO			.dsb 208 
   TEAM_17_SEASON_INFO			.dsb 208
   TEAM_18_SEASON_INFO			.dsb 208
   TEAM_19_SEASON_INFO			.dsb 208
   TEAM_20_SEASON_INFO			.dsb 208
   TEAM_21_SEASON_INFO			.dsb 208
   TEAM_22_SEASON_INFO			.dsb 208
   TEAM_23_SEASON_INFO			.dsb 208
   TEAM_24_SEASON_INFO			.dsb 208
   TEAM_25_SEASON_INFO			.dsb 208
   TEAM_26_SEASON_INFO			.dsb 208 
   TEAM_27_SEASON_INFO			.dsb 208
   TEAM_28_SEASON_INFO			.dsb 208
   TEAM_SEASON_INFO_END			.dsb 0
   
 SIZE_OF_TEAM_SEASON_INFO				= TEAM_SEASON_INFO_END	 - TEAM_SEASON_INFO_START ;
SIZE_OF_SEASON_INFO						= TEAM_SEASON_INFO_END - SEASON_INFO_START 
   
	






		
_F}_SEASON_STATS_SAVE_RAM_VARIABLES	

_F{_FREE_SPACE_SAVE_RAM_VARIABLES
	
   SRAM_FREE_SPACE				.dsb 142
   SRAM_END  					.dsb 0 
 
 .ENDE
_F}_FREE_SPACE_SAVE_RAM_VARIABLES	 


	