
_F{_IN_GAME_PLAYER_STAT_INDEXES

; IN GAME STAT INDEXES

; QB 
.ENUM $00
QB_PASS_ATTEMPTS_IN_GAME_STAT_INDEX			.dsb 1 ;
QB_PASS_COMPLETIONS_IN_GAME_STAT_INDEX		.dsb 1 ;
QB_PASS_TD_IN_GAME_STAT_INDEX				.dsb 1 ; 
QB_PASS_INT_IN_GAME_STAT_INDEX				.dsb 1 ; 
QB_PASS_YDS_IN_GAME_STAT_INDEX				.dsb 1 ;
QB_PASS_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ; multiplier 1= 256
QB_RUSH_ATTEMPTS_IN_GAME_STAT_INDEX			.dsb 1 ;
QB_RUSH_YDS_IN_GAME_STAT_INDEX				.dsb 1 ; 
QB_RUSH_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ;  multiplier 1= 256
QB_RUSH_TD_IN_GAME_STAT_INDEX				.dsb 1
.ENDE 

; RB/WR/TE 
.ENUM $00
SKILL_REC_IN_GAME_STAT_INDEX				.dsb 1 ;
SKILL_REC_YDS_IN_GAME_STAT_INDEX			.dsb 1 ;
SKILL_REC_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ;
SKILL_REC_TD_IN_GAME_STAT_INDEX				.dsb 1 ; 
SKILL_KR_ATT_IN_GAME_STAT_INDEX				.dsb 1 ; 
SKILL_KR_YDS_IN_GAME_STAT_INDEX			    .dsb 1 ;
SKILL_KR_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ; passing yards multiplier 1= 256
SKILL_KR_TD_IN_GAME_STAT_INDEX				.dsb 1
SKILL_PR_ATT_IN_GAME_STAT_INDEX				.dsb 1 ; 
SKILL_PR_YDS_IN_GAME_STAT_INDEX			    .dsb 1 ;
SKILL_PR_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ; passing yards multiplier 1= 256
SKILL_PR_TD_IN_GAME_STAT_INDEX				.dsb 1
SKILL_RUN_ATT_IN_GAME_STAT_INDEX			.dsb 1 ;
SKILL_RUN_YDS_IN_GAME_STAT_INDEX			.dsb 1 ;
SKILL_RUN_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ;
SKILL_RUN_TD_IN_GAME_STAT_INDEX				.dsb 1 ; 
.ENDE 


; DEFENDER
.ENUM $00
DEF_SACKS_IN_GAME_STAT_INDEX				.dsb 1 ;
DEF_INTS_IN_GAME_STAT_INDEX					.dsb 1 ;
DEF_INT_YDS_IN_GAME_STAT_INDEX				.dsb 1 ;
DEF_INT_YDS_MULTI_IN_GAME_STAT_INDEX		.dsb 1 ;
DEF_INT_TDS_IN_GAME_STAT_INDEX				.dsb 1 ; 	
.ENDE 

; KICKER
.ENUM $00
XP_ATT_IN_GAME_STAT_INDEX					.dsb 1 ;
XP_MADE_IN_GAME_STAT_INDEX					.dsb 1 ;
FG_ATT_IN_GAME_STAT_INDEX					.dsb 1 ;
FG_MADE_IN_GAME_STAT_INDEX					.dsb 1 ;
.ENDE 

; PUNTER
.ENUM $00
PUNTS_IN_GAME_STAT_INDEX					.dsb 1 ;
PUNT_YDS_IN_GAME_STAT_INDEX					.dsb 1 ;
PUNT_YDS_MULTI_IN_GAME_STAT_INDEX			.dsb 1 ;
.ENDE 

_F}_IN_GAME_PLAYER_STAT_INDEXES

_F{_SEASON_PLAYER_STAT_INDEXES


; QB 
.ENUM $00
QB_PASS_ATTEMPTS_SEASON_STAT_INDEX			.dsb 1 ;
QB_PASS_COMPLETIONS_SEASON_STAT_INDEX		.dsb 1 ;
QB_PASS_TD_SEASON_STAT_INDEX				.dsb 1 ; 
QB_PASS_INT_SEASON_STAT_INDEX				.dsb 1 ; 
QB_PASS_YDS_SEASON_STAT_INDEX				.dsb 1 ;

QB_RUSH_ATTEMPTS_SEASON_STAT_INDEX			.dsb 1 ;
QB_RUSH_YDS_SEASON_STAT_INDEX				.dsb 1 ; 
QB_RUSH_TD_SEASON_STAT_INDEX				.dsb 1 ;

SKILL_REC_SEASON_STAT_INDEX				    .dsb 1 ; 08
SKILL_REC_YDS_SEASON_STAT_INDEX			    .dsb 1 ; 09
SKILL_REC_TD_SEASON_STAT_INDEX				.dsb 1 ; 0A

SKILL_KR_ATT_SEASON_STAT_INDEX				.dsb 1 ; 0B 
SKILL_KR_YDS_SEASON_STAT_INDEX			    .dsb 1 ; 0C
SKILL_KR_TDS_SEASON_STAT_INDEX				.dsb 1 ; 0D 

SKILL_PR_ATT_SEASON_STAT_INDEX				.dsb 1 ; 0E 
SKILL_PR_YDS_SEASON_STAT_INDEX			    .dsb 1 ; 0F
SKILL_PR_TDS_SEASON_STAT_INDEX				.dsb 1 ; 10

SKILL_RUN_ATT_SEASON_STAT_INDEX				.dsb 1 ; 11
SKILL_RUN_YDS_SEASON_STAT_INDEX				.dsb 1 ; 12
SKILL_RUN_TD_SEASON_STAT_INDEX				.dsb 1 ; 13 

DEF_SACKS_SEASON_STAT_INDEX					.dsb 1 ;
DEF_INTS_SEASON_STAT_INDEX					.dsb 1 ;
DEF_INT_YDS_SEASON_STAT_INDEX				.dsb 1 ;
DEF_INT_TDS_SEASON_STAT_INDEX				.dsb 1 ; 	 

XP_ATT_SEASON_STAT_INDEX					.dsb 1 ;
XP_MADE_SEASON_STAT_INDEX					.dsb 1 ;
FG_ATT_SEASON_STAT_INDEX					.dsb 1 ;
FG_MADE_SEASON_STAT_INDEX					.dsb 1 ;

PUNTS_SEASON_STAT_INDEX						.dsb 1 ;
PUNT_YDS_SEASON_STAT_INDEX					.dsb 1 ;
.ENDE 

_F}_SEASON_PLAYER_STAT_INDEXES

_F{_SEASON_LEADERS_STAT_INDEXES

;;;;; SEASON LEADERS SORTING INDEXES ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
.ENUM $00

SORT_ON_QB_RATING_INDEX						.dsb 1
SORT_ON_COMP_PCT_INDEX						.dsb 1
SORT_ON_PASS_ATT_INDEX						.dsb 1
SORT_ON_PASS_COMP_INDEX						.dsb 1
SORT_ON_PASS_YARDS_INDEX					.dsb 1
SORT_ON_PASS_YARDS_PER_ATT_INDEX			.dsb 1
SORT_ON_PASS_TDS_INDEX						.dsb 1
SORT_ON_INT_PCT_INDEX						.dsb 1


SORT_ON_RECEPTIONS_INDEX					.dsb 1				
SORT_ON_REC_YARDS_INDEX						.dsb 1
SORT_ON_YARDS_PER_REC_INDEX					.dsb 1
SORT_ON_REC_TDS_INDEX						.dsb 1

SORT_ON_RUSH_YARDS_INDEX					.dsb 1
SORT_ON_RUSH_ATT_INDEX						.dsb 1
SORT_ON_YARDS_PER_RUSH_INDEX				.dsb 1
SORT_ON_RUSH_TDS_INDEX						.dsb 1

SORT_ON_TOTAL_PTS_INDEX						.dsb 1			; $10
SORT_ON_TOTAL_TDS_INDEX						.dsb 1
SORT_ON_EXTRA_PTS_INDEX						.dsb 1
SORT_ON_TOTAL_FGS_INDEX						.dsb 1

SORT_ON_PUNTING_AVG_INDEX					.dsb 1
SORT_ON_TOTAL_PUNTS_INDEX					.dsb 1

SORT_ON_INTERCEPTIONS_INDEX					.dsb 1
SORT_ON_INT_YARDS_INDEX						.dsb 1
SORT_ON_INT_TDS_INDEX						.dsb 1

SORT_ON_SACKS_INDEX							.dsb 1			; $19 

SORT_ON_PUNT_RET_AVERAGE_INDEX				.dsb 1
SORT_ON_PUNT_RET_YARDS_INDEX				.dsb 1
SORT_ON_PUNT_RET_TDS						.dsb 1
SORT_ON_PUNT_RET_YARDS_INDEX_DUPE_ONE		.dsb 1

SORT_ON_KICK_RET_AVERAGE_INDEX				.dsb 1
SORT_ON_KICK_RET_YARDS_INDEX				.dsb 1
SORT_ON_KICK_RET_TDS						.dsb 1
SORT_ON_PUNT_RET_YARDS_INDEX_DUPE_TWO		.dsb 1

_F}_SEASON_LEADERS_STAT_INDEXES

_F{_UPDATE_IN_GAME_STATS_INDEXES

.ENDE
;;;;; FUNCTION INDEXES ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; QB 
.ENUM $00
UPDATE_QB_PASS_ATT_IN_GAME_INDEX	        .dsb 1 ;
UPDATE_QB_PASS_COMP_IN_GAME_INDEX		    .dsb 1 ;
UPDATE_QB_PASS_TD_IN_GAME_INDEX				.dsb 1 ; 
UPDATE_QB_PASS_INT_IN_GAME_INDEX			.dsb 1 ; 
UPDATE_QB_PASS_YDS_IN_GAME_INDEX			.dsb 1 ;
UPDATE_QB_RUSH_ATT_IN_GAME_INDEX		    .dsb 1 ;
UPDATE_QB_RUSH_YDS_IN_GAME_INDEX			.dsb 1 ; 
UPDATE_QB_RUSH_TD_IN_GAME_INDEX			    .dsb 1
														; RB/WR/TE
UPDATE_REC_IN_GAME_INDEX					.dsb 1 ;
UPDATE_REC_YDS_IN_GAME_INDEX		        .dsb 1 ;
UPDATE_REC_TD_IN_GAME_INDEX			        .dsb 1 ; 
UPDATE_KR_ATT_IN_GAME_INDEX			        .dsb 1 ; 
UPDATE_KR_YDS_IN_GAME_INDEX		            .dsb 1 ;
UPDATE_KR_TDS_IN_GAME_INDEX			        .dsb 1
UPDATE_PR_ATT_IN_GAME_INDEX			        .dsb 1 ; 
UPDATE_PR_YDS_IN_GAME_INDEX		            .dsb 1 ;
UPDATE_PR_TDS_IN_GAME_INDEX			        .dsb 1 ; 
UPDATE_RUN_ATT_IN_GAME_INDEX		        .dsb 1 ;
UPDATE_RUN_YDS_IN_GAME_INDEX		        .dsb 1 ;
UPDATE_RUN_TD_IN_GAME_INDEX			        .dsb 1 ; 

UPDATE_DEF_SACKS_IN_GAME_INDEX			    .dsb 1 ;
UPDATE_DEF_INTS_IN_GAME_INDEX				.dsb 1 ;
UPDATE_DEF_INT_YDS_IN_GAME_INDEX			.dsb 1 ;
UPDATE_DEF_INT_TDS_IN_GAME_INDEX			.dsb 1

UPDATE_XP_ATT_IN_GAME_INDEX				    .dsb 1 ;
UPDATE_XP_MADE_IN_GAME_INDEX				.dsb 1 ;
UPDATE_FG_ATT_IN_GAME_INDEX				    .dsb 1 ;
UPDATE_FG_MADE_IN_GAME_INDEX				.dsb 1 ;

UPDATE_PUNTS_IN_GAME_INDEX				    .dsb 1 ;
UPDATE_PUNT_YDS_IN_GAME_INDEX				.dsb 1 ;

.ENDE 

_F}_UPDATE_IN_GAME_STATS_INDEXES

_F{_GET_IN_GAME_STATS_INDEXES

; QB 
.ENUM $00
GET_QB_PASS_ATT_IN_GAME_INDEX	        .dsb 1 ;
GET_QB_PASS_COMP_IN_GAME_INDEX		    .dsb 1 ;
GET_QB_PASS_TD_IN_GAME_INDEX				.dsb 1 ; 
GET_QB_PASS_INT_IN_GAME_INDEX			.dsb 1 ; 
GET_QB_PASS_YDS_IN_GAME_INDEX			.dsb 1 ;
GET_QB_RUSH_ATT_IN_GAME_INDEX		    .dsb 1 ;
GET_QB_RUSH_YDS_IN_GAME_INDEX			.dsb 1 ; 
GET_QB_RUSH_TD_IN_GAME_INDEX			    .dsb 1
														; RB/WR/TE
GET_REC_IN_GAME_INDEX					.dsb 1 ;
GET_REC_YDS_IN_GAME_INDEX		        .dsb 1 ;
GET_REC_TD_IN_GAME_INDEX			        .dsb 1 ; 
GET_KR_ATT_IN_GAME_INDEX			        .dsb 1 ; 
GET_KR_YDS_IN_GAME_INDEX		            .dsb 1 ;
GET_KR_TDS_IN_GAME_INDEX			        .dsb 1
GET_PR_ATT_IN_GAME_INDEX			        .dsb 1 ; 
GET_PR_YDS_IN_GAME_INDEX		            .dsb 1 ;
GET_PR_TDS_IN_GAME_INDEX			        .dsb 1 ; 
GET_RUN_ATT_IN_GAME_INDEX		        .dsb 1 ;
GET_RUN_YDS_IN_GAME_INDEX		        .dsb 1 ;
GET_RUN_TD_IN_GAME_INDEX			        .dsb 1 ; 

GET_DEF_SACKS_IN_GAME_INDEX			    .dsb 1 ;
GET_DEF_INTS_IN_GAME_INDEX				.dsb 1 ;
GET_DEF_INT_YDS_IN_GAME_INDEX			.dsb 1 ;
GET_DEF_INT_TDS_IN_GAME_INDEX			.dsb 1

GET_XP_ATT_IN_GAME_INDEX				    .dsb 1 ;
GET_XP_MADE_IN_GAME_INDEX				.dsb 1 ;
GET_FG_ATT_IN_GAME_INDEX				    .dsb 1 ;
GET_FG_MADE_IN_GAME_INDEX				.dsb 1 ;

GET_PUNTS_IN_GAME_INDEX				    .dsb 1 ;
GET_PUNT_YDS_IN_GAME_INDEX				.dsb 1 ;

.ENDE 

_F}_GET_IN_GAME_STATS_INDEXES

_F{_SRAM_ROSTER_SEASON_STAT_INDEXES

.ENUM $00
	QB1_SEASON_STATS_OFFSET             	.dsb 9	; OFFSET 0x00
	QB2_SEASON_STATS_OFFSET             	.dsb 9  ; OFFSET 0x09
	RB1_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x12
	RB2_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x1E
	RB3_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x2A
	RB4_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x36
	WR1_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x42
	WR2_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x4E
	WR3_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x5A
	WR4_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x66
	TE1_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x72
	TE2_SEASON_STATS_OFFSET             	.dsb 12 ; OFFSET 0x7E
	RE_SEASON_STATS_OFFSET              	.dsb 03 ; OFFSET 0x8A
	NT_SEASON_STATS_OFFSET              	.dsb 03 ; OFFSET 0x8D
	LE_SEASON_STATS_OFFSET              	.dsb 03 ; OFFSET 0x90
	ROLB_SEASON_STATS_OFFSET            	.dsb 03 ; OFFSET 0x93
	RILB_SEASON_STATS_OFFSET            	.dsb 03 ; OFFSET 0x96
	LILB_SEASON_STATS_OFFSET            	.dsb 03 ; OFFSET 0x99
	LOLB_SEASON_STATS_OFFSET           		.dsb 03 ; OFFSET 0x9C
	RCB_SEASON_STATS_OFFSET             	.dsb 03 ; OFFSET 0x9F
	LCB_SEASON_STATS_OFFSET             	.dsb 03 ; OFFSET 0xA2
	FS_SEASON_STATS_OFFSET              	.dsb 03 ; OFFSET 0xA5
	SS_SEASON_STATS_OFFSET              	.dsb 03 ; OFFSET 0xA8
	K_SEASON_STATS_OFFSET               	.dsb 04 ; OFFSET 0xAB
	P_SEASON_STATS_OFFSET               	.dsb 03 ; OFFSET 0xAF
	WINS_SEASON_STATS_OFFSET            	.dsb 01 ; OFFSET 0xB2
	LOSSES_SEASON_STATS_OFFSET          	.dsb 01 ; OFFSET 0xB3 
	TIES_SEASON_STATS_OFFSET            	.dsb 01 ; OFFSET 0xB4
	POINTS_FOR_SEASON_STATS_OFFSET      	.dsb 02 ; OFFSET 0xB5
	POINTS_ALLOWED_SEASON_STATS_OFFSET  	.dsb 02 ; OFFSET 0xB7
	PASS_YDS_ALLOWED_SEASON_STATS_OFFSET	.dsb 02 ; OFFSET 0xB9
	RUSH_YDS_ALLOWED_SEASON_STATS_OFFSET	.dsb 02 ; OFFSET 0xBB
	PLAYBOOK_SEASON_STATS_OFFSET        	.dsb 04 ; OFFSET 0xBD
	STARTERS_SEASON_STATS_OFFSET        	.dsb 04 ; OFFSET 0xC1
	INJURIES_SEASON_STATS_OFFSET        	.dsb 03 ; OFFSET 0xC5
	CONDITIONS_SEASON_STATS_OFFSET      	.dsb 08 ; OFFSET 0xC8
	END_OF_SEASON_STATS						.dsb 00
.ENDE

_F}_SRAM_ROSTER_SEASON_STAT_INDEXES