_F{_VARIOUS_TILE_IDS

OFFSET_TO_NUMBER_TILES 				= $30
OFFSET_TO_HIGHLIGHTED_NUMBER_TILES	= $E0				; used with playoff bracket

OFFSET_TO_TEAM_NAME					= $40
OFFSET_TO_TEAM_CTRL_TEXT			= $64				; use math to determine


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
PLAYER_SELECTED_X_TILE_ID			= $02

BLANK_TILE_ID              			= $00
SPRITE_SCRIPT_BLANK_TILE_ID			= $3F
START_OF_LETTERS        			= $41
END_OF_LETTERS						= $5A   
START_OF_LOWER_CASE 				= $61
UPPER_CASE_BIT_MASK 				= $DF
ASCII_SPACE            				= $20				; *** replace with space tile id
SPACE_TILE_ID 	 					= $20
DECIMAL_TILE_ID						= $2E
PERIOD_TILE_ID 						= $2E
LAST_NUMBER_TILE_ID					= $39
COLON_TILE_ID						= $3A
DASH_TILE_ID		    			= $3B

LARGE_SCORE_DASH_TILE_ID			= $2D 


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
P1_OVERHEAD_TILE_ID         		= $2D
P2_OVERHEAD_TILE_ID         		= $2F
OFFSCREEN_ARROW_TILE_ID    			= $33
;;;;; BALL TILE IDS ;;;;;;;;;;;;;;;;;;;;;;

VERTICAL_BALL_TILE_ID				= $A1
FORTY_FIVE_BALL_TILE_ID				= $A3
HORIZONTAL_BALL_TILE_ID				= $A9
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

TEAM_SELECT_P1_VERT_BAR_TILE_ID		= $27
TEAM_SELECT_P2_VERT_BAR_TILE_ID		= $2C
TEAM_SELECT_P2_ARROW_TILE_ID		= $2D
TEAM_SELECT_P1_ARROW_TILE_ID		= $2F
PLAYER_SELECTED_X_TILE_ID			= $02

INJURY_MARKER_X_TILE_ID				= $82

;;;; KICK BAR TILE IDS ;;;;;;;;;;;;

LEFT_KICKBAR_BORDER_TILE_ID 		= $04
RIGHT_KICKBAR_BORDER_TILE_ID 		= $05
KICK_BAR_BLACK_FILL_TILE_ID			= $06 

P1_KB_RED_ONE_QTR_FILL_TILE_ID		= $07  
P1_KB_RED_HALF_FULL_TILE_ID			= $08 
P1_KB_RED_THREE_QTR_FILL_TILE_ID	= $09
KB_RED_FULL_TILE_ID					= $0A 
P2_KB_RED_ONE_QTR_FILL_TILE_ID		= $0B  
P2_KB_RED_HALF_FULL_TILE_ID			= $0C 
P2_KB_RED_THREE_QTR_FILL_TILE_ID	= $0D


 
P1_KB_BLUE_ONE_QTR_FILL_TILE_ID		= $0E  
P1_KB_BLUE_HALF_FULL_TILE_ID		= $0F 
P1_KB_BLUE_THREE_QTR_FILL_TILE_ID	= $11
KB_BLUE_FULL_TILE_ID				= $12 
P2_KB_BLUE_ONE_QTR_FILL_TILE_ID		= $13  
P2_KB_BLUE_HALF_FULL_TILE_ID		= $14 
P2_KB_BLUE_THREE_QTR_FILL_TILE_ID	= $15

FG_XP_ARROW_TILE_ID					= $33
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
DIVISION_WINNER_TILE_ID				= $19
WILD_CARD_TEAM_TILE_ID				= $5F




;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SCHEDULE_LINE_TILE_ID				= $E3
MATCHUP_X_TILE_ID					= $E4	; used between matchups schedule		

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; LEADER SCREEN TILE IDS ;;;;;;;;;;;;;;;
PERCENT_SIGN_LEADERS_TILE_ID		= $C4
FG_XP_SLASH_LEADERS_TILE_ID			= $C5

;;; PLAYER DATA SKILL BAR TILE IDS ;;;;;;;;;;;;;;;

LEFT_END_OF_SKILL_BAR_TILE_ID		= $F0
RIGHT_END_OF_SKILL_BAR_TILE_ID		= $F1
BG_COLOR_SKILL_BAR_TILE_ID			= $F2
FULL_SKILL_BAR_TILE_ID				= $F3
HALF_FULL_SKILL_BAR_TILE_ID			= $ED


P1_OVERHEAD_TILE_ID 					= $2D
P2_OVERHEAD_TILE_ID 					= $2F
PASS_TARGET_ONSCREEN_TILE_ID			= $31
OFFSCREEN_TARGET_TILE_ID  				= $33
BALL_X_MARKER_TILE_ID					= $C7 

_F}_VARIOUS_TILE_IDS


